### PR TITLE
feat(config): add Minoston mp21zp config file

### PR DESCRIPTION
**Pull request by gazpachoking**
Adds a configuration file for the Minoston MP21ZP mini plug with power meter.

### CODE REVIEW

**Comment by gazpachoking** [comment]
Can anyone point me to the docs about semantic PR titles? I thought I fixed mine, but the check is failing. The description says I can ask the bot... but I can't find any instructions on how to do that.

**Comment by AlCalzone** [comment]
@zwave-js-bot rename commit

**Comment by AlCalzone** [comment]
> Can anyone point me to the docs about semantic PR titles? I thought I fixed mine

You did, but the original commit still has the uppercase `A`. Github has this stupid "feature" where squash-merging a single-commit PR takes the commit message as the title, but squash-merging a multi-commit PR takes the PR title (as expected).

**Review by AlCalzone — APPROVED** [review]

**Comment by gazpachoking** [comment]
@AlCalzone Thanks!

**Pull request merged**
