### PR TITLE
feat: configure logging through driver options

### LINKED ISSUE #1062: Configure logging through driver options
Ideally, this should have preference over env variables. Things to consider:

- [ ] minimum loglevel (currently `LOGLEVEL` env variable) 
- [ ] ability to turn logging off (loglevel: off), should also be supported through the `LOGLEVEL` env variable
- [ ] ability to provide a custom transport for logs (compatible with `winston`)
- [ ] change the logfile location

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #1062

### CODE REVIEW

**Comment by robertsLando** [comment]
@AlCalzone What about this?

**Comment by AlCalzone** [comment]
This seems to be going in the right direction. You are not using `setupLogger()` yet, are you? 

I'm thinking if we have to refactor the whole logger stuff to be set up per driver instance. Or the driver could create the base logger instance. All locations with driver access could access it via the driver instance. And we could pass it to all locations without driver access (e.g. serialport).
This way we could run multiple drivers (networks) at once with each driver logging into its own file.

Maybe something for a different PR though.

**Comment by robertsLando** [comment]
> This seems to be going in the right direction. You are not using setupLogger() yet, are you?

Nope I still have to use it in the code, It should be called in driver constructor and logConfig can be an option of Driver options

> I'm thinking if we have to refactor the whole logger stuff to be set up per driver instance. This way we could run multiple drivers (networks) at once with each driver logging into its own file.

I think it's a very good idea but thet needs a complete different approach and a big refactor, could go on with this for now and keep that for 6.0.0 version?

**Comment by robertsLando** [comment]
@AlCalzone I don't understand the lint issues. I have also run `eslint --fix` but it still report lint issues :man_shrugging:

**Comment by AlCalzone** [comment]
I'll check it. Maybe you need to "npm ci" locally, seems like my release fixes also updated Prettier.

**Review by AlCalzone — APPROVED** [review]
I've renamed a few methods and updated the documentation a bit. However, this change is breaking since the environment variables are no longer evaluated lazily, but rather when the module is imported.
At least https://github.com/AlCalzone/ioBroker.zwave2 was relying on this behavior.

**Comment by robertsLando** [comment]
Didn't thought about that, I think there is no way to implement this without that breaking, the only one would be to create a Zwave logger instance for each driver like you suggested

**Comment by AlCalzone** [comment]
merged manually

**Pull request closed without merging**
