### PR TITLE
fix: always use S2 for endpoint communication if node uses S2

### LINKED ISSUE #5302: Unable to get Ring Retrofit device working properly
Hi 
Is this something you can help me with?

Can't get it to work.

https://products.z-wavealliance.org/products/3696?selectedFrequencyId=-1

### PR DESCRIPTION
**Pull request by AlCalzone**
This PR does what https://github.com/zwave-js/node-zwave-js/pull/5310 failed to do.

fixes: https://github.com/zwave-js/node-zwave-js/issues/5302

### CODE REVIEW

**Comment by webmogul1** [comment]
Look at my smiley face: 😃 
Can't wait to try it.

**Comment by AlCalzone** [comment]
This time I'm pretty certain it works - I simulated a fake node with behavior similar to yours.

**Comment by AlCalzone** [comment]
@zwave-js-bot approve

**Comment by webmogul1** [comment]
Wonderful! I will try it as soon as robertsLando realeases a new ZUI verrsion.

**Comment by webmogul1** [comment]
It works!!!
Ring Retrofit is working now! 

image

**Pull request merged**
