### PR TITLE
fix(config): update Dome Wireless Siren

### PR DESCRIPTION
**Pull request by rmcginty**
Fixed some case inconsistencies and added options for strobe per device documentation.  Tested on the unit I have and it does indeed change whether the LED ring flashes or not.

### CODE REVIEW

**Review by AlCalzone — APPROVED** [review]
OK with my changes

**Comment by rmcginty** [comment]
> OK with my changes

Nice! I didn't know about templates. I'll remember that for the future. Thanks!

**Comment by AlCalzone** [comment]
If you want to read a bit: https://zwave-js.github.io/node-zwave-js/#/config-files/using-templates

**Comment by rmcginty** [comment]
> If you want to read a bit: https://zwave-js.github.io/node-zwave-js/#/config-files/using-templates

Awesome! Definitely will read up on it.

**Pull request merged**
