### PR TITLE
fix: treat V1 Alarm frames as simple report with two values

### LINKED ISSUE #1546: First Alert ZCOMBO v1 alarm notifications are unsupported
**Describe the bug**

Alarm notifications from a First Alert ZCOMBO are unsupported.

```
17:16:12.130 SERIAL « 0x010d00a800010a0471050c0000cbe6                                    (15 bytes)
17:16:12.132 SERIAL » [ACK]                                                                   (0x06)
17:16:12.133 DRIVER « [Node 010] [REQ] [BridgeApplicationCommand]
                      └─[NotificationCCReport]
                          V1 alarm type:  12
                          V1 alarm level: 0
17:16:12.137 CNTRLR « [Node 010] received unsupported notification {
                          "nodeId": 10,
                          "ccId": "Notification",
                          "ccCommand": "0x05",
                          "alarmType": 12,
                          "alarmLevel": 0
                      }
```

**Device information**

Which device(s) is/are affected (make/model)?  [First Alert ZCOMBO](https://products.z-wavealliance.org/products/862?selectedFrequencyId=2)
What are the node IDs? 10

**Last Known Working Configuration**
- [ ] New device
- [ ] Previously working device (node-zwave-js)
    - Which library version/docker image/adapter version?
    - Have you made any recent configuration changes to the device? Describe.

- [X] Previously working device (other platform)
    - Which platform? OZW
    - Have you made any recent configuration changes to the device? Describe. No.
    
**Installation information**
How did you install `node-zwave-js`?
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [X] Manual Docker build
    - `node-zwave-js` branch: b1b4f74ef95da72f87e68b474e513867d7e33c68
    - `zwavejs2mqtt` branch: v1.0.1
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**
1. Hold down the test button on the alarm
2. Watch in the node-zwave-js logs that the alarm is unsupported
3. Notice that zwavejs2mqtt shows no events or value updates in the debug trace except for battery

**Additional context**
As in this [comment](https://github.com/zwave-js/node-zwave-js/issues/1466#issuecomment-769408525), the only values I see are for battery levels. I see "unsupported notification" error in the logs.

**Logfile:** [zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/5901341/zwavejs_1.log)
**Cache files:** [cache.zip](https://github.com/zwave-js/node-zwave-js/files/5901342/cache.zip)

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #1546

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this
@kpine can you test this? Your reports should now result in two values.

**Comment by ragenhe** [comment]
@AlCalzone 

Since I have this hardware I will see if I can test with a custom docker image.

Fingers crossed, I can pull it off this time, LOL.

**Comment by ragenhe** [comment]
I don't remember seeing this before, I am seeing the following in my MQTT broker.
zwave/nodeID_22/notification/endpoint_0/alarmType - value 13
zwave/nodeID_22/notification/endpoint_0/alarmLevel - value 255

Other stuff as well from the broker.

Screen Shot 2021-02-02 at 2 15 18 PM

I don't see any new "notification" sensors in HA, even after restarting HA, for this node.

**Comment by AlCalzone** [comment]
HA probably needs to understand these first. But it looks like it worked.

**Comment by kpine** [comment]
I can test tomorrow if you need another one, but the alarmLevel/Type values are what I'd expect. I missed my window of opportunity today and the family is asleep now. I don't think they'd appreciate me waking up the alarm. 😬

**Comment by kpine** [comment]
LGTM 👍

**Pull request merged**
