### PR TITLE
feat(config): add fingerprint for Aeotec ZWA024-C (Multisensor 7 EU version)

### PR DESCRIPTION
**Pull request by altrnate32**
My Aeotec Multisensor 7 EU Version (zwa024-c) is not recognized. Fingerprint is: 0x0371-0x0002-0x0018
I added this fingerprint to the zwa024.json, re-included. But still not recognized.
Tried creating custom config file restart, re-include -> did not work
Tried rebuilding docker container from own sources, launch container, re-include -> did not work.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Did you follow this guide? https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files
If yes, what do the logs show on startup?

**Comment by altrnate32** [comment]
Yes I created zwa024.json and put it in root/config, and to make sure also in root/store/config.
With root I mean the folder used as 'app root'. And it is also included in my docker image. On startup there is no reference to these files in the logs (debug level). Does this mean it is not working?
This is the interview:

[log.txt](https://github.com/zwave-js/node-zwave-js/files/7838756/log.txt)

**Comment by AlCalzone** [comment]
You're looking at the wrong log files. This information is included in the [driver logs](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs)

Also, don't do that:

> put it in root/config

**Comment by altrnate32** [comment]
> You're looking at the wrong log files. This information is included in the [driver logs](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs)
> 
> Also, don't do that:
> 
> > put it in root/config

Thank you for pointing me in the right direction. with root/config I mean <app-root-folder/store>/config The custom file did not work due to templates missing. It works now and the values are picked up correctly. The pull request will add the compatibility for EU version.

**Review by AlCalzone — DISMISSED** [review]

**Comment by AlCalzone** [comment]
@zwave-js-bot rename commit

**Review by AlCalzone — APPROVED** [review]

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
