### PR TITLE
chore(config): remove redundant leading comments from config files

### PR DESCRIPTION
**Pull request by AlCalzone**
I've wanted to do this for a while. Now that we can use `comment-json` to automatically edit these files, things are a lot easier.

### CODE REVIEW

**Comment by blhoward2** [comment]
I kind of like the leading comments for human readability when you’re flipping between files, but obviously if you want them gone...

**Comment by AlCalzone** [comment]
I found them to be inconsistent sometimes, especially when new external contributors are involved.

**Comment by blhoward2** [comment]
Eh. Lint could just as easily compare them to the fields and rewrite them, but I don't feel that strongly.

**Review by blhoward2 — APPROVED** [review]
LGTM

**Pull request merged**
