### PR TITLE
fix(config): force Wake Up as supported for Aeon Labs Minimote

### LINKED ISSUE #1536: Aeon Labs Minimote appears as dead after network restart, despite being a battery device
**Describe the bug**

After I include the Minimote, it is found and the status is Asleep. When I restart zwavejs2mqtt, the node is detected as Dead, and all the device information is blank (not reloaded from cache). Once I click on a button on a remote, it completes the interview process and keeps it in the Alive status, never going Asleep, as if it were a mains-powered device. The device information is filled back in.

The device was included while on battery power.

**Device information**

Which device(s) is/are affected (make/model)?  Aeon Labs Minimote
What are the node IDs? Node 008

**Last Known Working Configuration**
- [ ] New device
- [ ] Previously working device (node-zwave-js)
    - Which library version/docker image/adapter version?
    - Have you made any recent configuration changes to the device? Describe.

- [X] Previously working device (other platform)
    - Which platform? OZW
    - Have you made any recent configuration changes to the device? Describe. No.
    
**Installation information**
How did you install `node-zwave-js`?
- [ ] `zwavejs2mqtt` (latest) docker image
- [X] `zwavejs2mqtt` (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**
1. Start inclusion process
2. Include Minimote
3. Notice everything looks ok
4. Restart zwavejs2mqtt
5. Notice the device details (mfg, product) are blank, and the device status is Dead
6. Press a button, device details appear and the device is marked incorrectly as Alive (should be asleep eventually).

**Additional context**

As discussed in the HA discord, this problem occurs because the device does not advertise the Wake Up CC during the interview, despite supporting it. I noticed the OZW device config file has several workarounds, including manually advertising the Wake Up CC, which is probably why I never noticed a problem there. Those are missing from the zwave-js config file.

After restarting the network, I noticed that if the very first thing I do is manually wake up the device (hold down the learn button for a few seconds), then zwave-js will decide to add the Wake Up CC to the node's list of CCs. Because of this, the attached cache file contains it. From this point on, restarting zwavejs2mqtt works fine and the device functions as expected (RestartFromCache, Asleep). If I send the wake up notification after pressing a button (thus finished the interview), the Wake Up CC will never be added.

Perhaps overriding the command classes in the config like OZW would be a good idea, to force zwave-js to think it supports the wake up CC during the inclusion. This would make a better experience. See [config file](https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/dsa03202.xml).

**Logfile:** [zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/5897185/zwavejs_1.log)
**Cache files:** [logs.zip](https://github.com/zwave-js/node-zwave-js/files/5897186/logs.zip)

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #1536

### CODE REVIEW

**Comment by AlCalzone** [comment]
@kpine did you have a chance to verify if this works?

**Comment by kpine** [comment]
Sorry, not yet. Need to figure out how to get the file into zwavejs2mqtt docker image and reload it, haven't had a chance yet.

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

**Comment by AlCalzone** [comment]
@kpine you can either build a [custom image](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds) with this branch - or if you prefer the Node.js way, install zwave-js using the command the bot is going to post in a minute.

**Comment by kpine** [comment]
Great, I'll give it a try today.

**Comment by kpine** [comment]
I think it looks good. I ended up just downloading the file into the container, replacing it in the two locations I found the existing file, and restarted the container. Then I excluded the node, restarted zwavejs2mqtt (not necessary), then added the node. I checked the cache and the wake up class was set. I restarted zwavejs2mqtt and in the UI the node kept all its information, never went dead, and has stayed Asleep. Interview considered it asleep instead of dead. Attached is the inclusion/restart log for completion. Thanks!

[zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/5900236/zwavejs_1.log)

**Comment by AlCalzone** [comment]
While you're at it, could you also check https://github.com/zwave-js/node-zwave-js/pull/1544 as an alternative broader solution?

**Comment by kpine** [comment]
Sure, I can do that.

**Comment by AlCalzone** [comment]
Following the discussion in https://github.com/zwave-js/node-zwave-js/discussions/1537, I'm going to modify #1544 in a way that it won't help you without this PR.

**Comment by kpine** [comment]
So how would I test both of these? Build an image with the other PR and copy this file into it? Or can you rebase this on the other PR?

**Comment by AlCalzone** [comment]
I meant there's no need - thanks anyways.

**Pull request merged**
