### PR TITLE
fix(config): change scenes sent config, ... - fibaro walli dimmer

### PR DESCRIPTION
**Pull request by Micka41**
Add First button: send scenes, Second button: send scenes, On/Off mode parameters, units, ...

### CODE REVIEW

**Comment by Micka41** [comment]
Hello, 
What's wrong this time?

**Comment by AlCalzone** [comment]
@Mergifyio update

**Review by blhoward2 — CHANGES_REQUESTED** [review]
Please take a look at my comment on the other one. Please update the remainder of the file according to our style guide. We appreciate you helping to clean up the file during your update.

**Comment by AlCalzone** [comment]
#3100 was just merged, so I've gone ahead and updated your file to match the new config format. As you'll see, paramInformation is now an array of objects.

I did not touch anything else, so please update the file according to the review comments

**Comment by AlCalzone** [comment]
@Micka41 are you planning to finish this?

**Pull request closed without merging**
