### PR TITLE
feat(config): add associations for Aeotec ZW130 Wallmote Quad

### PR DESCRIPTION
**Pull request by larstobi**
https://products.z-wavealliance.org/products/2153/assoc?noFilename=True

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Labels are a bit verbose.
Something like "Button 1: Basic Set" etc. would be better.

**Comment by blhoward2** [comment]
We've been doing these as "Button 2 (Basic Set)" and "Button 2 (Multilevel)" if memory serves.

**Comment by blhoward2** [comment]
Also, I'm planning to template the Aeotec ones some tomorrow so please try to fix this so @AlCalzone can merge it ASAP. Otherwise it's going to create a conflict.

**Comment by blhoward2** [comment]
I've merged this into my upstream work, so I'm going to close it here and it'll merge with my template push.

**Comment by larstobi** [comment]
Sounds good, @blhoward2 ! Looking forward to it. I've received an explanation from Aeotec support saying that the sliding function for the WallMote Quad only works when using direct associations. Groups 3,5,7,9 control the respective assigned device.

**Comment by larstobi** [comment]
@blhoward2 What's the status here ? Maybe we could just merge this, and you could fix the conflict in your code? It shouldn't be too much of a conflict, though, should it?

**Comment by AlCalzone** [comment]
Last time I talked to @blhoward2 he said that he wants to get Aeotec done over the weekend.

**Pull request closed without merging**
