### PR TITLE
Update for correct name of button and switch

### PR DESCRIPTION
**Pull request by pepsonEL**
0	Mono-stable input (button)
1	Bi-stable input (switch)

### CODE REVIEW

**Comment by pepsonEL** [comment]
Why this can not be merged ?

**Comment by AlCalzone** [comment]
I don't have time to review all config file changes if they match the style guide. I've asked @blhoward2 to take a look, but he has a life too :)

**Comment by pepsonEL** [comment]
But it is name type from manual Fibaro.

**Comment by AlCalzone** [comment]
The texts and descriptions manufacturer manuals are often not good and every manufacturer calls things differently, so we often use different labels to be consistent.

**Comment by blhoward2** [comment]
Yes, and actually we're not going to merge this. We're aiming for consistency across devices and the labels you're replacing are what we generally use. We want human readable labels. "Mono-stable input" is not very user friendly. 

We very much welcome suggestions for improvements to the files, but this isn't an improvement just because it matches the manual.

**Pull request closed without merging**
