### PR TITLE
fix(config): swap product type and id for ZEN30

### PR DESCRIPTION
**Pull request by aneisch**

### CODE REVIEW

**Comment by AlCalzone** [comment]
@blhoward2 any objections?

**Review by AlCalzone — APPROVED** [review]
assuming blhoward2 is okay with this

**Comment by blhoward2** [comment]
Does this match ozw? We haven't touched those yet so I don't know how zwa has them, if at all.

**Comment by aneisch** [comment]
> Does this match ozw? We haven't touched those yet so I don't know how zwa has them, if at all.

Yes, matches OZW. https://github.com/OpenZWave/open-zwave/blob/master/config/zooz/zen30.xml#L38

Unfortunately I overlooked this mistake in my initial ZEN30 conversion.

**Comment by AlCalzone** [comment]
What, they have `manufacturerId:productId:productType` in their files? Or was that a mistake in the xml?
If it is that way round, we might have a couple of other files with that error.

**Comment by aneisch** [comment]
> What, they have `manufacturerId:productId:productType` in their files? Or was that a mistake in the xml?
> If it is that way round, we might have a couple of other files with that error.

If you use the line `<MetaDataItem name="OzwInfoPage">http://www.openzwave.com/device-database/027a:a008:a000</MetaDataItem>` it is `manufacturerId:productId:productType`, yes.

**Comment by blhoward2** [comment]
You really shouldn't pull the device info from that line as it is non-operative. Their index lives in manufacturer_specific.xml.

**Comment by aneisch** [comment]
> You really shouldn't pull the device info from that line as it is non-operative. Their index lives in manufacturer_specific.xml.

That's great to know, thank you. I will reference that for future contributions.

**Comment by blhoward2** [comment]
Most of the Zooz devices only have one set of type/id but you may check that you didn't miss any. In the index they'll often have multiple sets of values pointing to one device file, but the device file only has the metadata for one of them.

**Comment by AlCalzone** [comment]
> Their index lives in manufacturer_specific.xml

Yeah, right... our import script respects that.

**Review by blhoward2 — APPROVED** [review]

**Pull request merged**
