### PR TITLE
fix(config): add 700 series variant of SimonTech Roller Blind

### PR DESCRIPTION
**Pull request by davidcalleja**
I have new Roller Blind in my home and his signature is `x0267-0x0102-0x0000`

### CODE REVIEW

**Comment by AlCalzone** [comment]
I assume you have confirmed that the config parameters are the same for your device?
This ID looks so different from the others, it may be an entirely new hardware revision.

**Comment by davidcalleja** [comment]
Yes, is a bit weird but... is same device with same instructions... but this one have `z-wave 2` I have tried to test it in my zwave-js-ui (I have it in docker) but is not working, do you know exactly how to test if it works?

Z-Wave JS UI display diferences

Screenshot 2023-05-04 at 18 21 10

Instructions of new device are this

**Comment by AlCalzone** [comment]
Ok looks like a new 700 series version. I'll double check later and merge. Thanks!

**Comment by AlCalzone** [comment]
The changes were significant enough (including differences in config parameters) that I decided to move this to a new file.

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
