### PR TITLE
fix(config): remove unnecessary endpoint functionality for CT101

### LINKED ISSUE #6017: CT101 Thermostat Showing as two climate entities, and no fan
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within Z-Wave JS UI (formerly ZwaveJS2MQTT)?

NO, my problem is NOT within Z-Wave JS UI

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

See attached Bug from the following Home Assistant Issue: https://github.com/home-assistant/core/issues/48452

### Device information

Manufacturer:  Radio Thermostat of America
Model name:  CT101
Node ID in your network: 3

### How are you using `node-zwave-js`?

- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (latest)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker image (dev)
- [ ] `zwave-js-ui` (formerly `zwavejs2mqtt`) Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: stable
`zwave-js-ui` branch: stable

### Did you change anything?

no

### If yes, what did you change?

_No response_

### Did this work before?

Don't know, this is a new device

### If yes, where did it work?

_No response_

### Attach Driver Logfile

See attached Bug from the following Home Assistant Issue: https://github.com/home-assistant/core/issues/48452

If more are required other than this already filed issue, I can gather if needed. First time filing, so I can definitely gather if required.

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: https://github.com/zwave-js/node-zwave-js/issues/6017

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot automerge

**Comment by txwindsurfer** [comment]
In moving my CT101 thermostat from the official Zwave-JS to Zwave-JS-UI the issue of 2 climate entities reappeared.  Will the fix applied in #6146 be applied to Zwave-JS-UI?  Also, this fix needs to be applied to CT100 thermostats #6184

**Comment by AlCalzone** [comment]
This was released in v11.10.1. As of now, the Z-Wave JS UI addon does not include that version yet.
https://zwave-js.github.io/which-version/

> Z-Wave JS UI (HA Addon)
> 
> Latest version:
>     v1.15.5
> Z-Wave JS UI version:
>     v8.22.3
> Driver version:
>     v11.9.2

**Comment by txwindsurfer** [comment]
@AlCalzone Thanks so much for fixing the long-time issues on CT101 and CT100 thermostats.  Everything is great until I upgrade Z-Wave JS UI to a new release (which seems to happen frequently) and the extra attributes reappear (see image) with the thermostat revert to the old state.  I can re-interview each thermostat and the extra attributes disappear; however, I have to manually reinterview each one.  I have deleted a thermostat and reinstalled it as a new node but this doesn't fix the reversion problem.  Also, deleting the unavailable entities after re-interview doesn't help as they just reappear with the next Z-Wave JS UI update.  If I can be of any assistance, please let me know!

**After upgrading Z-Wave JS UI to v9.2.2:**
image

**After re-interview:**
image

**Comment by AlCalzone** [comment]
Since you are using Z-Wave JS UI, we can do a little digging:

Please enable logging to file and set the loglevel to debug in the Z-Wave section of the settings, then save:
grafik

The info icon in the top right corner shows your home ID as a hexadecimal string (0-9, a-f). In the Store tab, you should find 3 files with the same string in their name (not the .lock folders though), e.g.:
grafik

Please do a re-interview, then wait a minute or 2 to make sure the data has been saved, then download the 3 files and save them somewhere. Also download the current log with the re-interview in it. Remember when you did this (date and time).

When you notice the entities are back, download the 3 files again, plus any logs that you still have between the re-interview and now. Remember when you did this (date and time).

Send me everything, ideally via e-mail or on Discord - you'll find me on the HA and [Z-Wave JS](https://discord.gg/HFqcyFNfWd) servers.

**Pull request merged**
