### PR TITLE
feat(config): add MCO Home Technology Co. LTD MH-DS221

### PR DESCRIPTION
**Pull request by itzniru**
Added configuration file for MCO Home Technology Co., LTD MH-DS221 Micro Switch, my first file and my first pull request ever. :)

### CODE REVIEW

**Comment by AlCalzone** [comment]
Not sure what you did there, but you should really make PRs from branches, not the master branch :)

**Comment by itzniru** [comment]
Ohh fuck. Im sorry, was up all night installing VScode to fix the
formatting issues in my config, I probably should have slept before i tried
to push it from my pc.  Im really sorry about that!

But i do appriciate that you let me know. I might have to get a new account
now.

Hope i didnt mess stuff up for u.



Den fre 30 sep. 2022 08:43AlCalzone ***@***.***> skrev:

**Comment by AlCalzone** [comment]
> I might have to get a new account

No, just make a new branch in git, do your changes there and create a new PR.

**Comment by itzniru** [comment]
Thanks yeah Ill do that, was kidding about the account part, meant its just
so embarassing that i should get a new one.  :) Yeah,  i will read and look
it up some more. :) I wanted to help out and not make it worse for u guys
lol





Den fre 30 sep. 2022 09:00AlCalzone ***@***.***> skrev:

**Comment by AlCalzone** [comment]
All good, you can't mess up stuff for us.

**Comment by itzniru** [comment]
Glad to hear it. Then its only my dignity and that was long gone already. :)

Den fre 30 sep. 2022 09:19AlCalzone ***@***.***> skrev:

**Comment by itzniru** [comment]
So should i just open an new pull request to to add the file? Since now it should be ok formatting.

**Comment by AlCalzone** [comment]
Yep

**Pull request closed without merging**
