### PR TITLE
Implement Scene Activation CC

### LINKED ISSUE #516: The command class Scene Activation is not implemented
The full message is `Dropping message because it could not be deserialized: The command class Scene Activation is not implemented`.

The item is a Nodon Wallswitch CWS-3-1-00

Is there any possibility that `Scene Activation`will be supported in the foreseeable future?

### PR DESCRIPTION
**Pull request by AlCalzone**
Fixes: #516

### CODE REVIEW

**Comment by CliffS** [comment]
I'm clearly missing something.  On your current `master` branch, if I click the switch, I get the following log:

```
17:32:32.867 DRIVER   handling application command request Scene Activation (0x2b) for node 14
17:32:32.869 CNTRLR « [Node 014] TODO: no handler for application command {
                          "nodeId": 14,
                          "ccId": "Scene Activation",
                          "ccCommand": "0x01",
                          "payload": "0x1e00"
                      }
```
I do not get an event on the node and I cannot tell which scene was activated.

Actually, I've just realised that the high byte of the `payload` is the information that should be passed back and matches the test at https://github.com/AlCalzone/node-zwave-js/issues/516.

**Comment by CliffS** [comment]
If it helps, the `command` received by `handleCommand()` is an instance of `SceneActivationCCSet`.

**Comment by AlCalzone** [comment]
You should get a `value updated` event for the value ID
```
{
    commandClass: CommandClasses["Scene Activation"],
    property: "sceneId",
    endpoint: <depends>
}
```

**Comment by AlCalzone** [comment]
Oh... yeah I forgot something: 2f10699
You should now get the events.

**Comment by CliffS** [comment]
I'm still seeing `TODO: no handler for application command`

```
16:56:19.754 SERIAL « 0x010a0004000e042b010a00db                                          (12 bytes)
16:56:19.760 DRIVER   handling application command request Scene Activation (0x2b) for node 14
16:56:19.762 CNTRLR   [Node 014] command is a SceneActivationCCSet
16:56:19.756 SERIAL   Buffer := 0x010a0004000e042b010a00db                                (12 bytes)
16:56:19.759 SERIAL » [ACK]                                                                   (0x06)
16:56:19.766 SERIAL   The receive buffer is empty, waiting for the next chunk...
16:56:19.764 CNTRLR « [Node 014] TODO: no handler for application command {
                          "nodeId": 14,
                          "ccId": "Scene Activation",
                          "ccCommand": "0x01",
                          "payload": "0x0a00"
                      }
16:56:20.902 SERIAL « 0x01080004000e0284077c                                              (10 bytes)
16:56:20.908 DRIVER   handling application command request Wake Up (0x84) for node 14
16:56:20.909 CNTRLR « [Node 014] received wakeup notification
16:56:20.903 SERIAL   Buffer := 0x01080004000e0284077c                                    (10 bytes)
16:56:20.906 SERIAL » [ACK]                                                                   (0x06)
16:56:20.917 SERIAL   The receive buffer is empty, waiting for the next chunk...
16:56:20.919 DRIVER   The remaining 5 messages are for sleeping nodes, not sending anything!
16:56:20.914 CNTRLR   [Node 014] The node is now awake.
16:56:30.926 DRIVER   The awake timeout for node 14 has elapsed. Assuming it is asleep.
16:56:30.930 CNTRLR   [Node 014] The node is now asleep.
```

**Comment by CliffS** [comment]
I now get two events for each press.  `sceneId` and `dimmingDuration`.

For a long press, I get two `sceneId` events (as expected) and two `dimmingDuration` events.  However the result is always zero seconds as below:

```javascript
Node 14 value updated {
  commandClassName: 'Scene Activation',
  commandClass: 43,
  endpoint: 0,
  property: 'dimmingDuration',
  newValue: Duration { unit: 'seconds', _value: 0 },
  prevValue: Duration { unit: 'seconds', _value: 0 },
  propertyName: 'dimmingDuration'
}
```

I don't think it matters though.  I don't particularly need the duration from the `Node`.

**Comment by AlCalzone** [comment]
> However the result is always zero seconds as below

That means the target values of the scene are intended to be reached immediately. The 2nd byte of the payload above is 0, so I guess the remote does not send different durations.

**Comment by CliffS** [comment]
Great.  So we ca call this fixed. Thanks again.

**Pull request merged**
