### PR TITLE
feat(config): add support for Weiser SmartCode 5

### PR DESCRIPTION
**Pull request by mw-white**
Added a config for the Weiser SmartCode 5 Lever Lock:  https://products.z-wavealliance.org/products/2378

Very similar to the existing Weiser and Kwikset configs.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Do you know by any chance if that's an OEM for Kwikset? We avoid cross-importing from other manufacturers unless this is the case. Granted, here it seems suspiciously similar, so it might aswell be.

**Comment by mw-white** [comment]
I suspect that it is - they all seem to fall under the same manufacturer ID.  I believe the Weiser lock is just a rebranded Kwikset 912 (one of the codes for the quickset is productType 0x0003, Id 0x0339 and the Weiser is 0x0001, 0x0339.

Would it make more sense to add this as another device in the 912 entry?

**Comment by AlCalzone** [comment]
> Would it make more sense to add this as another device in the 912 entry?

No, it's fine here - otherwise its going to confuse users.

**Comment by AlCalzone** [comment]
@zwave-js-bot rename commit

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
