### PR TITLE
docs: add link to the Z-Wave JS UI health check documentation

### PR DESCRIPTION
**Pull request by matejdro**
As per https://github.com/zwave-js/zwave-js-ui/discussions/2675#discussioncomment-3714547, extra link makes it easier to find the UI that network healt mentions.

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
That link doesn't seem complete (it's relative to this documentation)

**Comment by matejdro** [comment]
Hm, how should it be instead?

**Comment by AlCalzone** [comment]
The full URL instead of the relative path.

**Comment by matejdro** [comment]
Changed to full URL

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
Thanks!

**Pull request merged**
