### PR TITLE
feat: support OTW firmware updates for 500 series

### PR DESCRIPTION
**Pull request by AlCalzone**
After adding support for 700 series we now have support for 500 series too.

⚠️ WARNING: It is of utmost importance to select the correct firmware file to upload for these sticks. I bricked an UZB3 during testing without a chance to bring it back.

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot approve

**Comment by Hedda** [comment]
> ⚠️ WARNING: It is of utmost importance to select the correct firmware file to upload for these sticks. I bricked an UZB3 during testing **without a chance to bring it back.**

@AlCalzone FYI, while relatively complicated it is possible for a user to unbrick a bricked Z-Wave controller, but not via USB, as the user will first need to get a JTAG/SWD flasher (either build a DIY flasher using GPIO on Raspberry Pi or buy J-Link Debug Probe) and then connect wires from it to the correct solder-pads/pins on the circuit board to be able to flash the firmware via using either programming application from Silicon Labs or other.

**Comment by AlCalzone** [comment]
Okay, tiny chance to bring it back 😇
I didn't feel like breaking mine open since I had two spares.

**Comment by Hedda** [comment]
SWD interface will be needed for new Silicon Labs Z-Wave/Zigbee/Thread chips and after (for bricked) to do a full chip/flash erase:

https://community.silabs.com/s/article/z-wave-500-recovering-uzb3-controller-stick?language=en_US 
https://www.silabs.com/documents/public/application-notes/AN136-production-programming-options.pdf
https://www.silabs.com/documents/public/application-notes/an1303-efr32-dci-swd-programming.pdf
https://www.silabs.com/documents/public/application-notes/an958-mcu-stk-wstk-guide.pdf

Should be able to use cheap SWD debug probe that supports the SWD protocol, like example original ST-Link V2 (or its clones), just do a search on google for "J-Link Debug Probe", "ST-LINK V2", or "JTAG/SWD Debugger Programmer", The are of course also many clones of J-Link debugger (and ST-Link V2 clones) available which may be or may not work with Silabs Simplicity Studio so you will need to use some open-source or third-party JTAG/SWD programmer software to flash it (such as OpenOCD or PyOCD which both has cross-platform support). 

https://wiki.segger.com/SWD
https://openocd.org/
https://pyocd.io/

Not tested OpenOCD with Silicon Labs but here is an old example:

https://github.com/nopeppermint/openocd_efm32
https://github.com/nopeppermint/OpenOCD_EmBlocks_with_EFM32WG_STK3800

Cheapest debugger might be the "DapCat Programmer" (or is it "Dap Cat Programmer") but not sure if it really is compatible(?):

https://electroniccats.com/store/dapcat/
https://github.com/ElectronicCats/DAP-Cat-Programmer

Note! Silicon Labs Simplicity Studio and the official Silicon Labs Flasher Programmer do not support all third-party SWD debug probe solutions, and for that, you might need to use a real (none-clone) J-Link Debug Probes by SEGGER which is the trusted industry standard that Silicon Labs have tested and approved, and while it is a more expensive option the simplest/easiest option for a tinkerer and hobbyists is just to invest in SEGGER's "J-Link EDU" model (or their little more limited "J-Link EDU Mini" model) is their least expensive models, however, due to chip shortages it looks like those "J-Link EDU" variants are out-of-stock in most places, and unfortunately all other J-Link JTAG/SWD Debug Probes by SEGGER are very expensive as they are only targeting professionals, 

https://www.segger.com/products/debug-probes/j-link/models/j-link-edu/
https://www.segger.com/products/debug-probes/j-link/models/j-link-edu-mini/
https://www.segger.com/products/debug-probes/j-link/models/model-overview/

For the full-on DIY approach here are some related articles about using a Raspberry Pi as a JTAG/SWD flasher or OpenOCD:
https://fabacademy.org/2020/labs/ulb/students/quentin-bolsee/projects/raspi_openocd/
https://codensolder.com/blog/rip-swd-programmer
https://www.pcbway.com/blog/technology/OpenOCD_on_Raspberry_Pi__Better_with_SWD_on_SPI.html
https://learn.adafruit.com/programming-microcontrollers-using-openocd-on-raspberry-pi

PS: While probably unlikely, depending on which exact chip and circuit board design of your ur Z-Wavecontroller and if the manufacturer has flashed a bootloader firmware to the Z-Wave controller then if you are lucky it might even be possible to recover from a bricked Z-Wave controller by forcing recovery mode by short-circuit the right pins/pads on the circuit board (with a jump cable) which activate the bootloader and then you are able to flash it via USB. However, then you will need to research that further to figure out which pads/pins to short-circuit and when.

**Pull request merged**
