### PR TITLE
feat(config): add HeatIt Z-TRM3

### PR DESCRIPTION
**Pull request by AlCalzone**
Operation mode and setpoint were commented out by the user who sent me this. I think it makes sense since that should be set through Thermostat Setpoint CC. Thoughts?

### CODE REVIEW

**Comment by robertsLando** [comment]
I saw same configuration also in heatit033 for cold setpoint, sincerly I dunno why them are also present in config vars but as you said there is no reason for this since it supports dedicated CC for them

**Review by robertsLando — DISMISSED** [review]

**Comment by roflmao** [comment]
@AlCalzone seems i lost some sensors with these changes (ex air temperature).

What do you need from me?

**Comment by AlCalzone** [comment]
> seems i lost some sensors with these changes (ex air temperature).

That shouldn't be related. Open a new issue please and provide the information requested in the issue template.

**Comment by roflmao** [comment]
@AlCalzone I got the air temperature sensors after all.

**Comment by robertsLando** [comment]
> seems i lost some sensors with these changes (ex air temperature).

Do you mean you don't see them in control panel?

**Comment by roflmao** [comment]
@robertsLando Yes, but i can see the sensors getting reported in the logs:
```
 2020-12-01T07:20:02.612Z z2m:Zwave Node 3: metadata updated: 49-2-Air temperature                                                                                                                                                                            
 2020-12-01T07:20:02.612Z z2m:Zwave Node 3: value updated: 49-2-Air temperature 25.1 => 25.1                                                                                                                                                                  
 2020-12-01T07:20:02.728Z z2m:Zwave Node 3: metadata updated: 49-3-Air temperature                                                                                                                                                                            
 2020-12-01T07:20:02.729Z z2m:Zwave Node 3: value updated: 49-3-Air temperature 0 => 0                                                                                                                                                                        
 2020-12-01T07:20:02.929Z z2m:Zwave Node 3: metadata updated: 49-4-Air temperature                                                                                                                                                                            
 2020-12-01T07:20:02.930Z z2m:Zwave Node 3: value updated: 49-4-Air temperature 20 => 20                                                                                                                                                                      
 2020-12-01T07:21:02.063Z z2m:Zwave Node 3: metadata updated: 49-2-Air temperature                                                                                                                                                                            
 2020-12-01T07:21:02.064Z z2m:Zwave Node 3: value updated: 49-2-Air temperature 25.1 => 25.1                                                                                                                                                                  
 2020-12-01T07:21:02.227Z z2m:Zwave Node 3: metadata updated: 49-3-Air temperature                                                                                                                                                                            
 2020-12-01T07:21:02.227Z z2m:Zwave Node 3: value updated: 49-3-Air temperature 0 => 0                                                                                                                                                                        
 2020-12-01T07:21:02.436Z z2m:Zwave Node 3: metadata updated: 49-4-Air temperature                                                                                                                                                                            
 2020-12-01T07:21:02.437Z z2m:Zwave Node 3: value updated: 49-4-Air temperature 20 => 20                                                                                                                                                                      
 2020-12-01T07:21:32.379Z z2m:Zwave Node 3: value updated: 50-1-value-65537 535.8 => 535.8                                                                                                                                                                    
 2020-12-01T07:21:32.379Z z2m:Zwave Node 3: value updated: 50-1-deltaTime-65537 0 => 0                                                                                                                                                                        
 2020-12-01T07:21:32.579Z z2m:Zwave Node 3: value updated: 50-1-value-66049 0.1 => 0.2                                                                                                                                                                        
 2020-12-01T07:21:32.579Z z2m:Zwave Node 3: value updated: 50-1-deltaTime-66049 0 => 0                                                                                                                                                                        
 2020-12-01T07:21:32.699Z z2m:Zwave Node 3: value updated: 50-1-value-66561 233.5 => 233.9                                                                                                                                                                    
 2020-12-01T07:21:32.700Z z2m:Zwave Node 3: value updated: 50-1-deltaTime-66561 0 => 0                                                                                                                                                                        
 2020-12-01T07:22:02.155Z z2m:Zwave Node 3: metadata updated: 49-2-Air temperature                                                                                                                                                                            
 2020-12-01T07:22:02.156Z z2m:Zwave Node 3: value updated: 49-2-Air temperature 25.1 => 25.2                                                                                                                                                                  
 2020-12-01T07:22:02.332Z z2m:Zwave Node 3: metadata updated: 49-3-Air temperature                                                                                                                                                                            
 2020-12-01T07:22:02.333Z z2m:Zwave Node 3: value updated: 49-3-Air temperature 0 => 0                                                                                                                                                                        
 2020-12-01T07:22:02.495Z z2m:Zwave Node 3: metadata updated: 49-4-Air temperature                                                                                                                                                                            
 2020-12-01T07:22:02.495Z z2m:Zwave Node 3: value updated: 49-4-Air temperature 20 => 19.9 
```

https://www.jottacloud.com/s/006df9ed7020b1248008d41229f2f0896a5

**Comment by robertsLando** [comment]
That's really strange :confused: Is that the only one value that is missing?

**Comment by roflmao** [comment]
```
49-2-Air temperature
49-3-Air temperature 
49-4-Air temperature 
```

Screenshot shows all values shown.

Maybe we should continute in https://github.com/zwave-js/zwavejs2mqtt/issues/38#issuecomment-736280796

**Pull request merged**
