### PR TITLE
feat(config): add additional identifier for FGKF-601

### LINKED ISSUE #2526: Fibaro unknown manufacturer/product
Hi!
I have Fibaro FGWPF-102 (device ID is 0x010f-0x0602-0x4003) - this is the same that Product Identifiers: 0x0602:0x1001, 0x0602:0x1003, but RU version. Also i have FGKF601 (device ID is 0x010f-0x1001-0x4000) - RU version. There is only PID 0x1001:0x1000, 0x1001:0x2000, 0x1001:0x3000 in z-wave js database.
Both fibaro devices sowed as Unknown manufacturer 0x010f/Unknown product 0x4003 for FGWPF-102 and Unknown manufacturer 0x010f/Unknown product 0x4000 for FGKF601.
Also there aren't "Configuration" section to manage devise parameters. As they the same versions of devices but Ru versions, how i can make to detect they correctly?
Screenshot 2021-05-02 203257

### PR DESCRIPTION
**Pull request by marcus-j-davies**
Fixes https://github.com/zwave-js/node-zwave-js/issues/2526

### CODE REVIEW

**Comment by marcus-j-davies** [comment]
@zwave-js-bot fix lint

**Comment by marcus-j-davies** [comment]
@AlCalzone ?

**Comment by AlCalzone** [comment]
That's no lint check that failed :)

**Comment by marcus-j-davies** [comment]
I thought  the checks just had a funny moment, so tried getting clever, to kick it off again.
Bot is more intelligent than I thought

**Comment by AlCalzone** [comment]
Pro tip: You should be able to do that by closing and reopening the PR. 🤓

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
