### PR TITLE
fix(config): add metadata to 0x0258: Shenzhen Neo Siren Alarm

### PR DESCRIPTION
**Pull request by jaym25**
PR description here
[0x0258 - Shenzhen Neo Siren Alarm.txt](https://github.com/zwave-js/node-zwave-js/files/8307701/0x0258.-.Shenzhen.Neo.Siren.Alarm.txt)
Adds values for Alarm and Doorbell Sound Selection

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
I'm a bit confused... The change you did is something else than your description and there is a merge conflict.

**Comment by jaym25** [comment]
Sorry about the mistake.  I am totally new to this and am trying to contribute the additional details contained in the file I attached.  If you can guide me in the right direction, I will be happy to create an actual merge file or fix whatever error I made... or please pass the info to someone who knows how to do it correctly.

**Comment by AlCalzone** [comment]
Ok, I'm assuming you actually wanted to add the `mapRootReportsToEndpoint` compat flag? Can you share some details why this is necessary?

**Comment by jaym25** [comment]
Below is the stuff I wanted to add to 0x0258: Shenzhen Neo Siren Alarm.  It appears like I made the pull request in the wrong place?  My additions aren't to compatibility flag but to the configuration file.  What I attached was the entire modified file.  Sorry about the ignorance.
```
		{
			"#": "2",
			"label": "Alarm Duration",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 255,
			"defaultValue": 2,
			"options": [
				{
					"label": "Off",
					"value": 0
				},
				{
					"label": "30 seconds",
					"value": 1
				},
				{
					"label": "1 minute",
					"value": 2
				},
				{
					"label": "5 minutes",
					"value": 3
				},
				{
NEW:					"label": "Always on",
					"value": 255
				}
			]
		},
ALL VALUES BELOW ARE NEW:
		{
			"#": "5",
			"label": "Alarm Sound Selection",
			"valueSize": 1,
			"minValue": 1,
			"maxValue": 10,
			"defaultValue": 9
			"options": [
				{
					"label": "Doorbell",
					"value": 1
				},
				{
					"label": "Fur Elise",
					"value": 2
				},
				{
					"label": "Westminster Chimes",
					"value": 3
				},
				{
					"label": "Ding Dong",
					"value": 4
				},
				{
					"label": "William Tell",
					"value": 5
				},
				{
					"label": "Rondo Alla Turca",
					"value": 6
				},
				{
					"label": "Police Siren",
					"value": 7
				},
				{
					"label": "Evacuation",
					"value": 8
				},
				{
					"label": "Beep Beep",
					"value": 9
				},
				{
					"label": "Beep",
					"value": 10
				}
			]
		},
		{
			"#": "6",
			"label": "Doorbell Sound Selection",
			"valueSize": 1,
			"minValue": 1,
			"maxValue": 10,
			"defaultValue": 10
			"options": [
				{
					"label": "Doorbell",
					"value": 1
				},
				{
					"label": "Fur Elise",
					"value": 2
				},
				{
					"label": "Westminster Chimes",
					"value": 3
				},
				{
					"label": "Ding Dong",
					"value": 4
				},
				{
					"label": "William Tell",
					"value": 5
				},
				{
					"label": "Rondo Alla Turca",
					"value": 6
				},
				{
					"label": "Police Siren",
					"value": 7
				},
				{
					"label": "Evacuation",
					"value": 8
				},
				{
					"label": "Beep Beep",
					"value": 9
				},
				{
					"label": "Beep",
					"value": 10
				}
			]
		},
```

**Comment by AlCalzone** [comment]
Looks like you selected the wrong branch to merge:
grafik

This is a branch our bot created last August and edits an entirely different file.

**Comment by AlCalzone** [comment]
Oh... I just realized you attached a file in the OP. A pull request is usually done in separate steps:
1. you fork the repository into your account
2. you make the edits in your fork, ideally in a new branch
3. you create a pull request from **your branch**

https://docs.github.com/en/get-started/quickstart/contributing-to-projects has a beginner-friendly explanation of the process.

**Comment by AlCalzone** [comment]
Also, I recommend starting in the [config browser](https://devices.zwave-js.io/#) and using Gitpod to edit files:
grafik

This has some guidance to (hopefully) make it easier to do the changes and contribute them.

**Comment by jaym25** [comment]
Thank you, Al.  I give it a try this evening and close this request after I figure it out.

**Comment by jaym25** [comment]
OMG.  I think I got it!  at least I hope...  Thanks for the help

**Pull request closed without merging**
