### PR TITLE
feat(config): add zooz zen31 config driver (imported from ozw)

### PR DESCRIPTION
**Pull request by jcam**

### CODE REVIEW

**Comment by jcam** [comment]
@zwave-js-bot fix-lint

**Comment by jcam** [comment]
@zwave-js-bot fix lint

**Comment by AlCalzone** [comment]
@jcam does that command not work when you comment?

**Comment by jcam** [comment]
@zwave-js-bot fix lint

**Comment by jcam** [comment]
image
https://github.com/zwave-js/node-zwave-js/actions/runs/490560940

**Comment by AlCalzone** [comment]
Strange, looks like you're not authorized to run that (and I forgot a check) but as the PR author you should have been... 🤔

**Comment by AlCalzone** [comment]
@jcam I added some debug output to the bot. Can you try the lint fix again (although it won't do anything)?

**Comment by jcam** [comment]
@zwave-js-bot fix lint

**Comment by jcam** [comment]
@AlCalzone hmm, no rocket, but also no error email

**Comment by jcam** [comment]
actually looking at the run, it appears it was successful. Maybe no rocket because it didn't need to do anything
https://github.com/zwave-js/node-zwave-js/runs/1714885525

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
