### PR TITLE
fix(config): add parameter 17 to ZEN73 (firmware dependent)

### PR DESCRIPTION
**Pull request by cybergrimes**
Added new config entry 17, current ZEN73 models are shipping with firmware v10+. AFAIK there was nothing released between 1.3 and 10.0

Values entered as described with email from Zooz:
Here is the change log for version 10.0:
- Removed delay for on/off operation when scene control is disabled.
- Fixed relay behavior after power outage when used in smart bulb mode.
- Added parameter 17:

17: Disable programming from toggle
0 – programming function from toggle enabled (switch will behave according to manual toggle programming)
1 – programming function from toggle disabled (switch will NOT perform the following manual toggle press functions: 2) exclusion, inclusion, 3) change LED indicator mode. Switch will still perform functions 1) on/off, 4) factory reset, 5) range test tool and central scene triggers (if central scene enabled).

Default: 0

### CODE REVIEW

**Comment by cybergrimes** [comment]
@zwave-js-bot fix lint

**Comment by cybergrimes** [comment]
@zwave-js-bot fix lint

**Comment by blhoward2** [comment]
I've emailed Zooz as I'm not sure I understand exactly what this does. Their description is terrible. We'll wait to merge it until I hear back from them.

**Comment by cybergrimes** [comment]
It refers to the manual control functions of the switch, they are documented on Zooz support site along with the parameter settings. At closer look I think part of what's missing here is documentation of parameter 11.

https://www.support.getzooz.com/kb/article/639-zen73-on-off-toggle-switch-700-advanced-settings/

MANUAL CONTROL

Toggle Up: 
1 x tap: load on; Scene 1, attribute 00
2 x tap: Scene 1, attribute 03
3 x tap: enter inclusion (pairing) mode (only if the switch is not included to the hub); Scene 1, attribute 04
4 x tap: Scene 1, attribute 05
5 x tap: Scene 1, attribute 06
held: Scene 1, attribute 01
released: Scene 1, attribute 02

Toggle Down: 
1 x tap: load off; Scene 2, attribute 00
2 x tap: Scene 2, attribute 03
3 x tap: enter exclusion (unpairing) mode; Scene 2, attribute 04
4 x tap: Scene 2, attribute 05
5 x tap: Scene 2, attribute 06
held: Scene 2, attribute 01
released: Scene 2, attribute 02
held for 10 seconds (LED indicator starts blinking): enter the setting menu >> 5 x tap down for factory reset; 5 x tap up to change LED bulb mode (see parameter 11); 2 x tap down to enable the range test tool.

**Comment by blhoward2** [comment]
I think that may be right, but I'm not sure. It says manual programming, not control. And they don't mention sending scene events in their description. I think it may only disable the inclusion/exclusion/LED option. We'll clarify it with them...we work with them a lot.

**Comment by cybergrimes** [comment]
Glad to hear it. I was working with them on submitting OZW config files last year, I had suggested they reach out to you about files for this project. I just finally made the jump this past week, working to make sure all of my devices have full parameters available.

**Comment by blhoward2** [comment]
We haven't yet scrubbed their files and templated them, but if you see other errors, please bring them to our attention.

**Comment by blhoward2** [comment]
Converting to draft. I confirmed this parameter with Zooz and what it does (disables inclusion/exclusion/LED changes, except on toggles which don't have a LED). The change was made to many models, though, and I'm waiting on them to confirm which ones.

**Comment by blhoward2** [comment]
Just a status update, Zooz owes me a list of devices and change logs. I chased them again on it today.

**Comment by AlCalzone** [comment]
#3100 was just merged, so I've gone ahead and updated your file to match the new config format. As you'll see, paramInformation is now an array of objects.

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
The branch seems to have been deleted, I've recreated the PR here: https://github.com/zwave-js/node-zwave-js/pull/3758

**Pull request closed without merging**
