### PR TITLE
feat(config): update parameters for Inovelli LZW31-SN and LZW31-BSD

### PR DESCRIPTION
**Pull request by otaku**
Continuation of https://github.com/zwave-js/node-zwave-js/pull/1700

### CODE REVIEW

**Comment by otaku** [comment]
Requesting review.  Partial parameters was used for 12 and removed 16, 18, 19, 20 from LZW31-BSD.  I left parameter 17 as it is in the spec sheet.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
I think that `tmp` file wasn't meant to be checked in :)
Looks good otherwise!

**Comment by otaku** [comment]
Dangling file has been removed.  Thank you!

**Comment by AlCalzone** [comment]
Where does this PR leave https://github.com/zwave-js/node-zwave-js/pull/1739 btw?

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
