### PR TITLE
fix: make Multi Channel Association Value IDs internal

### LINKED ISSUE #1175: Make MultiChannelAssociationCC valueIds internal

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #1175

### CODE REVIEW

**Comment by AlCalzone** [comment]
@robertsLando Do you remember which value IDs were shown on the screenshots?

**Comment by robertsLando** [comment]
```
2020-12-01T13:40:15.244Z z2m:Zwave Node 3: value added 3-142-0-maxNodes-1 => 5
2020-12-01T13:40:15.244Z z2m:Zwave Node 3: value added 3-142-0-nodeIds-1 => 
2020-12-01T13:40:15.244Z z2m:Zwave Node 3: value added 3-142-0-endpoints-1 => [object Object]
2020-12-01T13:40:15.245Z z2m:Zwave Node 3: value added 3-142-0-maxNodes-2 => 5
2020-12-01T13:40:15.245Z z2m:Zwave Node 3: value added 3-142-0-nodeIds-2 => 
2020-12-01T13:40:15.245Z z2m:Zwave Node 3: value added 3-142-0-endpoints-2 => 
2020-12-01T13:40:15.245Z z2m:Zwave Node 3: value added 3-142-0-maxNodes-3 => 5
2020-12-01T13:40:15.245Z z2m:Zwave Node 3: value added 3-142-0-nodeIds-3 => 
2020-12-01T13:40:15.245Z z2m:Zwave Node 3: value added 3-142-0-endpoints-3 => 
2020-12-01T13:40:15.246Z z2m:Zwave Node 3: value added 3-142-0-maxNodes-4 => 5
2020-12-01T13:40:15.246Z z2m:Zwave Node 3: value added 3-142-0-nodeIds-4 => 
2020-12-01T13:40:15.246Z z2m:Zwave Node 3: value added 3-142-0-endpoints-4 => 
2020-12-01T13:40:15.247Z z2m:Zwave Node 3: value added 3-142-0-maxNodes-5 => 5
2020-12-01T13:40:15.247Z z2m:Zwave Node 3: value added 3-142-0-nodeIds-5 => 
2020-12-01T13:40:15.247Z z2m:Zwave Node 3: value added 3-142-0-endpoints-5 => 
2020-12-01T13:40:15.247Z z2m:Zwave Node 3: value added 3-94-1-zwavePlusVersion => 1
2020-12-01T13:40:15.247Z z2m:Zwave Node 3: value added 3-94-1-nodeType => 0
2020-12-01T13:40:15.247Z z2m:Zwave Node 3: value added 3-94-1-roleType => 5
```

So all valueids from cc 142 and also I would hide the nodeType and roleType from cc 94

**Comment by AlCalzone** [comment]
I should have all the 142's with this PR. Not sure about roleType. Someone might use that information and it is not exposed through an API like associations.

**Comment by robertsLando** [comment]
@AlCalzone Ok for the roleType (could become a node parameter?) about the nodeType maybe that could be hidden I think?

**Comment by AlCalzone** [comment]
Lets make both node properties (in a different PR)

**Review by robertsLando — APPROVED** [review]
LGTM

**Pull request merged**
