### PR TITLE
feat(config): add checks for partial parameters

### PR DESCRIPTION
**Pull request by AlCalzone**
This PR adds three more checks for partial config parameters:
* Is the value size compatible with the bitmask?
* Is the value size of all related partial params the same?
* Is there a (unnecessary) non-partial config parameter with the same property as a partial one?

### CODE REVIEW

**Comment by AlCalzone** [comment]
found a few errors along the way too.

**Comment by marcus-j-davies** [comment]
trying to not add to the list - so saw this, and it may be related?


But setting values (specifically  Configuration Values) via `setValue(ValueID,Value)` is that normal practice?
incorrectly aligns the value to 4 Bytes.

```
17:25:15.253 DRIVER » [Node 002] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      17
                      └─[ConfigurationCCSet]
                               parameter #:      31
                               reset to default: false
                               value size:       4
                               value:            6 
```

When in fact, a particular  value might only be 1 byte.
the Configuration Report for a Develo Siren.
[https://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/2308/MT02758_manual.pdf](https://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/2308/MT02758_manual.pdf)

```
17:25:15.320 DRIVER « [Node 002] [REQ] [ApplicationCommand]
                      └─[ConfigurationCCReport]
                               parameter #: 31
                               value size:  1
                               value:       0 
```

Is there a reference to the value size, in the cache anywhere? - it could be used for setValue when targeting the Configuration class?

targeting the CCAPI isn't a problem of course  (and my preferred method) as its asks you for the size.
the value that gets set, is of course ,  incorrect = 0 instead of 6

**Comment by AlCalzone** [comment]
That is configured in the config files. You'll find them in packages/config/config/devices/...
The tricky part will be locating the correct file but you should be able to search for the device label.

**Comment by AlCalzone** [comment]
Oh and feel free to open new issues, this is most likely a bug.

**Comment by marcus-j-davies** [comment]
The config param size states its 4 - manual states 1.
how would you prefer this correction - raise a bug or PR?

> All of the configuration, the data size is 1.  
[MT02758_manual.pdf](https://github.com/zwave-js/node-zwave-js/files/5797942/MT02758_manual.pdf)

config : 0x0175/ph-pse02.json

EDIT
Updating the config correctly aligns the size when using setValue

**Comment by AlCalzone** [comment]
If you have figured it out, pr would be good.

**Comment by marcus-j-davies** [comment]
done - so we'll see ;-)

**Pull request merged**
