### PR TITLE
feat: add compat flag to remove support of CCs

### LINKED ISSUE #1426: Homeseer WD200+ dimmer not providing updates to MQTT topics on change
**Describe the bug**
When setting the changeValue topic with MQTT to turn on/off or set dim level the light changes to the correct setting but the MQTT topics currentValue and targetValue never get updated.
Discussion of issue: https://zwave2mqtt.slack.com/archives/C01DQ24SDKL/p1610818512273700

It looks like SupervisionCCReport command is failing in the zwave logs.

**Device information**
Which device(s) is/are affected (make/model)?  Homeseer WD200+
What are the node IDs? 22

**Last Known Working Configuration**
- [ ] New device
- [ ] Previously working device (node-zwave-js)
    - Which library version/docker image/adapter version?
    - Have you made any recent configuration changes to the device? Describe.

- [X] Previously working device (other platform)
    - Which platform? zwave2mqtt/HA Native Zwave
    - Have you made any recent configuration changes to the device? Describe.
    
**Installation information**
How did you install `node-zwave-js`?
- [X] Zwavejs2mqtt (latest) docker image
- [X] Zwavejs2mqtt (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [ ] Manual docker build
    - Against which branch of `node-zwave-js`?
    - With which branch of `zwavejs2mqtt`?
- [ ] Other (describe)
- [ ] Manually built (`git clone` - `yarn install` - `yarn run build:full`) 

**To Reproduce**
1. issue:  z2m/nodeID_22/38/0/targetValue/set to 0
2. light turns off, but MQTT targetValue and CurrentValue do not get updated with a new timestamp or value.
3. issue:  z2m/nodeID_22/38/0/targetValue/set to 50 
4. light is set to dim level of 50, but targetValue and currentValue do not get updated with a new timestamp of value.

**Logfile:** 
[zwavejs_1_WD200_LightOn.log](https://github.com/zwave-js/node-zwave-js/files/5825210/zwavejs_1_WD200_LightOn.log)

### PR DESCRIPTION
**Pull request by AlCalzone**
and apply it to HomeSeer WD200+ to remove Supervision support

fixes: #1426

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

@crzykidd wanna try this?

**Comment by crzykidd** [comment]
This is so much better.  Interaction is now Turn light off in HA.  Light turns off, UI toggles to off, then back to on, then in about 5 seconds it sets back to off in the UI.    It would be great to be able to set that refresh time, but this fix is more than enough to allow me to move these switches into zwavejs from OZW.

**Comment by AlCalzone** [comment]
The refresh time should be enough once this is merged. I have another improvement for the flickering, already merged in master in the meantime.

**Comment by danieljy** [comment]
@AlCalzone Hi there!

I recently filed this issue with HA:

https://github.com/home-assistant/core/issues/46676

It seems like despite me running all the latest code, my WD200+ dimmers are suffering from an issue that I believe is related to this. Please see above and let me know if I can provide any more data to help debug.

My GUESS right now is that the code that checks for whether a node is a supervised one: 
https://github.com/zwave-js/node-zwave-js/pull/1522/commits/6cd0dfa62d616b6220a00d13b375bd61012a25e0#diff-9397c8948a06d7061964655d80272f34166e53676c4642a76c3a7799b61e4360R322

still thinks my WD200+ dimmers support supervision.

Is there some kind of reset I need to do on the zwavejs DB or something so that it understands that they really shouldn't have that capability?

**Comment by AlCalzone** [comment]
Have you done a re-interview (or even the initial interview) of the node since the updates? If not, re-interviewing would be my first attempt.

**Comment by danieljy** [comment]
Would that just happen if I restart the zwave_js? If so then yes.
If no, I'm not sure how to even do it given the integration I have set up.

I am running:

Z-Wave JS
Current version: 0.1.7

in supervisor.

I don't really see how to re-interview.

**Comment by PhAzE-Variance** [comment]
I have verified that compat flag is set in the config and did a reinterview on all my wd200's but they still act in the same manor.

**Comment by danieljy** [comment]
@PhAzE-Variance Great so I'm not alone.

How did you reinterview, just so that I'm on th same page.

**Comment by PhAzE-Variance** [comment]
I'm using the interface through zwavejs2mqtt. It has a list of devices and options for each like re-interview or heal.

**Comment by danieljy** [comment]
Ah. I am using the basic (official) zwavejs integration.
I can try it with that one and see what the behavior is there 

It's a bit weird that there are two. Seems like one has the bells and whistles, but isn't the official integration.

**Comment by danieljy** [comment]
Also, when you say you've verified that the flag is set  where are you looking?

**Comment by PhAzE-Variance** [comment]
I checked in the zwavejs2mqtt docker under:

/usr/src/app/node_modules/@zwave-js/config/config/devices/0x000c/hs-wd200_5.11.json

There is a section that removes the supervisor class. Then when you add or interview those devices they use this config.

BTW, zwavejs and zwavejs2mqtt run the same core but the mqtt version has a nice interface for node control. You can disable the mqtt part and use the web socket gateway so it functions the same as the zwavejs core integration.

**Comment by AlCalzone** [comment]
Hm then it might not be working as intended. Can you make me a full log from the interview to controlling the device?

**Comment by manderSD** [comment]
Ya something isn't right with this.  I have issues with switches from time to time.   So it is now intermintant for me.  some switches work and some don't, but the switches are the same firmware and config settings.. I can pull some logs this weekend, haven't had time to dig into it.

**Comment by crzykidd** [comment]
Ya something isn't right with this. I have issues with switches from time to time. So it is now intermintant for me. some switches work and some don't, but the switches are the same firmware and config settings.. I can pull some logs this weekend, haven't had time to dig into it.

**Comment by danieljy** [comment]
Update: Simply moving to zwavetomqtt seems to have resolved my issue. My WD200+ now operate just like the WD100+s. State still flips immediately to off after turning on, but then  5 seconds later, it sets to on.

I'm not sure why this would've been the case, being that I assume both the regular integration and this one are running at the same zwave JS version...

----------------

As a side note, there are so many pieces of code that it's a bit hard to understand the versioning.

Do I have this correct?

https://github.com/zwave-js/node-zwave-js (main library)
https://github.com/zwave-js/zwave-js-server (includes a fixed version of main library, has its own versioning scheme)
https://github.com/zwave-js/zwavejs2mqtt (includes zwave-js server, so must be kept up to date with changes there too, has nice management UI)

Then there's the HA zwave integration (not sure where that code lives).

What is the process by which the code gets updates (when node-zwave-js adds a new release tag)?

**Comment by AlCalzone** [comment]
> Do I have this correct?

> node-zwave-js (main library)

YES

> zwave-js-server

Is the bridge to HA, can be uses standalone or hosted by zwavejs2mqtt

> zwavejs2mqtt

Can be used with or without zwave-js-server. The server version needs to be bumped here too and node-zwave-js version needs to be compatible to the server's one.

We're planning on providing a graphical representation of the architecture, but didn't get very far here.

---

Basically, the HA version is lagging behind a bit, since 6.3.0 introduced changes that were breaking from a HA POV.

**Comment by danieljy** [comment]
@AlCalzone  Thanks for the explanation, and for your hard work on this.

Back to the original issue, am I right to assume that if I'm not getting back a status update after setting a new level, that it must be because zwavejs believes the node is supervised?

Note that it's all working now, but given @crzykidd 's comments I'm concerned that there is some flakiness with the override mechanism (that reads the per-device config and eliminates the offending command class support).

Is there some way of seeing what command classes zwavejs actually does believe each device supports at a given time?
In general, where does zwavejs save its state (when running under HA)?

**Comment by PhAzE-Variance** [comment]
I will try and get a capture tomorrow. I'm on zwavejs2mqtt and still have flakiness in the UI on most of them.

**Comment by PhAzE-Variance** [comment]
Interestingly, I updated my docker to use zwavejs 6.4.0 and the problem isn't happening anymore. All 6 hs-wd200 dimmers do appear to update properly a few seconds, so I can't reproduce the problem to capture in a log. 

Edit: nvm as soon as I posted this it happened on one of the dimmers again. I will continue to try and get a log capture of it.

**Comment by XtacySWAT** [comment]
I have a zlink zl-pd-100 that had this issue.  i added the compat stuff to zl-pd-100.json and it started working properly.

**Comment by AlCalzone** [comment]
@XtacySWAT mind sharing the file?

**Comment by XtacySWAT** [comment]
[zl-pd-100.txt](https://github.com/zwave-js/node-zwave-js/files/6017081/zl-pd-100.txt)
Sure, attached, (renamed to .txt so it would upload here)

**Comment by danieljy** [comment]
Update: When I first moved to 6.4 (mqtt version) the problem seemed to be solved. However, like @PhAzE-Variance, the problem came back after a few days :(

FYI, it does indeed look like the removal of the supervision CC is not having an effect. When I examine the contents of the .json file this is what I see:

```
                "0x6c": {
                    "name": "Supervision",
                    "endpoints": {
                        "0": {
                            "isSupported": true,
                            "isControlled": false,
                            "secure": false,
                            "version": 0
                        }
                    }
                },
```

**Comment by AlCalzone** [comment]
Can you please make a log like I requested above and open a new issue with that?

**Comment by danieljy** [comment]
Yes sorry I lost that in the conversation.

**Comment by danieljy** [comment]
@AlCalzone I did a reinterview.

Do you want me to file a new bug in this repo, or in the mqtt one? I just want to do the right thing...

**Comment by AlCalzone** [comment]
In this repo please

**Comment by danieljy** [comment]
@AlCalzone  https://github.com/zwave-js/node-zwave-js/issues/1865

**Pull request merged**
