### PR TITLE
feat: allow configDir to be passed as an option

### PR DESCRIPTION
**Pull request by ghost**
It's frustrating while developing to keep losing the cache file.  IMO, it should be possible to check the cache file into version control to save having to re-interview.

### CODE REVIEW

**Comment by AlCalzone** [comment]
LOL, I was just working at the same thing (a bit more complex though)

**Comment by AlCalzone** [comment]
This will be included in PR #538

**Comment by CliffS** [comment]
> LOL, I was just working at the same thing (a bit more complex though)

Thanks.  I don't do *complex* in typescript.  It already took me five goes to get it to compile and three goes to get past your lint. :smile:

**Comment by AlCalzone** [comment]
>  three goes to get past your lint. 😄

:D I have the ESLint and Prettier plugins in VSCode. So just saving the file does most of the work.

**Pull request merged**
