### PR TITLE
fix(config): remove delete duplicate device file ge_46202

### PR DESCRIPTION
**Pull request by blhoward2**
Delete duplicate device file inadvertently introduced. #1311

### CODE REVIEW

**Comment by blhoward2** [comment]
The one lint is failing with a missing file error...seeing as I'm deleting the file that makes some sense.

**Comment by AlCalzone** [comment]
You need to update the index :)
https://zwave-js.github.io/node-zwave-js/#/development/config-files?id=contributing-configuration-files

**Comment by blhoward2** [comment]
It's always something.

**Comment by blhoward2** [comment]
I don't seem to be able to run that:

```
yarn run config import -i
Usage: yarn [options]

yarn: error: no such option: -i
```

And if I remove the -i:

```
yarn run config import
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
```

**Comment by AlCalzone** [comment]
Uhh. That works for me. Yarn installed correctly?

**Comment by AlCalzone** [comment]
Can also do

    npm run config import -- -i

**Comment by AlCalzone** [comment]
https://stackoverflow.com/questions/45430645/yarn-error-no-such-option-with-dev-flag

**Comment by blhoward2** [comment]
Grr. That worked RE the yarn error. Then I manually installed two missing modules. Now it wants me to update my type definitions. Ideas? (It would really help to have some sort of setup script for people that may want to do this...)

```
/usr/lib/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
maintenance/importConfig.ts:7:1 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.
```

Where is the tsconfig?

**Comment by blhoward2** [comment]
I think I'm through that, but now I am missing like eight more modules and the first one fails the host key verification:

alcalzone-shared/objects

**Comment by blhoward2** [comment]
I'm at a loss. I've manually installed every module it complains about with the -g flag, and I still get the same errors:

```
yarn run v1.22.10
$ ts-node maintenance/importConfig.ts import -i

/usr/lib/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
maintenance/importConfig.ts:11:31 - error TS2307: Cannot find module 'alcalzone-shared/objects' or its corresponding type declarations.

11 import { composeObject } from "alcalzone-shared/objects";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
maintenance/importConfig.ts:12:35 - error TS2307: Cannot find module 'alcalzone-shared/typeguards' or its corresponding type declarations.

12 import { isArray, isObject } from "alcalzone-shared/typeguards";
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
maintenance/importConfig.ts:13:21 - error TS2307: Cannot find module 'ansi-colors' or its corresponding type declarations.

13 import { red } from "ansi-colors";
                       ~~~~~~~~~~~~~
maintenance/importConfig.ts:15:19 - error TS2307: Cannot find module 'axios' or its corresponding type declarations.

15 import axios from "axios";
                     ~~~~~~~
maintenance/importConfig.ts:17:21 - error TS2307: Cannot find module 'fs-extra' or its corresponding type declarations.

17 import * as fs from "fs-extra";
                       ~~~~~~~~~~
maintenance/importConfig.ts:18:24 - error TS2307: Cannot find module 'json5' or its corresponding type declarations.

18 import * as JSON5 from "json5";
                          ~~~~~~~
maintenance/importConfig.ts:20:25 - error TS2307: Cannot find module 'semver' or its corresponding type declarations.

20 import { compare } from "semver";
                           ~~~~~~~~
maintenance/importConfig.ts:22:22 - error TS2307: Cannot find module 'xml2json' or its corresponding type declarations.

22 import xml2json from "xml2json";
                        ~~~~~~~~~~
maintenance/importConfig.ts:23:19 - error TS2307: Cannot find module 'yargs' or its corresponding type declarations.

23 import yargs from "yargs";
                     ~~~~~~~
maintenance/importConfig.ts:180:23 - error TS7006: Parameter 'err' implicitly has an 'any' type.

180  	stream.on("error", (err) => {
     	                    ~~~
maintenance/importConfig.ts:733:24 - error TS2532: Object is possibly 'undefined'.

733  if (!isArray(IDs) || !IDs.length) {
                           ~~~
maintenance/importConfig.ts:741:22 - error TS2532: Object is possibly 'undefined'.

741  for (let i = 0; i < IDs.length; i++) {
                         ~~~
maintenance/importConfig.ts:743:42 - error TS2532: Object is possibly 'undefined'.

743  		`Fetching device config ${i + 1} of ${IDs.length}...`,
     		                                      ~~~
maintenance/importConfig.ts:745:37 - error TS2532: Object is possibly 'undefined'.

745  	const content = await fetchDevice(IDs[i]);
     	                                  ~~~
maintenance/importConfig.ts:747:28 - error TS2532: Object is possibly 'undefined'.

747  		path.join(ohTempDir, `${IDs[i]}.json`),
     		                        ~~~
maintenance/importConfig.ts:935:4 - error TS7006: Parameter 'file' implicitly has an 'any' type.

935  	(file) =>
     	 ~~~~
maintenance/importConfig.ts:1105:14 - error TS7006: Parameter 'id' implicitly has an 'any' type.

1105  					?.map((id) => parseInt(id as any))
      					       ~~
maintenance/importConfig.ts:1106:16 - error TS7006: Parameter 'num' implicitly has an 'any' type.

1106  					.filter((num) => !Number.isNaN(num)),
      					         ~~~

    at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
error Command failed with exit code 1.

```

**Comment by AlCalzone** [comment]
> I've manually installed every module it complains about with the -g flag

nonono... installing dependencies globally should only be done for CLI commands and package managers.

Just run `yarn` or `npm install` in the repo directory.

**Comment by blhoward2** [comment]
I’ll try that later, thanks. The documentation does a good job explaining some of these things but I feel like in some areas (like here) it assumes a level of knowledge with JavaScript/typescript that not everyone will have as the project grows. Just a thought. I guess ultimately it’s a question of how accessible you want it to be for people to add devices and such.

**Comment by AlCalzone** [comment]
Good point! I've been thinking about letting the bot offer help (like he now does if there are ESLint/Prettier errors), but I need to figure out how to best do that. The fix lint help reacts if the check fails, but we cannot use that here.

...(or we should get rid of the index file entirely)

**Comment by AlCalzone** [comment]
Let's see if the bot can help you here...

**Comment by AlCalzone** [comment]
Meh... I kinda expected that.

**Comment by blhoward2** [comment]
There are only so many device files. How much of a performance hit would it be to build the index in the fly on startup from the directories? Or the first time a node needs to be refreshed/added?

**Comment by AlCalzone** [comment]
Probably not too much of a hit. There are some pitfalls though but they might cause much less problems than these PRs 😅

**Comment by blhoward2** [comment]
It would be one less thing to do. I’m not sure how often they change in reality but what happens when you have two people submit PRs at the same time? Presumably someone has to rebuild the index then. Maybe it doesn’t happen enough to worry about that though. They backed up for qt-ozw but that’s because no one was merging them.

**Comment by blhoward2** [comment]
Ok, so I can finally run the yarn command and it finishes without an error, but git status doesn't show any changed files for me to add to the push. Shouldn't index.json or something be changing?

**Comment by blhoward2** [comment]
Finally! So the yarn config command did not actually change the index. It appears to be broken? The npm version worked.

**Comment by blhoward2** [comment]
Alright, new index pushed. It shows changes other than the ones to delete ge_46202 though. Were there other uncommitted changes?

**Comment by AlCalzone** [comment]
Yeah I've noticed some changes, but that seems to be mostly due to changes in sort order (why ever).

I wonder why it didn't do something for you. This did work locally and on CI:
https://github.com/zwave-js/node-zwave-js/pull/1315/files#diff-bb9bc3c636fea36813e748c9e3f36b90a14d8099a56c694c189df643fd9521b4R226

**Comment by AlCalzone** [comment]
But let's not care about it now, I think I'll get rid of the index tonight.

**Comment by AlCalzone** [comment]
I'm gonna leave this PR open for now. Seems the bot also didn't react to the lint error, so this serves as a good base for debugging :)

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
