### PR TITLE
fix(config): add fingerprint to Aeotec ZWA024

### PR DESCRIPTION
**Pull request by HammerAdmin86**
Firmware update for Aeotec product ZWA024 changes the product type parameter (XYZ-114-0-productType) from 258 (0x0102) to 7170 (0x1c02).

image

### CODE REVIEW

**Comment by HammerAdmin86** [comment]
Could someone assist me with this PR?  I;ve updated the title but the bot still does not like it.

**Comment by apella12** [comment]
I think the capital U needs to be lowercase (ie. update...

**Comment by AlCalzone** [comment]
Well, that could explain why the device needs to be re-included after the update.

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
Thanks!

**Pull request merged**
