### PR TITLE
feat(config): add compat option skipConfigurationInfoQuery

### LINKED ISSUE #1128: Z-Wave driver not able to complete the interview with a Heatit Z-TRM2 device
**Describe the bug**
Node 009 is not able to complete the Interview. I can see that Node 009 is having a hard time being Interviewed. It's a Heatit Z-TRM2 device. 

**To Reproduce**
1. Start zwavejs2mqtt with a Heatit Z-TRM2 thermostat in the network
2. Observe the not completed interview. Last completed stage is NodeInfo.

**Device information**
Which device(s) is/are affected?   HeatIt Z-TRM2
What are the node IDs? `9`

**Logfile:** 
I added the debug log in https://gist.github.com/larstobi/a644872f2cfb2b96f5a0fb2c1a0d9e5d
as `zwave-4.log`

### LINKED ISSUE #1309: [bug] Unable to properly include Thermofloor Z-TRM2FX thermostats
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: develop (1.0.0-alpha.2)

**Describe the bug**
Unable to properly include [Thermofloor Z-TRM2FX thermostats](https://github.com/zwave-js/node-zwave-js/blob/9fa9a67cd52321de801efdb4d324dfe023759e86/packages/config/config/devices/0x019b/z-trm2fx_3.0.json) using the normal inclusion method.

This happends to all my Z-TRM2FX thermostats (I have 6). All these included fine on OZW. Somehow one odd Thermostat actully got included after many heals/refresh info and container restarts. Couldnt reproduce this on the following 5.

Except for node 45 in the picture below, the other thermostats where added many hours ago and should have completed thire interviews. It seems they hang on interview stage **NodeInfo** or **ProtocolInfo**.

**To Reproduce**
1. Actions -> Start inclusion [RUN]
2. Vise versa on thermostat

**Expected behavior**
The thermostat properly included with zwavejs2mqtt. 

**Additional context**

Picture (taken after the logs below - notice node 45):
image

Logs (first excluding the thermostat, as to then include it again - alas Node 44 and 45 is that same unit):
Better logs posted below

I tried both debug and silly log levels (from the UI), but I only got info? ^

### PR DESCRIPTION
**Pull request by AlCalzone**
This PR adds a new compat option to skip the `ConfigurationCC` parameter info query which causes devices like the `Z-TRM2fx` to flood the network with garbage reports.

In addition, it adds a workaround for a bug **also** present in this device from hell, which causes the V3 query for the first parameter number to **also** send an invalid response.

fixes: #1309
fixes: #1128

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

**Comment by AlCalzone** [comment]
@jkaberg, the bot should post an npm install command soon, which you can use to test this PR. Alternatively, build the dockerfile against the `fix-ztrm2fx` branch for further debugging.

**Comment by jkaberg** [comment]
Device from hell 😆 

d820481ef14b1cd2a16ff4e7660deb5f

Thanks @AlCalzone, that did it! Used the Dockerfile.contrib to build it,

```
DOCKER_BUILDKIT=1 docker build --build-arg SRC=git-clone-src --build-arg Z2M_BRANCH=master --build-arg ZWJ_BRANCH=fix-ztrm2fx --no-cache -t zwavejs2mqtt .
```

And voilà:
image

Didn't show up in Home Assistant just yet, but I'll dive into that later tonight!

**Comment by AlCalzone** [comment]
Thanks for reporting back!

**Pull request merged**
