### PR TITLE
feat(config): add Ring contact sensor v2

### PR DESCRIPTION
**Pull request by ryanrandrews**

### CODE REVIEW

**Comment by ryanrandrews** [comment]
Adding based off of information from https://products.z-wavealliance.org/products/3862

**Comment by ryanrandrews** [comment]
@zwave-js-bot "message must be semantic!" help

**Comment by ryanrandrews** [comment]
@zwave-js-bot fix lint

**Review by blhoward2 — DISMISSED** [review]
Thanks for your attempt. In the interest of getting this merged I just corrected it myself, but in the future please do take a look at our style guide before submitting (in the project docs). Additionally, it is best to edit these in VS Code so Prettier will keep you in line as far as formatting is concerned.

**Review by AlCalzone — APPROVED** [review]
approved with my fixes

**Pull request merged**
