### PR TITLE
fix(cc): update color values manually after set instead of polling

### LINKED ISSUE #1454: [feat] hexColor updates three times, when set - HASS jumps around
**Is your feature request related to a problem? Please describe.**
When changing the `hexColor` (which works great, btw..), three updates are pushed back - one for each component with gradually changing hexColors.. Like, if I push out `ffffff` to something that has `000000` today.. It reports back `ff0000`, `ffff00` and finally `ffffff`.

In HASS, this means the colorpicker, and shown color bounce around, like shown in the gif below.

**Describe the solution you'd like**
.. I don't know.. delay reporting the update?.. Is it possible to batch-set three values at once, so only one report occurs?

**Describe alternatives you've considered**
N/A

**Additional context**
recording

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #1454

### CODE REVIEW

**Comment by AlCalzone** [comment]
@LordMike can you test this please?

**Comment by LordMike** [comment]
There really ought to be an easier way to test zwave-js.. :|

**Comment by AlCalzone** [comment]
Yeah, not use Docker ;)

1. Install zwavejs2mqtt the [Node.js way](https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start?id=nodejs-or-pkg-version) ==> "If you want to compile last code from github:"
2. `npm install zwave-js@<version>`
3. `npm start`

Repeat steps 2/3 as desired.

**Comment by LordMike** [comment]
> Yeah, not use Docker ;)

Uhuh .. :P

If you gave me a .NET project, I'd be all over it.. Javascript and npm - not so much.

I'll try giving it a go tomorrow evening.. if it doesn't get merged by then.. :)

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

**Comment by jcam** [comment]
This is working great for me!
@LordMike if you have an x64 cpu in your host device, you could give my build a go:
hikeit/zwavejs2mqtt:2secduration-rc1-colorfix

**Comment by LordMike** [comment]
I finally got around to pulling the dev image of zwavejs2mqtt, which I assume has this code in it (I hope).. I noticed some bouncing still, so I captured the MQTT messages coming out. It seems like I'm still seeing 3x updates via MQTT, which indicates this is not working?

The version of zwave-js is reported as `6.0.1` - I sadly don't have a git hash.

image

I'll try the alternative image posted here.

**Comment by LordMike** [comment]
The image provided by jcam seems to work better. So the code is just not in `dev` yet.. :)

The first report back with a different value seems to be a fluke or timeout of sorts.. My network is still booting, so it's quite slow at this point.

Looks good!

image

**Pull request merged**
