### PR TITLE
fix(config): add metadata to AEON Labs DSC26

### PR DESCRIPTION
**Pull request by aderusha**
I couldn't find a download link in a canonical source for the manual.  The link in the JSON goes to the manufacturer support page.  Z-Wave Alliance product page does not have a manual available: https://products.z-wavealliance.org/products/709?selectedFrequencyId=-1

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
If there is no manual, just remove the entry. Better than linking to a manual for a different device :)

**Comment by aderusha** [comment]
Oh dear - that was my fault.  So, what I do have is this link: https://help.aeotec.com/support/solutions/articles/6000165733-micro-switch-g2-user-guide-

That's the correct manual from the vendor's site, but it's not a downloadable page.  Should I include that one?  Or just leave the manual tag out.

Sorry about the wrong link :D

**Comment by AlCalzone** [comment]
@blhoward2 what do you think?

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
Thanks again!

**Pull request merged**
