### PR TITLE
fix(config): update default values for Zooz ZSE40

### PR DESCRIPTION
**Pull request by dwradcliffe**
per defaults listed in manual: https://www.getzooz.com/downloads/zooz-z-wave-plus-4-in-1-sensor-zse40-ver2-manual.pdf

### CODE REVIEW

**Comment by dwradcliffe** [comment]
@zwave-js-bot run checks

**Comment by dwradcliffe** [comment]
@zwave-js-bot rename commit

**Comment by AlCalzone** [comment]
Do you know if the parameter defaults changed between firmware versions? I don't think @blhoward2 overlooked that :)

**Comment by dwradcliffe** [comment]
Unfortunately I'm not sure about that. All I know is they didn't match my device running firmware version `32.02` and the posted documentation.

**Comment by AlCalzone** [comment]
I've asked the Zooz support for clarification - lets see what they can tell us.

**Review by blhoward2 — DISMISSED** [review]
The ZSE40 predated me, I only changed parameter 5 but haven't yet cleaned these up. I have no issue changing the defaults.

**Review by AlCalzone — APPROVED** [review]
Verified with Zooz support. The changes (if any) were made some time before the device version 2.0

**Pull request merged**
