### PR TITLE
feat: discover remote TCP serial ports using mDNS

### PR DESCRIPTION
**Pull request by AlCalzone**

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot automerge

**Comment by niemyjski** [comment]
Is there any documentation for this feature?

**Comment by AlCalzone** [comment]
Not really. You'll need something that responds to queries for the `_zwave._tcp.` domain. The responses need to have
* a `PTR` record, pointing to...
* an [`SRV` record](https://en.wikipedia.org/wiki/SRV_record) with the following fields:
	* `target`, set to the domain or IP address
	* `port`, set to the port under which `ser2net` or sth. else is listening
* an optional `TXT` record which can be used to further identify the device (not exposed yet)

How to set this up, I have no idea. Open for any tips.

**Comment by kaechele** [comment]
Here's a possible setup for this.

Hardware:
 - RaspberryPi 3+ with Fedora 38 IoT Edition
 - Nortek GoControl HUSBZB-1

Software:
 - Fedora 38 IoT Edition
 - avahi-daemon enabled
 - ser2net 4.3.12 (built with gensio 2.6.5 with mDNS support enabled)


/etc/ser2net/ser2net.yaml:
```
connection: &my-zwave
  accepter: ipv4,tcp,20100
  enable: on
  options:
    kickolduser: true
    mdns: true
    mdns-sysattrs: true
    mdns-type: "_zwave._tcp"
  connector: serialdev,/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_515014F0-if00-port0,115200N81,nobreak,local

connection: &my-zigbee
  accepter: ipv4,tcp,20101
  enable: on
  options:
    kickolduser: true
    mdns: true
    mdns-sysattrs: true
    mdns-type: "_zigbee._tcp"
  connector: serialdev,/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_515014F0-if01-port0,57600N81,nobreak,local
```

Verifying PTR availability (done from my laptop, ensure mDNS is active in your `systemd-resolved`):
```
$ resolvectl query -p mdns --type=PTR _zwave._tcp.local
_zwave._tcp.local IN PTR my-zwave._zwave._tcp.local         -- link: wlp4s0

-- Information acquired via protocol mDNS/IPv4 in 4.4ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache
```

Check the `SRV` record for that service:
```
$ resolvectl query -p mdns --type=SRV my-zwave._zwave._tcp.local
my-zwave._zwave._tcp.local IN SRV 0 0 20100 rf-hub.local    -- link: wlp4s0

-- Information acquired via protocol mDNS/IPv4 in 2.8ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache
```
Cool, the service is found at `rf-hub.local` port `20100`.

For good measure, check the optional `TXT` record `ser2net` creates:
```
$ resolvectl query -p mdns --type=TXT my-zwave._zwave._tcp.local
my-zwave._zwave._tcp.local IN TXT "provider=ser2net" "gensiostack=tcp" "devicetype=serialusb" "bInterfaceNumber=00" "interface=HubZ Z-Wave Com Port" "idProduct=8a2a" "idVendor=10c4" "serial=515014F0" "manufacturer=Silicon Labs" "product=HubZ Smart Home Controller" -- link: wlp4s0

-- Information acquired via protocol mDNS/IPv4 in 2.8ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache
```
Or a little more readable using `gmdns` from `gensio`:
```
$ gmdns -t _zwave._tcp
All-for-now:
Found:
 interface: 0
 iptype: ipv4
 name: 'my-zwave'
 type: '_zwave._tcp'
 domain: 'local'
 host: 'rf-hub.local'
 addr: 'ipv4,10.0.0.139,20100'
 txt:
  'provider=ser2net'
  'gensiostack=tcp'
  'devicetype=serialusb'
  'bInterfaceNumber=00'
  'interface=HubZ Z-Wave Com Port'
  'idProduct=8a2a'
  'idVendor=10c4'
  'serial=515014F0'
  'manufacturer=Silicon Labs'
  'product=HubZ Smart Home Controller'
Found:
 interface: 0
 iptype: ipv6
 name: 'my-zwave'
 type: '_zwave._tcp'
 domain: 'local'
 host: 'rf-hub.local'
 addr: 'ipv6,fdde:2311:9feb:0:c5fb:dda6:73bb:97d2,20100'
 txt:
  'provider=ser2net'
  'gensiostack=tcp'
  'devicetype=serialusb'
  'bInterfaceNumber=00'
  'interface=HubZ Z-Wave Com Port'
  'idProduct=8a2a'
  'idVendor=10c4'
  'serial=515014F0'
  'manufacturer=Silicon Labs'
  'product=HubZ Smart Home Controller'
```

The additional information `ser2net` provides in the `TXT` field (thanks to `mdns-sysattrs: true` in the config) could be parsed out by Z-Wave UI to show a prettier formatted name for the Adapter used.

Currently it shows up in Z-Wave UI like this:
Z-Wave JS UI showing mDNS discovered device

**NOTE:** If you're running Z-Wave JS UI inside Docker make sure to set `--network host` so that mDNS can function correctly.

**Pull request merged**
