### PR TITLE
feat(config): add support for Linear/Nortek/GoControl WT00Z5-1

### PR DESCRIPTION
**Pull request by natekspencer**
Adds support for the Linear/Nortek/GoControl WT00Z5-1 accessory switch.

Config was imported from OpenHAB and compared to similar WD500Z5-1 switch.

### CODE REVIEW

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
Thanks!

**Comment by blhoward2** [comment]
@natekspencer Does your wt00z5-1 require the same compat flag as the wt00z-1 so that it sends events on taps? #1708

**Comment by natekspencer** [comment]
@blhoward2 no, the wt00z5-1 appears to be fine. It is z-wave plus and supports central scene commands.

**Comment by blhoward2** [comment]
Ok

**Pull request merged**
