### PR TITLE
feat: handle device class of endpoints

### LINKED ISSUE #2100: Basic CC mapping does not work if node has a different device class than the endpoint
```
20:54:42.383 CNTRLR « [Node 010] received response for protocol info:
                      basic device class:    Routing Slave
                      generic device class:  Multilevel Switch
                      specific device class: Multilevel Power Switch
...
20:54:43.656 CNTRLR « [Node 010] received response for endpoint capabilities (#2):
                      generic device class:  Binary Sensor
                      specific device class: Unused
```

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #2100
and was probably due long ago 😅

### CODE REVIEW

**Comment by AlCalzone** [comment]
@aveseli can you test if this branch fixes your problem with the Flush Dimmer?
You'll probably need to build a custom container https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds

And re-interview the node for the changes to have an effect.

**Comment by aveseli** [comment]
It reports the state after a restart here:

Screenshot 2021-03-18 at 22 25 10

I guess this is expected.

One strange thing I noticed: it toggles the value to `true` and after 2-5 seconds it switches back to `false` without me pressing the switch.

I have build a new docker image like this:

`DOCKER_BUILDKIT=1 docker build --build-arg SRC=git-clone-src --build-arg Z2M_BRANCH=master --build-arg ZWJ_BRANCH=endpoint-device-class --no-cache -f zwavejs2mqtt/docker/Dockerfile.contrib -t zwavejs2mqtt .`

I am not sure if using  `Z2M_BRANCH=master ` is correct, since the control panel changes a bit and probably this is still under development.

**Comment by AlCalzone** [comment]
Could you make a log so I can check what exactly happens?

**Comment by aveseli** [comment]
[zwavejs2mqtt-store-2.zip](https://github.com/zwave-js/node-zwave-js/files/6173503/zwavejs2mqtt-store-2.zip)

What I did:
- starting the new test version of zwavejs2mqtt
- hitting the switch 2-3 times
- re-interviewing the node 10
- hitting the switch 2-3 times

Please note: I configured the zwave logging to only include Node 10.

**Comment by AlCalzone** [comment]
Ok so it looks like the mapping works now, but the device actually sends a followup Binary Sensor Report with state `false`. You could try adding the controller node to association group 7 to see if this changes things.

I'm actually not sure how this is supposed to work. I'll ask my contact at Qubino and let you know.

Let's continue this discussion in your original issue #2099 - we might have to do something else to make the device work correctly.

This PR is working as intended and fixes #2100.

**Pull request merged**
