### PR TITLE
feat(conf): Add assoc. groups to Namron 2 kanaler bryter

### PR DESCRIPTION
**Pull request by jmgiaever**
Added the missing association groups for this device.

2. https://www.elektroimportoren.no/docs/lib/4512720-Brukerveiledning-5.pdf
See page 2 for groups.

### CODE REVIEW

**Review by AlCalzone — COMMENTED** [review]
Maybe this is not necessary. The device supports Z-Wave Plus and Association Group Info CC, so this info can be discovered automatically. We do still specify the groups to improve bad labels, so it depends on how the associations are shown without this change. Can you share that?

**Comment by jmgiaever** [comment]
Hi,

It's seems like you are correct. However, the reason I added it was because the assoc.groups list showed up empty yesterday when I added the switch. But now they're there! 

I haven't re-interviewed the nodes, so why they didn't show up yesterday is a mystery to me.

**Comment by jmgiaever** [comment]
Can add: Turned out it was zwavejs2mqtt that needed a fullpage refresh to get the list of associations populated. Just re-tried with another remote now.

**Comment by AlCalzone** [comment]
Can you still share how the associations are discovered? Wonder if the labels are okay or if we need your change after all.

**Comment by jmgiaever** [comment]
Can you elaborate? Attach the log from the inclusion process?

**Comment by AlCalzone** [comment]
Just a Screenshot of the available association group should be fine

**Comment by jmgiaever** [comment]
Screenshot from 2021-04-17 08-58-34
After inclusion :arrow_up: 

Screenshot from 2021-04-17 11-38-43
After a page refresh **1 kanal** :arrow_up: 

Screenshot from 2021-04-17 11-36-52
After a page refresh **2 kanaler** :arrow_up: 

But looks like @robertsLando already pushed a PR for a fix. I'm testing it out asap and keep you posted. Thanks!

EDIT: Sorry, took screenshot of the wrong node. However this occurred for all of them. I have 3, 1 «1 kanal» and 2 «2 kanaler» remotes.

**Comment by jmgiaever** [comment]
Just a quick notice though; Looks like the «product name» is in the «product code», and the product name is empty? 

The codes should be
1. kanal: 4512712
2. kanaler: 4512720

**Pull request closed without merging**
