### PR TITLE
fix(config): remove duplicate association group for Shenzhen Neo AB01Z

### PR DESCRIPTION
**Pull request by andrewpc**
Fix - isLifeline to only be on Group 2 per manual
Fix - maxNodes to be 1 for Group 2 per manual

Screen Shot 2021-05-03 at 8 27 10 pm

### CODE REVIEW

**Review by AlCalzone — COMMENTED** [review]
We sometimes have multiple associations marked as "lifelines" because some devices use the additional groups to transmit information they don't send via the lifeline.

Are you sure that nothing is missing after this change?

**Comment by andrewpc** [comment]
Thanks for pointing that out. I will test this further and come back

**Comment by AlCalzone** [comment]
Turning this into a draft for now. You should be able to click "ready to review" once you've checked.

**Comment by andrewpc** [comment]
I have tested this with just Group 2 configured as Lifeline and  also with both Group 1 and Group 2 with that setting.

In the first instance, if the siren is triggered then a BinarySwitchCCReport is generated as per below:

```
2021-05-06T03:16:48.442Z DRIVER « [Node 020] [REQ] [ApplicationCommand]
                                  └─[BinarySwitchCCReport]
                                      current value: true
```

If Group 1 is also configured to send reports to the controller, in addition to the BinarySwitchCCReport it also generates a NotificationCCReport

```
2021-05-06T03:19:18.672Z DRIVER « [Node 020] [REQ] [ApplicationCommand]
                                  └─[NotificationCCReport]
                                      notification type:   Siren
                                      notification status: 255
                                      notification state:  Siren active
2021-05-06T03:19:18.676Z CNTRLR   [Node 020] [~] [Notification] Siren[Siren status]: 0 => 1         [Endpoint 0]
2021-05-06 13:19:18.678 INFO ZWAVE: Node 20: value updated: 113-0-Siren-Siren status 0 => 1
2021-05-06T03:19:19.630Z SERIAL » 0x0109001314022502251bea                                            (11 bytes)
2021-05-06T03:19:19.631Z DRIVER » [Node 020] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      27
                                  └─[BinarySwitchCCGet]
2021-05-06T03:19:19.632Z SERIAL « [ACK]                                                                   (0x06)
2021-05-06T03:19:19.638Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-05-06T03:19:19.639Z SERIAL » [ACK]                                                                   (0x06)
2021-05-06T03:19:19.639Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-05-06T03:19:19.660Z SERIAL « 0x010700131b000002f2                                                 (9 bytes)
2021-05-06T03:19:19.661Z SERIAL » [ACK]                                                                   (0x06)
2021-05-06T03:19:19.662Z DRIVER « [REQ] [SendData]
                                    callback id:     27
                                    transmit status: OK
2021-05-06T03:19:19.673Z SERIAL « 0x010900040014032503ff3c                                            (11 bytes)
2021-05-06T03:19:19.674Z CNTRLR   [Node 020] [~] [Binary Switch] currentValue: true => true         [Endpoint 0]
2021-05-06 13:19:19.675 INFO ZWAVE: Node 20: value updated: 37-0-currentValue true => true
2021-05-06T03:19:19.676Z SERIAL » [ACK]                                                                   (0x06)
2021-05-06T03:19:19.678Z DRIVER « [Node 020] [REQ] [ApplicationCommand]
                                  └─[BinarySwitchCCReport]
                                      current value: true
```

If its desirable to have both be enabled by default, let me know and I modify my pull request to restore that setting for Group 1 and keep the other changes instead.

**Comment by AlCalzone** [comment]
> 2021-05-06T03:19:19.631Z DRIVER » [Node 020] [REQ] [SendData]
>                                   │ transmit options: 0x25
>                                   │ callback id:      27
>                                   └─[BinarySwitchCCGet]

Wait... why is the switch state being requested here? Do you have an automation active that polls it?

**Comment by andrewpc** [comment]
No I dont. I triggered this log by enabling the siren switch in the HA UI which triggered a BinarySwitchCCSet. Would HA be somehow causing the state to be requested via the followup GET?

**Comment by AlCalzone** [comment]
> which triggered a BinarySwitchCCSet

Ok that explains it. The Get is a followup verification. If there's nothing else missing than the seemingly unnecessary notification, we can remove the auto-assignment to group 1.

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
