### PR TITLE
chore: update importConfig, ZWA import and config normalization with comments

### PR DESCRIPTION
**Pull request by blhoward2**
Incorporates local changes from other branches

### CODE REVIEW

**Comment by blhoward2** [comment]
@zwave-js-bot fix lint

**Comment by blhoward2** [comment]
@zwave-js-bot fix lint

**Comment by blhoward2** [comment]
@zwave-js-bot fix lint

**Review by AlCalzone — APPROVED** [review]

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Just so I don't forget. We should delete the test file before merging.

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
