### PR TITLE
fix(config): correct mcohome mh s510 series device files

### PR DESCRIPTION
**Pull request by kanebullen**
Additional parameters added to configuration files.

### CODE REVIEW

**Review by blhoward2 — APPROVED** [review]
Approved with the changes I pushed.

**Review by blhoward2 — CHANGES_REQUESTED** [review]
Please incorporate the changes in your PR #2169 in this PR. Also #2151.

**Comment by kanebullen** [comment]
@blhoward2 I'm going around in circles working out how to incorporate the additional parameters - I'd committed the changes against another PR (I think), but I think that has now caused the potential conflicts you mention

Might just be easiest for me to wait until this PR is merged, and then use that as a basis to do a separate PR for the additional parameters.

**Comment by blhoward2** [comment]
That means we'd have to review this same file over and over. Can you try downloading VS Code and the GitHub plug-in?

**Comment by kanebullen** [comment]
Ok - Will do - I originally used vscode to make the changes, but used the web UI to commit.        Have been playing with the github desktop app and not really sure how it all works..

**Comment by kanebullen** [comment]
Sorry @blhoward2 - I'm not having much luck, and have to crash.    I really want to help out to save work for others, but struggling with the github side of things..       I probably need a solid bunch of hours to work out the basics, not sure when I'll get that chance!

**Comment by AlCalzone** [comment]
>  I really want to help out to save work for others, but struggling with the github side of things..

Easiest way:
* Fork the repo on Github
* Open VSCode
* Clone your fork and open the folder
* Make a new branch
* Do all necessary edits in that branch, commit them, push to your fork (you can use the VSCode UI for all of that)
* Go to Github, make a PR from your branch to this repo.

**Comment by kanebullen** [comment]
Thanks AlCalzone - I have done this, and committed a bunch of changes - but this has resulted in another PR (#2266 )       Couldn't work out how to send to this PR.

**Comment by kanebullen** [comment]
I have incorporated @blhoward2's changes into #2266 along with further changes, so I think easiest if I close this one.

**Pull request closed without merging**
