### PR TITLE
fix(config): add missing config params for button 1 (ZDB5100)

### PR DESCRIPTION
**Pull request by kvs**
Copied from params for button 2, matches what is written here: https://logic-group.com/download/3571/

### CODE REVIEW

**Comment by AlCalzone** [comment]
@blhoward2 looks like this needs some cleanup too.

**Comment by blhoward2** [comment]
@kvs We've merged some detailed guidance on adding device files since you pushed this, including a detailed style guide. Please take a looka nd change this file to match the style guide if you'd still like this merged. https://zwave-js.github.io/node-zwave-js/#/

**Review by blhoward2 — CHANGES_REQUESTED** [review]
@kvs We've merged some detailed guidance on adding device files since you pushed this, including a detailed style guide. Please take a looka nd change this file to match the style guide if you'd still like this merged. https://zwave-js.github.io/node-zwave-js/#/

**Review by blhoward2 — CHANGES_REQUESTED** [review]
@kvs If you're still interested in having this merged, could you please take a look at the style guide I linked in my prior comment? Thanks!

**Comment by Roagert** [comment]
This Can be closed. Already resolved in another PR that has Bern merged

**Pull request closed without merging**
