### PR TITLE
fix(config): remove Z-Wave Plus CC from GE 14318

### LINKED ISSUE #3273: GE/Jasco Model #14318 Zwave Switch will not update Home Assistant UI when operated manually
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

The GE 14318 is described as a zwave plus device, and on HomeSeer and Smartthings it reportedly updated instantly with local control. On zwavejs, the device does not update after local control.

What causes the bug?

What do you observe?

What did you expect to happen?

  2. Click on '...'
  3. Scroll down to '...'
GE/Jasco Model #14318 Zwave Binary Switch does not update the UI when operated manually.  When HA operates the switch it updates the UI with it's current state (on/off) but if I operate the switch manually it does not update the UI.  I have been working with @blhoward2 in the forum on this and I have attached at "Silly" log of the re-interview of the switch and I also operated the switch manually while capturing, 1 on tap and 1 off tap.  Any questions and you can email me at cfrudolphy@gmail.com.
[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/7108150/zwave_js.1.log)

### Device information

Manufacturer: 
Model name: 
Node ID in your network: 
GE/Jasco
Model #14318
Node ID: 7

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
Driver Version: 8.1.1
Server Version: 1.10.0

### Did you change anything?

no

### If yes, what did you change?

_No response_

### Did this work before?

Yes (please describe)

### If yes, where did it work?

I have just switched over from a hybrid solution.  I was running Homeseer and the mcsMQTT plugin.  Then I had Home Assistant running the Mosquitto MQTT add-on.  I configured all of my Zwave Devices to subscribe and post to topics in the broker going in both directions.  I decided to get rid of Homeseer and MQTT and go with the ZwaveJS add on.  

When these switches (1 have 3 of the them and they all exhibit the same behavior in HA) were included and operated in Homeseer with their Zwave implementation they updated instantly upon operation whether manually or by Homeseer.  So yes it worked and updated instantly but with Homeseer's Zwave implementation.  It works in HA but again when manually operated it doesn't update the UI.

When I was running it through the MQTT broker:
Homeseer -> mcsMQTT -> Mosquitto Broker -. Home Assistant it also updated instantly in HA.

### Attach Driver Logfile

[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/7108189/zwave_js.1.log)

### PR DESCRIPTION
**Pull request by blhoward2**
Closes #3273

### CODE REVIEW

**Comment by blhoward2** [comment]
@zwave-js-bot fix lint

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
Before we merge, @cfrudolphy could you test this file?

=> https://zwave-js.github.io/zwavejs2mqtt/#/development/intro?id=testing-custom-devices-config
use this file: https://raw.githubusercontent.com/zwave-js/node-zwave-js/blhoward2-patch-1/packages/config/config/devices/0x0063/jasco_14318.json
and re-interview your device.

**Comment by crudolphy** [comment]
@alcalzone,  I will be happy to test.  However I am using the following 
system:

1.) Home Assistant OS installation on a RPI4b+.  Includes Supervisor.  
All the most recent editions.

2.) ZwaveJS add on not the ZwaveJS2MQTT add on.

3.) This is my production system.  I have another RPI4b+ that I could 
install and then restore a snapshot to, giving me a "Test" system.

4.) Regardless you are going to have to tell me where to place that file 
within the system.


The more I think about this it may be better for me to create that 
system extra system.  May get started on that in just a little bit.

Regards

Chuck

**Comment by AlCalzone** [comment]
@cfrudolphy I'm not sure if this is possible without Zwavejs2mqtt. Maybe it's easier for us to just merge the change and you to test it after the next upgrade?

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
