### PR TITLE
feat: support learn mode

### LINKED ISSUE #6428: Support Learn Mode to become a secondary controller
### Discussed in https://github.com/zwave-js/node-zwave-js/discussions/6427

<div type='discussions-op-text'>

<sup>Originally posted by **@thomaswitt** October 19, 2023</sup>
### Description

I bought an Aeotec Z-Stick 7 for my RPi 4 and hoped it could be used as a secondary controller for my Homey Pro system (as the Homey Aeotec App supports the Z-Stick Gen 5 officially). There's even some [official documentation](https://aeotec.freshdesk.com/support/solutions/articles/6000263528-z-stick-gen-5-as-secondary-controller-in-homey) on the Aeotec page for that. I wanted to gain three functionalities by using Z-Wave JS UI with that:

1. Seamless MQTT integration - so that all actions of all my devices can be broadcasted to my MQTT broker.
2. Firmware Updates for Z Wave Devices (as Homey doesn't support Firmware Updates)
3. Getting easy API access to send commands to Z Wave Devices (e.g. turning on/off a light via an API call easily)

Unfortunately, Z-Wave JS UI - as I understand - doesn't support learn mode at the moment and therefore I can't include it as a device/secondary controller in my existing network.

### Do you have a solution in mind?

I would suggest to add support for Z-Wave UI JS for being a secondary controller.

### Describe alternatives you've considered

There are non as I don't want to drop Homey as my primary system.

### Additional context

_No response_</div>

### PR DESCRIPTION
**Pull request by AlCalzone**
This PR adds support for joining another network using S2 and S0 and being a secondary controller

fixes: #6428

enables https://github.com/zwave-js/node-zwave-js/issues/7096
enables #1070

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot automerge

**Comment by iskiselev** [comment]
Should FAQ be also updated now? https://github.com/zwave-js/node-zwave-js/blob/master/docs/getting-started/faq.md or is it still considered "Not supported"?

**Comment by AlCalzone** [comment]
It's not fully supported yet - the other half of the Inclusion Controller CC implementation is missing. But I guess it's good enough to update the FAQ.

**Comment by brandond** [comment]
Does this mean I can run a second instance of zwave-js-ui elsewhere in my environment, with another stick. and join it to the network as a range extender? It's not clear from the docs how to get it to join an existing network on startup.

**Comment by AlCalzone** [comment]
No, a secondary controller does not have the same functionality as the primary. For example with some devices you can not have them report to more than one controller.

What you may be thinking of (multiple instances cooperating) would require some backend work. It may come one day, but no guarantees.

**Comment by brandond** [comment]
Right but even if I didn't want to have it report to the secondary controller, or do any management from that node, could I at least get it as far as joining the network to extend the range of the mesh? I'm confused as to what the current limited support actually allows for.

**Comment by AlCalzone** [comment]
I don't think there's support for this in Z-Wave JS UI yet.

> I'm confused as to what the current limited support actually allows for.

Mainly in preparation for https://github.com/zwave-js/node-zwave-js/issues/7096

/cc @robertsLando

**Comment by robertsLando** [comment]
No support in UI yet but you could still try using it with driver function

**Comment by brandond** [comment]
Do you have any pointers on how to do that? I'm assuming I'd need to run the driver headless and pass it the keys and such?

**Comment by robertsLando** [comment]
@brandond Never tried those new APIs so I have no clue but if you want to understand how to work with custom driver functions you can look at docs here: https://zwave-js.github.io/zwave-js-ui/#/usage/driver_function

**Comment by 37Rb** [comment]
I'm interested in experimenting with this as well. I'm using the [Node-RED Z-Wave JS](https://flows.nodered.org/node/node-red-contrib-zwave-js) package. I don't expect to be able to do it from there but can I use learn mode via code in the driver used by Node-RED and then use the UI after it's included?

**Comment by AlCalzone** [comment]
@37Rb what do you expect to do when Z-Wave JS is a secondary controller?
Right now it "works", but it probably does not behave as expected - i.e. no automatic device interview and when you trigger it manually, it will assign a wrong lifeline association.

**Comment by 37Rb** [comment]
I'm trying to discover what's possible to do. I want to add a z-stick (Zooz ZST39 LR) to an existing network and use Node-RED to do as much as possible with it. The goal is to enhance the existing network to do automations that aren't possible due to limitations on the primary controller. I want to add Z-Wave to [this tool](https://support.suretyhome.com/t/surety-iq-mate/32721) and see how much mileage I can get.

**Comment by marcus-j-davies** [comment]
@37Rb 

if you’re willing to todo some testing - I can start the ground work in the NR module?

It can then be done in the UI

**Comment by 37Rb** [comment]
I'm happy to do testing on it. That would be easier than trying to modify the driver instance myself!

**Comment by marcus-j-davies** [comment]
I'll ping you when something is ready to test.

**Pull request merged**
