### PR TITLE
chore(config): check if param description contains unnecessary stuff

### PR DESCRIPTION
**Pull request by AlCalzone**
@robertsLando Like we talked about. This found a ton of warnings - I could use some help here:
```Found 0 errors and 470 warnings!```

@blhoward2 do you have a script to clean the descriptions?

### CODE REVIEW

**Comment by blhoward2** [comment]
Essentially. I have a function setup to parse over all the files and write it back. Changing what it does in the middle is just a few lines. I've been using it to fix things as I go, or like when I rewrote the metadata. 

What needs cleaned?

**Comment by robertsLando** [comment]
Indentation in descriptions, check if description contains default/min/max and remove that too

**Comment by AlCalzone** [comment]
If you now run the lint script locally you'll see about 470 warnings. Those need fixing.

**Comment by blhoward2** [comment]
I'll take a look.

**Comment by robertsLando** [comment]
Love new lint config :heart_eyes:

**Comment by AlCalzone** [comment]
Since there's an influx of new contributors, this should be merged ASAP - will update the branch.

**Comment by blhoward2** [comment]
FYI I started working on pulling out the similar descriptions. I already went and hand jammed the ones that require changes to the label or unit...I just need to figure out why iterating the parameters in the file isn't working. Once I solve that tonight it should be ready to push.

**Pull request merged**
