### PR TITLE
feat(config): modify UltraPro 700 Z-Wave Switch

### LINKED ISSUE #6578: UltraPro 700 Series Z-Wave In-Wall Smart Light Switch missing
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

UltraPro Zwave 700 series in-wall light switch

### Manufacturer ID

0x0063

### Product Type

0x4952

### Product ID

0x3333

### Firmware Version

1.22.2

### Is the device listed on the Z-Wave Alliance website?

[Yes](https://products.z-wavealliance.org/products/4569?selectedFrequencyId=2)

### Do you have a manual?
Copy paste debug info from z-wave js.

  "hexId": "0x0063 0x4952-0x3333",
  "dbLink": "https://devices.zwave-js.io/?jumpTo=0x0063:0x4952:0x3333:1.22.2",
  "manufacturerId": 99,
  "productId": 13107,
  "productType": 18770,
  "productLabel": "Unknown product 0x3333",
  "productDescription": "0x4952",
  "manufacturer": "GE/Jasco",
  "firmwareVersion": "1.22.2",
  "sdkVersion": "7.15.4",
  "protocolVersion": 3,
  "zwavePlusVersion": 2,
  "zwavePlusNodeType": 0,
  "zwavePlusRoleType": 5,

Included Manual shows the following models on the cover:  59347, 59370, 59371, ZWA4011.  The manual does NOT list details of the z-wave parameters.  I found this manual that lists only ZWA4011 (and 58433?).  It appears the same other than "UltraPro" is swapped for "Enbrighten" on the cover, and "59347" is swapped for "58433" throughout.

https://byjasco.com/mwdownloads/download/link/id/3542

The switch has a multi-color LED. For parameter: 112-0-34 LED Light Color
The following values were tested.

0 (no change / does nothing)
1 red
2 orange
3 yellow
4 green
5 blue (default)
6 pink
7 purple
8 white

Purchase Link at Amazon
https://www.amazon.com/dp/B0BRDJJ5ZN?psc=1&ref=ppx_yo2ov_dt_b_product_details

The QR code on the manual's cover takes you to this YT video for model 46563?
https://www.youtube.com/watch?v=cNR8Kmd9_JE

### PR DESCRIPTION
**Pull request by apella12**
PR description here:
Added parameters and groups to paddle switch stub item 58433_59344_zw4011.json Merging will close #6578

### CODE REVIEW

**Comment by AlCalzone** [comment]
@jascoproducts, can you please review this?

**Comment by apella12** [comment]
To @jascoproducts
In addition to the PR review, it would be very helpful for us (and therefore your customers) to have some sort of table of product TYPE:ID pairs and their parameters and association groups. For instance there are several "stubs" for your products (0x0063) without that information.  Examples (there are several more):
```
{
	"manufacturer": "Enbrighten",
	"manufacturerId": "0x0063",
	"label": "58436 / 59334 / ZWA4012",
	"description": "In-Wall Toggle Switch, QFSW, 700S",
	"devices": [
		{
			"productType": "0x4952",
			"productId": "0x3330"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	}
	// TODO: Add configuration parameters
}
```
```
{
	"manufacturer": "Enbrighten",
	"manufacturerId": "0x0063",
	"label": "59335 / 59341 / ZWA3017",
	"description": "In-Wall Toggle Dimmer, QFSW, 700S",
	"devices": [
		{
			"productType": "0x4944",
			"productId": "0x3431"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	}
	// TODO: Add configuration parameters
}
```
```
{
	"manufacturer": "Enbrighten",
	"manufacturerId": "0x0063",
	"label": "59337 / ZWA4011DV",
	"description": "In-Wall Paddle Switch, 120+277, QFSW, 700S",
	"devices": [
		{
			"productType": "0x4952",
			"productId": "0x3331"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	}
	// TODO: Add configuration parameters
}
```

That way when your customer gets a shiny new device, it will be picked up by Zwave JS and HAss upon inclusion.

Also note that the "stub" for this PR did not include the customer reported Type:ID, so as these are added/changed and the parameters and groups remain the same it would be good to have those too.

Thanks in advance.

**Comment by apella12** [comment]
Messed this up trying to rebase

**Comment by AlCalzone** [comment]
I often don't bother rebasing anymore, unless it's really clean. Just merge the master branch.

**Comment by AlCalzone** [comment]
You should be able to save this with a cherry pick of the relevant commit(s).

**Comment by apella12** [comment]
I have one more old one, but I'll just leave it.  Recreated this #6726.  Sorry, I struggle with github.

**Pull request closed without merging**
