### PR TITLE
fix(config): correct and normalize line-breaks in Z-Wave Alliance metadata imports

### PR DESCRIPTION
**Pull request by blhoward2**
Correct metadata with the following:
Changes \n\r to \n\n.
Changes \r to \n.
Leaves \n\n.
Leaves \n.
Removes \t.

In support of #1349 .

@marcus-j-davies Take a look. Thoughts?

### CODE REVIEW

**Comment by blhoward2** [comment]
@zwave-js-bot fix lint

**Comment by AlCalzone** [comment]
> Changes \n\r to \n\n.

Eh, I figure it is too late now, but `\r\n` should just be `\n` (both are a single line ending)

**Comment by blhoward2** [comment]
I can rerun it then. It only takes a minute.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Didn't see everything yet, but there are a few things that are weird.

**Comment by blhoward2** [comment]
They had a newline there. We’ll have to proofread each one to catch that...

**Comment by AlCalzone** [comment]
Oh, so you completely filtered them out before this PR? Then the diffs make sense. I'm okay with leaving it like this for now.

**Review by AlCalzone — DISMISSED** [review]

**Comment by blhoward2** [comment]
I started anew. I parsed the device files, collected the zwa ID numbers, then re-pull the longest version of each for each file, then did the regex on the line.

**Comment by AlCalzone** [comment]
Alright. Then let's leave it like it is now. Let me know when this is ready to merge.

**Comment by blhoward2** [comment]
I’ll rerun it in a bit to change the \r\n

**Comment by blhoward2** [comment]
@zwave-js-bot fix lint

**Comment by blhoward2** [comment]
It's only about 80 files that likely have in-line breaks. I'll take a look at them later tonight.

**Comment by blhoward2** [comment]
@AlCalzone This is as good as I'm going to get them.

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
