### PR TITLE
feat(config): add all zwa approved yale locks

### LINKED ISSUE #5114: Missing device configuration: Yale YRL256 (using AYR-MOD-ZW3, 700 series module)
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Yale YRL256 (using AYR-MOD-ZW3, 700 series module)

### Manufacturer ID

0x129

### Product Type

0x800c

### Product ID

0x4f00

### Firmware Version

2.17.0

### Is the device listed on the Z-Wave Alliance website?

_No response_

### Do you have a manual?

It is the same at the YRD256-ZW3 for the most part. They utilize the same z-wave module underneath.

### LINKED ISSUE #5144: Missing device configuration: <enter manufacturer and device name>
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Yale Assure Lock 2

### Manufacturer ID

297

### Product Type

33028

### Product ID

0x8104

### Firmware Version

1.78

### Is the device listed on the Z-Wave Alliance website?

YES

### Do you have a manual?

[400 series Keyed.pdf](https://github.com/zwave-js/node-zwave-js/files/9724376/400.series.Keyed.pdf)

### PR DESCRIPTION
**Pull request by blhoward2**
This PR now merges in all Yale locks with an entry in the ZWA database.

Closes #5144
Closes #5114

### CODE REVIEW

**Comment by blhoward2** [comment]
Ah, bot. Thou art a cold heartless bitch.

**Comment by robertsLando** [comment]
Let me know if you need to merge this :)

**Comment by AlCalzone** [comment]
Good bot.
@blhoward2 FYI you can check the files locally using
```
yarn lint:configjson
```
for formatting and
```
yarn lint:zwave
```
for semantic errors.

Might save you some precious time.

**Comment by blhoward2** [comment]
I know. I kept thinking I had it all. Lol. I'm going to merge in a few more Yale locks I think to close a couple more issues.

**Comment by blhoward2** [comment]
@AlCalzone @robertsLando This should be ready now. I've merged in every Yale lock in the ZWA database and templated them. There are technically two more, but they are missing productType's so I cannot merge them.

**Review by robertsLando — APPROVED** [review]
LGTM. Let's see if @AlCalzone agrees :)

**Comment by tamorgen** [comment]
Has this been published yet?  How would I update my locks if/when it has been published?

**Comment by robertsLando** [comment]
Not published yet, just reinterview your locks when it will be

**Comment by robertsLando** [comment]
@blhoward2 Good to merge so?

**Comment by blhoward2** [comment]
Yes, good to merge.

**Comment by tamorgen** [comment]
I'm still unable to update my locks.  They still show up as Assa Abloy (manufacturer), Unknown Product.

I've tried reinterviewing the node, but nothing changes.  Am I missing a step?

**Comment by blhoward2** [comment]
> I'm still unable to update my locks. They still show up as Assa Abloy (manufacturer), Unknown Product.
> 
> I've tried reinterviewing the node, but nothing changes. Am I missing a step?

You’ve upgraded to a version of zwavejs that includes this device file, right? What does the UI show for the product type and product id?

**Comment by tamorgen** [comment]
This is what I'm running.  I've tried checking for updates, and it appears to stay at this version

zwave-js-ui: 8.4.1
zwave-js: 10.3.0
home id: 4133703301
home hex: 0xf6634e85


Product 0x8104
Unknown Product 0x05d2

**Comment by blhoward2** [comment]
That’s too old. This device file first appears in zwavejs-ui version 8.5.0, zwavejs version 10.3.1. 8.5.1 is the latest.

**Comment by blhoward2** [comment]
You’d also need to go through the files and ensure that device fingerprint appears in the correct file. We may need to add it.

**Comment by tamorgen** [comment]
I have auto update enabled in HACS for Z-Wave JS UI.   Is there another way to update?

**Comment by tamorgen** [comment]
> You’d also need to go through the files and ensure that device fingerprint appears in the correct file. We may need to add it.

I had opened an issue on this a couple months ago.   That issue was closed saying the integration would be merged into this, so all the information for my lock should be part of it.

https://github.com/zwave-js/node-zwave-js/issues/5144

**Comment by tamorgen** [comment]
> That’s too old. This device file first appears in zwavejs-ui version 8.5.0, zwavejs version 10.3.1. 8.5.1 is the latest.

It looks like 1.3.0 is the latest on the HACS add-on (26 days ago)

https://github.com/hassio-addons/addon-zwave-js-ui 

It says 8.4.1 is the version it'll update it to.

https://github.com/hassio-addons/addon-zwave-js-ui/releases/tag/v1.3.0

Looks like the hassio-addons needs to be updated.

**Comment by blhoward2** [comment]
Looks like it. That’s outside our control.

**Comment by tamorgen** [comment]
> Looks like it. That’s outside our control.

Is there an alternative / manual way to update?

**Comment by tamorgen** [comment]
> Looks like it. That’s outside our control.

And who controls that?  I'm confused.  The Config updates button doesn't seem to update the application.  I opened an issue the app "owner" as shown on the hassio-addons /addon-zwave-js-ui page, and he immediately closed it, saying "HACS doesn't provide addons", and "Update of device databases are not related to add-on UI updates"

https://github.com/hassio-addons/addon-zwave-js-ui/issues/447

I'm getting frustrated here, trying to understand what I need to do to stay up to date.  As far as I can tell, all my other HA add ons update automatically when that option is checked.

**Comment by blhoward2** [comment]
@frenck controls the addons. 

@frenck Could you please bump the zwave-js-ui addon when you get a chance?

**Pull request merged**
