### PR TITLE
feat(config): added Wave devices 

### PR DESCRIPTION
**Pull request by QubinoHelp**
added Wave devices i4, i4DC, Plug UK, Plug US, PRO 1, PRO 2, PRO 2, PRO 2PM
added wave_template

### CODE REVIEW

**Comment by AlCalzone** [comment]
Thanks for this. I'll try to look at this when I find some time, as I'm currently on parental leave.

**Comment by apella12** [comment]
Not the official reviewer, but it looks like the lint-zwave errors are from not using the lower case hex (i.e. 008a, not 008A, etc.) in five files.

Also three files (001x16, 0a1p16, and 0a1x16) are duplicates? (same TYPE:ID and all versions) that could be a problem.  Might want to check or combine into one with all the labels

**Comment by QubinoHelp** [comment]
@apella12 
Thank you for the review, I will check the files and fix the issues you mentioned.

**Comment by QubinoHelp** [comment]
There was mistakes, will make a new pull request. Closing this one.

**Pull request closed without merging**
