### PR TITLE
ci: add tests for auto-generated docs, create auto-update action

### PR DESCRIPTION
**Pull request by AlCalzone**

### CODE REVIEW

**Comment by robertsLando** [comment]
@AlCalzone What about also push changes if the test is successfull?

**Comment by AlCalzone** [comment]
next step :)

**Comment by AlCalzone** [comment]
Wonder how many iterations this auto-update action is going to take... I can't get `act` to work locally.

**Comment by robertsLando** [comment]
What iterations do you mean?

**Comment by AlCalzone** [comment]
These:
grafik

**Comment by AlCalzone** [comment]
15..., it took 15...😖

But now it works 🎉

**Comment by robertsLando** [comment]
> 15..., it took 15...confounded

Not bad :laughing: 

> But now it works :tada: 

That's what really matter :rocket:

**Pull request merged**
