### PR TITLE
fix(config): add missing LED Light param to GE/Jasco 46202 and 14292

### LINKED ISSUE #2998: GE Jasco 46202 missing parameter to configure LED behavior
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

I have a bunch of GE/Jasco switches. One of them is a dimmer:
https://github.com/zwave-js/node-zwave-js/blob/5539dd48f967e74f8afe131dd896f952269e42c1/packages/config/config/devices/0x0063/14295_46204_zw3011.json#L34

That dimmer lets me configure the LED behavior in the UI because of parameter 3. I also have some switches, the GE Jasco 46202:

https://github.com/zwave-js/node-zwave-js/blob/5539dd48f967e74f8afe131dd896f952269e42c1/packages/config/config/devices/0x0063/46202.json

These allow me to “Invert Switch” in the Home Assistant UI but not set the “LED Light” behavior. I’m guessing because the second device config doesn’t have parameter 3 defined. I can see the device supports it because when I interrogate it I get this in the log:
```
2021-07-09T21:51:41.564Z CNTRLR « [Node 021] received information for parameter #3:
                                  parameter name:      LED Light
                                  value format:        SignedInteger
                                  value size:          1 bytes
                                  min value:           0
                                  max value:           3
                                  default value:       2
                                  is read-only:        false
                                  is advanced (UI):    false
                                  has bulk support:    false
                                  alters capabilities: false
```

What do you observe?
I can configure the LED Behavior on my GE/Jasco 14295 / 46204 / ZW3011 but not on my GE Jasco 46202

What did you expect to happen?
LED Behavior is configurable in the Home Assistant UI.

  2. Click on '...'
  3. Scroll down to '...'

### Device information

Manufacturer: GE/JASCO
Model name: 46202
Node ID in your network: 8, 20, 21

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 
Home Assistant core-2021.7.0, 
Z-Wave JS: 0.1.28
`node-zwave-js` branch:
`zwavejs2mqtt` branch:

### Did you change anything?

no

### If yes, what did you change?

_No response_

### Did this work before?

No, it never worked anywhere

### If yes, where did it work?

_No response_

### Attach Driver Logfile

```2021-07-10T16:29:45.110Z CNTRLR   [Node 008]   skipping query for All Switch (0x27) because max implemented vers
                                  ion is 0
2021-07-10T16:29:45.111Z CNTRLR » [Node 008]   querying the CC version for Z-Wave Plus Info...
2021-07-10T16:29:45.190Z CNTRLR   [Node 008]   supports CC Z-Wave Plus Info (0x5e) in version 2
2021-07-10T16:29:45.191Z CNTRLR » [Node 008]   querying the CC version for Association...
2021-07-10T16:29:45.240Z CNTRLR   [Node 008]   supports CC Association (0x85) in version 2
2021-07-10T16:29:45.240Z CNTRLR » [Node 008]   querying the CC version for Association Group Information...
2021-07-10T16:29:45.286Z CNTRLR   [Node 008]   supports CC Association Group Information (0x59) in version 1
2021-07-10T16:29:45.287Z CNTRLR » [Node 008]   querying the CC version for Manufacturer Specific...
2021-07-10T16:29:45.333Z CNTRLR   [Node 008]   supports CC Manufacturer Specific (0x72) in version 2
2021-07-10T16:29:45.334Z CNTRLR   [Node 008]   skipping query for Transport Service (0x55) because max implement
                                  ed version is 0
2021-07-10T16:29:45.335Z CNTRLR   [Node 008]   skipping query for Device Reset Locally (0x5a) because max implem
                                  ented version is 1
2021-07-10T16:29:45.337Z CNTRLR   [Node 008]   skipping query for Powerlevel (0x73) because max implemented vers
                                  ion is 0
2021-07-10T16:29:45.338Z CNTRLR » [Node 008]   querying the CC version for Central Scene...
2021-07-10T16:29:45.386Z CNTRLR   [Node 008]   supports CC Central Scene (0x5b) in version 3
2021-07-10T16:29:45.387Z CNTRLR   [Node 008]   skipping query for Security 2 (0x9f) because max implemented vers
                                  ion is 0
2021-07-10T16:29:45.389Z CNTRLR   [Node 008]   skipping query for Supervision (0x6c) because max implemented ver
                                  sion is 1
2021-07-10T16:29:45.390Z CNTRLR » [Node 008]   querying the CC version for Configuration...
2021-07-10T16:29:45.445Z CNTRLR   [Node 008]   supports CC Configuration (0x70) in version 4
2021-07-10T16:29:45.446Z CNTRLR   [Node 008]   skipping query for Scene Actuator Configuration (0x2c) because ma
                                  x implemented version is 1
2021-07-10T16:29:45.446Z CNTRLR   [Node 008]   skipping query for Scene Activation (0x2b) because max implemente
                                  d version is 1
2021-07-10T16:29:45.447Z CNTRLR   [Node 008]   skipping query for Application Status (0x22) because max implemen
                                  ted version is 0
2021-07-10T16:29:45.447Z CNTRLR » [Node 008]   querying the CC version for Firmware Update Meta Data...
2021-07-10T16:29:45.492Z CNTRLR   [Node 008]   supports CC Firmware Update Meta Data (0x7a) in version 4
2021-07-10T16:29:45.493Z CNTRLR » [Node 008] querying if Z-Wave Software Get is supported...
2021-07-10T16:29:45.540Z CNTRLR « [Node 008] Z-Wave Software Get is supported
2021-07-10T16:29:45.541Z CNTRLR » [Node 008] querying Z-Wave software versions...
2021-07-10T16:29:45.603Z CNTRLR « [Node 008] received Z-Wave software versions
2021-07-10T16:29:45.633Z CNTRLR   [Node 008] Embedded device config loaded
2021-07-10T16:29:45.641Z CNTRLR   [Node 008] Interviewing Z-Wave Plus Info...
2021-07-10T16:29:45.642Z CNTRLR » [Node 008] querying Z-Wave+ information...
2021-07-10T16:29:45.696Z CNTRLR « [Node 008] received response for Z-Wave+ information:
                                  Z-Wave+ version: 1
                                  role type:       AlwaysOnSlave
                                  node type:       Node
                                  installer icon:  0x0704
                                  user icon:       0x0700
2021-07-10T16:29:45.699Z CNTRLR   [Node 008] Interviewing Basic...
2021-07-10T16:29:45.701Z CNTRLR » [Node 008] querying Basic CC state...
2021-07-10T16:29:45.748Z CNTRLR « [Node 008] received Basic CC state:
                                  current value:      99
2021-07-10T16:29:45.754Z CNTRLR   [Node 008] Interviewing Binary Switch...
2021-07-10T16:29:45.757Z CNTRLR » [Node 008] querying Binary Switch state...
2021-07-10T16:29:45.840Z CNTRLR « [Node 008] received Binary Switch state:
                                  current value:      true
                                  target value:       true
                                  remaining duration: 0s
2021-07-10T16:29:45.854Z CNTRLR   [Node 008] Interviewing Configuration...
2021-07-10T16:29:45.854Z CNTRLR   [Node 008] ConfigurationCC: Loading configuration parameters from device confi
                                  g
2021-07-10T16:29:45.859Z CNTRLR » [Node 008] finding first configuration parameter...
2021-07-10T16:29:45.908Z CNTRLR » [Node 008] querying parameter #3 information...
2021-07-10T16:29:46.329Z CNTRLR « [Node 008] received information for parameter #3:
                                  parameter name:      LED Light
                                  value format:        SignedInteger
                                  value size:          1 bytes
                                  min value:           0
                                  max value:           3
                                  default value:       2
                                  is read-only:        false
                                  is advanced (UI):    false
                                  has bulk support:    false
                                  alters capabilities: false
2021-07-10T16:29:46.330Z CNTRLR » [Node 008] querying parameter #4 information...
2021-07-10T16:29:46.883Z CNTRLR « [Node 008] received information for parameter #4:
                                  parameter name:      Invert Switch
                                  value format:        SignedInteger
                                  value size:          1 bytes
                                  min value:           0
                                  max value:           1
                                  default value:       0
                                  is read-only:        false
                                  is advanced (UI):    false
                                  has bulk support:    false
                                  alters capabilities: false
2021-07-10T16:29:46.884Z CNTRLR » [Node 008] querying parameter #19 information...
2021-07-10T16:29:47.700Z CNTRLR « [Node 008] received information for parameter #19:
                                  parameter name:      Alternate Exclusion
                                  value format:        SignedInteger
                                  value size:          1 bytes
                                  min value:           0
                                  max value:           1
                                  default value:       0
                                  is read-only:        false
                                  is advanced (UI):    false
                                  has bulk support:    false
                                  alters capabilities: false
2021-07-10T16:29:47.706Z CNTRLR » [Node 008] querying parameter #4 value...
2021-07-10T16:29:47.771Z CNTRLR   [Node 008] Interviewing Association...
2021-07-10T16:29:47.771Z CNTRLR » [Node 008] querying number of association groups...
2021-07-10T16:29:47.817Z CNTRLR « [Node 008] supports 3 association groups```

### PR DESCRIPTION
**Pull request by disforw**
Add LED param for 46202

Closes #2998

### CODE REVIEW

**Comment by disforw** [comment]
Closes #2998

**Review by AlCalzone — APPROVED** [review]
LGTM

**Comment by AlCalzone** [comment]
@blhoward2 anything to add, since you were involved in that issue?

**Comment by AlCalzone** [comment]
Waiting for verification in https://github.com/zwave-js/node-zwave-js/issues/2998

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
