### PR TITLE
fix(config): remove Supervision support for GE 14287 / ZW4002

### LINKED ISSUE #1982: GE 14287 Fan Switch Multilevel switch command not working
**Describe the bug**
GE 14287 Fan switch is not responding to multilevel switch commands sent from zwavejs2mqtt control panel. Sending a Basic command does work.

**Device information**
GE 14287 Fan Switch
Firmware: 5.24
NodeId: 8

**Did you change anything?**
- [ ] **Yes**: *(please describe)*
- [x] **No**

**Did this use to work before?**
- [x] **Don't know**, Dont know if this have ever working in zwave-js however this device worked in OpenZwave
- [ ] **No**, it never worked anywhere
- [ ] **Yes**, in: *(specify application with versions)*
    
**How are you using `node-zwave-js`**
App version: 2.1.0 
Zwavejs Version 6.6.0
Zwavejs-server version 1.1.0
- [x] `zwavejs2mqtt` (latest) docker image 
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] `zwavejs2mqtt` Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] ioBroker.zwave2 adapter
- [ ] `HomeAssistant` version XYZ
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**

1. Go to zwavejs2mqtt control panel
2. Click on fan switch node and then multilevel switch under values section
3. Set target value to 255 and send cmd
4. Device never turns on and a timeout message appears in the logs

**Additional context**

For comparison I have a working OpenZwave serial command and was able to compare the two.

OpenZwave command: SwitchMultilevelCmd_Set (Node=8): 0x01, 0x0a, 0x00, 0x13, 0x08, 0x03, 0x26, 0x01, 0xff, 0x25, 0x2b, 0x3b

Zwave-js command: 0x01 0e 00 13 08 07 6c 01 9d 03 26 01 ff 25 28 cb

Zwave-js seems to be sending the command as a Supervision get compared to OpenZwave just sending the MultiLevel set command. This specific switch does not support the supervision command as can be seen in interview log file attached and from https://products.z-wavealliance.org/products/2506/classes.

**Logfile:**
[node8_interview.log](https://github.com/zwave-js/node-zwave-js/files/6071025/node8_interview.log)
[multiLevelSet_timeout.log](https://github.com/zwave-js/node-zwave-js/files/6071027/multiLevelSet_timeout.log)

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #1982

### CODE REVIEW

**Comment by AlCalzone** [comment]
@blhoward2, master of configs. This works - but I suspect we're gonna need this for other GE devices aswell.

**Comment by blhoward2** [comment]
It’s odd that this just came up, as some of the people with issues said it had been working. What changed? Any idea of how we know which need this?

**Comment by AlCalzone** [comment]
The logs in https://github.com/zwave-js/node-zwave-js/issues/1982 are a good indicator. Device does not report Supervision CC, zwave-js still uses it (because the device class says it is mandatory). Supervision encapsulated Multilevel Switch Set times out.

**Comment by blhoward2** [comment]
Yeah, but I just did a level change up on mine and it worked fine. I’m a few versions behind master, though. Did we change something in that regard?

**Comment by AlCalzone** [comment]
No change. Do you have a log, maybe a different firmware?

**Comment by kpine** [comment]
> No change. Do you have a log, maybe a different firmware?

You actually did make a change somewhat recently, https://github.com/zwave-js/node-zwave-js/pull/1694. Prior to that, Fan devices and a number of other types did not define any supported CCs. That PR was introduced in 6.3.0. Someone just starting to use zwave-js now would see different behavior than prior to 6.3.0.

> 
> 
> Yeah, but I just did a level change up on mine and it worked fine. I’m a few versions behind master, though. Did we change something in that regard?

Do you have the same 14287 fan controller, or are you referring to other GE devices? If the former, what happens if you re-interview it? Maybe it was interviewed prior to the changes mentioned above, so it doesn't include the Supervisor CC?

**Comment by blhoward2** [comment]
Same but I haven’t reinterviewed since 6.3.0. I already sent him the cache file. I have a range of these devices so I’m going to do some further testing to see if it’s a wider issue on other GE devices.

**Comment by AlCalzone** [comment]
> That PR was introduced in 6.3.0.

3 minor versions back, that's ancient history 😅
I didn't think that far until I saw @blhoward2's cache.

**Comment by blhoward2** [comment]
Confirmed that the Supervision CC is added and also times out on a Honeywell 39358, and I see this behavior on a GE 14287 after re-interviewing. (These two share the zw4002 hardware, so this isn't surprising.) Others built on the zw4002 include the GE 10974, 12730, 14314, 55258, 55259. I'm going to push additions to all of those.

Tested on others, which seem fine:

14291 (binary switch) - Supervision doesn't get added -- works
14294 (dimmer) - Supervision doesn't get added -- works
46201 (binary switch) - Supervision added but it works without compat
46203 (dimmer) - Supervision added but it works without compat

I also renamed the file for the 14287 for consistency.

**Review by blhoward2 — APPROVED** [review]

**Comment by AlCalzone** [comment]
Thanks!

**Comment by thegame3202** [comment]
For some reason this file didn't update for me on the latest version of "master": packages/config/config/devices/0x0063/zw4002.json 

I have a 14287 switch that wasn't working with HomeAssistant, and manually making the change to that file fixed it. But looking at commits, it looks like that file was supposed to be removed? I manually deleted it, and it seems to redownload and break again.

EDIT: Just realized I'm not posting in zwavejs-mqtt, which is the Docker container I'm using. That must be the difference.

**Comment by blhoward2** [comment]
If you pull the docker image it’s built off the numbered release of node and this won’t be there yet. You can follow the instructions in the documentation to build your own off both masters which would get you both now. The master tagged docker image may also pull this in nightly but I don’t know.

**Comment by thegame3202** [comment]
> If you pull the docker image it’s built off the numbered release of node and this won’t be there yet. You can follow the instructions in the documentation to build your own off both masters which would get you both now. The master tagged docker image may also pull this in nightly but I don’t know.

Awesome, thanks! I'll just modify the file for the time being. The only other thing I've noticed is when I flip the fan switch "on" in HomeAssistant, it turns the actual fan on. But the switch in the GUI turns on, then off, then back on again. Anyone else's doing that as well?

**Comment by cweakland** [comment]
> 
> 
> > If you pull the docker image it’s built off the numbered release of node and this won’t be there yet. You can follow the instructions in the documentation to build your own off both masters which would get you both now. The master tagged docker image may also pull this in nightly but I don’t know.
> 
> Awesome, thanks! I'll just modify the file for the time being. The only other thing I've noticed is when I flip the fan switch "on" in HomeAssistant, it turns the actual fan on. But the switch in the GUI turns on, then off, then back on again. Anyone else's doing that as well?

I see this exact behavior, which is not all that bothersome, however, when I turn the device off I have to hit it twice.  

Edit found a work around, posted it here: https://community.home-assistant.io/t/ge-enbrighten-fan-controller-incorrectly-reporting-on-off-state/334036/8

**Pull request merged**
