### PR TITLE
feat(config): add fingerprint 0x8109-0x4dd5 to Yale YRD-256-ZW3

### LINKED ISSUE #5603: Missing device configuration: <ZW3 module for YRD256 (Yale Lock)>
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

YRD256 ZW3 is in database, but this particular device ID is missing from existing range

### Manufacturer ID

0x0129

### Product Type

0x4dd5

### Product ID

0x8109

### Firmware Version

2.17.0

### Is the device listed on the Z-Wave Alliance website?

_No response_

### Do you have a manual?

This is a YRD256 device for which a config file already exists; this device ID (new Yale ZW3 module) is just not recognized within that range.

### PR DESCRIPTION
**Pull request by MistyMoose**
Updated YRD-256 config with additional fingerprints for YRD-256-ZW3

fixes: https://github.com/zwave-js/node-zwave-js/issues/5603

### CODE REVIEW

**Review by AlCalzone — APPROVED** [review]
Thanks, I did a small correction - this way it is okay.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Oh wait - which is it? In the issue you say 0x8109 is the product ID, here it is the other way round.

**Comment by MistyMoose** [comment]
Thank you. The issue is incorrect, the pull is correct. I’ve tested locally and works as expected. Sent from my iPhoneOn Apr 4, 2023, at 16:39, AlCalzone ***@***.***> wrote:﻿
@AlCalzone requested changes on this pull request.

Oh wait - which is it? In the issue you say 0x8109 is the product ID, here it is the other way round.

**Comment by AlCalzone** [comment]
Thanks for clarifying

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
