### PR TITLE
fix(config): add configuration for iblinds V3.10

### LINKED ISSUE #2663: New param for iblinds v3.06
**Which device is missing?**
N/A on device missing, there is a new parameter added with v3.06 of the firmware:
"New Z-Wave Parameter #7 added for remote calibration start. Sending a value of 1 to Z-Wave Parameter 7 will immediately start the Calibration Routine. (size = 1)"

Enter Manufacturer and Device name here
iblinds v3

**What are the IDs?**
https://devices.zwave-js.io/?jumpTo=0x0287:0x0004:0x0071:0.0

**Do you have a link to the PDF manual?**
Release notes at https://support.myiblinds.com/knowledge-base/iblinds-v3-firmware/#v3-01-ib3-0zwx

### PR DESCRIPTION
**Pull request by chancehiblinds**
Newer versions (V3.1+) will have a new product ID.
Lower firmware versions will not be affected. No other changes

### CODE REVIEW

**Comment by AlCalzone** [comment]
To clarify, you meant 3.10 like you wrote in the configuration file, not 3.1? The Z-Wave specs treat firmware versions as two numbers without leading zeroes.

**Review by AlCalzone — DISMISSED** [review]

**Comment by blhoward2** [comment]
@chancehiblinds are you with the manufacturer itself? If so, we are actively seeking to build relationship with as many manufacturers as we can to ensure devices are well supported. We appreciate you submitting device files yourself. We're also happy to work with you by email to answer questions or resolve any issues that may arise.

**Comment by chancehiblinds** [comment]
> 
> 
> @chancehiblinds are you with the manufacturer itself? If so, we are actively seeking to build relationship with as many manufacturers as we can to ensure devices are well supported. We appreciate you submitting device files yourself. We're also happy to work with you by email to answer questions or resolve any issues that may arise.

Yes, I am a developer for HAB Home Intelligence, which is the manufacturer of iblinds. We would be happy to cooperate.
You can email me personally (chance@habhomeintel.com) or the CTO Eric, @habhomegit (eric@habhomeintel.com) @blhoward2 



> 
> 
> To clarify, you meant 3.10 like you wrote in the configuration file, not 3.1? The Z-Wave specs treat firmware versions as two numbers without leading zeroes.

For our current model we are using V3.1, which should be fine but we have a V3.01 which is our initial release, and may be read as 3.1. I am slightly concerned about the semantics but we will do some testing to make sure that the correct file is imported upon inclusion. 
Have you had any issues with this in the past? @AlCalzone

**Comment by blhoward2** [comment]
> Have you had any issues with this in the past?

I’m not sure that we’ve had an issue with this. What does the device report for fw firmware version when interviewed?

**Comment by AlCalzone** [comment]
> For our current model we are using V3.1, which should be fine but we have a V3.01 which is our initial release, and may be read as 3.1. I am slightly concerned about the semantics but we will do some testing to make sure that the correct file is imported upon inclusion.

Can you tell me how the device reponds to a `VersionCC::Get` request? That should clear this up. Worst case we can remove the firmware specifier in the files and just detect it based on the different productId.

> Have you had any issues with this in the past?

There has been some confusion in the past. People tend to treat 3.1 and 3.10 as identical but they aren't. The firmware versions are reported as two bytes (numeric) which are just joined with a `.` for the representation, so `3.1` equals `0x0301` and `3.10` equals `0x030a`.

**Comment by chancehiblinds** [comment]
> Can you tell me how the device reponds to a `VersionCC::Get` request?

Here is V3.01
image

We have gone ahead and changed the firmware version to V3.11 to avoid confusion, so anything above 3.10 will work
For V3.01 through V3.06 however, is the leading zero going to be an issue for the firmware ID?
Or will we be able to get away with having it as the 3.6 for 3.06?

**Comment by AlCalzone** [comment]
> For V3.01 through V3.06 however, is the leading zero going to be an issue for the firmware ID?

No, what the devices report gets interpreted by zwave-js as 3.1 - 3.6, so that's fine.

**Comment by blhoward2** [comment]
Just so you know, you also don't have to split the files anymore and keep track. We now support conditional parameters: https://zwave-js.github.io/node-zwave-js/#/config-files/conditional-settings

**Comment by blhoward2** [comment]
Also, this is coincidental. https://github.com/zwave-js/node-zwave-js/issues/2663

Are there any other changes at any fw version beyond this one parameter a user is requesting? It looks like we need to go through and catch-up the files.

**Comment by AlCalzone** [comment]
I think the easiest thing here is to just add the new product ID to the old file and leave the firmware alone. New future firmware parameters can be added with [`$if` conditions](https://zwave-js.github.io/node-zwave-js/#/config-files/conditional-settings).

**Comment by AlCalzone** [comment]
@chancehiblinds I hope you don't mind I took the liberty to make the changes myself. I also added the config param 7 for firmwares 3.6+

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
