### PR TITLE
feat(config): add Fibaro outlet FWPG-121 (UK version)

### LINKED ISSUE #2400: Fibaro Outlet FGWPG-121
Hi,

Just added a Fibaro outlet FWPG-121 (UK variant) device to my Z-wave mesh in Home Assistant and it comes up as unknown manufacturer and model. Looking at the database it seems only the FWPB-121 US version is there today. I have a read through the manual, and created a FWPG-121.json file using the FWPB-121.json file as a template. However I am unsure how to get this into the database Can someone help here?

Thanks.

[fgwpg-121.json.zip](https://github.com/zwave-js/node-zwave-js/files/6333799/fgwpg-121.json.zip)

### PR DESCRIPTION
**Pull request by siwilson2000**
fixes: #2400

### CODE REVIEW

**Comment by siwilson2000** [comment]
@AlCalzone @blhoward2 , Any chance you can take a look at this for me? 

Thanks.

**Review by AlCalzone — APPROVED** [review]
The Fibaro files all need to be aligned with our Style Guide and cleaned up. I gave this one and the original one a quick pass, but I don't want to bother with figuring out the missing units etc. right now.

At least it's better than before now, so let's add this file before doing any more refactoring here.

**Comment by siwilson2000** [comment]
Sorry, I assumed the original one was OK since it was already merged. Thanks for fixing it.

**Comment by siwilson2000** [comment]
@AlCalzone How log does this take to be visible in thew database?

HA was still not picking ups the device, so I had a look at using Z-Wave JS Config DB Browser and I can't see it?

Thanks

**Comment by blhoward2** [comment]
It'll come out with the next release of the driver (we rebuild the database at the same time). Then it takes the addons 1-3 weeks to push the update. We're working on live config file checking but it isn't implemented yet.

**Pull request merged**
