### PR TITLE
Haseman RS-10PM2 - Device Config

### PR DESCRIPTION
**Pull request by mmtnrw**
Did a quick Config for Haseman rs-10pm2

// Haseman RS-10PM2
// MultiRelay
{
	"manufacturer": "Haseman",
	"manufacturerId": "0x0115",
	"label": "RS-10PM2",
	"description": "MultiRelay",
	"devices": [
		{
			"productType": "0xf111",
			"productId": "0x1111"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"paramInformation": {
		"11": {
			"label": "Reporting Time (seconds)",
			"description": "Range 1-255",
			"valueSize": 1,
			"minValue": 1,
			"maxValue": 255,
			"defaultValue": 30,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": true
		},
		"64": {
			"label": "Power Up Memory",
			"description": "1=Active 0=Inactive",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 1,
			"defaultValue": 0,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "1 - Active",
					"value": 1
				},
				{
					"label": "0 - Inactive",
					"value": 0
				}
			]
		},
		"65": {
			"label": "Button Type - Channel 1",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"66": {
			"label": "Button Type - Channel 2",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"67": {
			"label": "Button Type - Channel 3",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"68": {
			"label": "Button Type - Channel 4",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"69": {
			"label": "Button Type - Channel 5",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"70": {
			"label": "Button Type - Channel 6",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"71": {
			"label": "Button Type - Channel 7",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"72": {
			"label": "Button Type - Channel 8",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"73": {
			"label": "Button Type - Channel 9",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		},
		"74": {
			"label": "Button Type - Channel 10",
			"description": "(separate for each channel)",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 1,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": false,
			"options": [
				{
					"label": "Inactive",
					"value": 0
				},
				{
					"label": "Push Button",
					"value": 1
				},
				{
					"label": "Toggle Switch",
					"value": 2
				},
				{
					"label": "Follower Switch",
					"value": 3
				}
			]
		}
	}
}

### CODE REVIEW

**Comment by AlCalzone** [comment]
I think you messed up. Wanna try again?

**Comment by mmtnrw** [comment]
> I think you messed up. Wanna try again?

Dunno how to add it, so please add it by yourself :) Since i already wrote it for Openhab and it was downloaded very often, i think it will be usefully......

[haseman_rs-10pm2.json.txt](https://github.com/zwave-js/node-zwave-js/files/6291425/haseman_rs-10pm2.json.txt)

**Comment by AlCalzone** [comment]
Ok, I was just confused by you opening a PR :)

**Comment by mmtnrw** [comment]
> Ok, I was just confused by you opening a PR :)

Thx.....

**Pull request closed without merging**
