### PR TITLE
fix(config): fix typos (zts-110)

### PR DESCRIPTION
**Pull request by aptalca**
`Farhenheit` > `Fahrenheit`

### CODE REVIEW

**Comment by AlCalzone** [comment]
Thanks!

Looks like this entire file is suboptimal. Would you be willing to give it a pass and align it with our [style guide](https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide)?

**Comment by aptalca** [comment]
Sure, I'd be happy to

**Comment by AlCalzone** [comment]
Cool, when do you think you'll be able to?

**Review by AlCalzone — APPROVED** [review]
Approved with my change. I'll merge this, but we'd very much appreciate if you could give the entire file a revisit :)

**Pull request merged**
