### PR TITLE
feat(config): add Aeotec ZW187 Recessed Door Sensor 7

### LINKED ISSUE #1259: Support Aeotec Recessed Door Sensor 7
Support Aeotec Recessed Door Sensor 7 is currently unknown to zwave-js.

After inclusion (secure) it says:
Unknown manufacturer: 881
Unknown product: 187
Product: 2

User guide:
[Aeotec Recessed Door Sensor 7 Engineering Specification.pdf](https://github.com/zwave-js/node-zwave-js/files/5754360/Aeotec.Recessed.Door.Sensor.7.Engineering.Specification.pdf)

https://aeotec.freshdesk.com/support/solutions/articles/6000226848-recessed-door-sensor-7-user-guide-

Web UI Console Debug log during inclusion:
[recessed7.log](https://github.com/zwave-js/node-zwave-js/files/5754374/recessed7.log)

The log contains some  "DRIVER Message with invalid data received. Dropping it" messages.

### PR DESCRIPTION
**Pull request by larstobi**
Add Aeotec ZW187 Recessed Door Sensor 7

Closes #1259

### CODE REVIEW

**Comment by AlCalzone** [comment]
Is this ready?

**Comment by larstobi** [comment]
> Is this ready?

No, I need to fix the parial CCs first. They don't work, currently.

**Comment by AlCalzone** [comment]
Can you make a log where you try to set them?

**Comment by larstobi** [comment]
```
2021-01-03 17:23:05.387 INFO SOCKET: Event ZWAVE_API emitted to DbnpjAzyp4cRdQfEAAAJ
2021-01-03 17:23:05.394 INFO APP: Zwave api call: writeValue [
  {
    nodeId: 87,
    commandClass: 112,
    endpoint: 0,
    property: 4,
    propertyKey: 1
  },
  2,
  [length]: 2
]
2021-01-03 17:23:05.395 INFO ZWAVE: Writing 2 to 112-0-4-1
2021-01-03 17:23:10.316 INFO ZWAVE: Node 87 is now awake
2021-01-03 17:23:12.650 INFO ZWAVE: Node 87: value updated: 128-0-level 100 => 100
2021-01-03 17:23:12.651 INFO ZWAVE: Node 87: value updated: 128-0-isLow false => false
2021-01-03 17:23:12.768 INFO ZWAVE: Success zwave api call writeValue
2021-01-03 17:23:12.885 INFO ZWAVE: Node 87: value updated: 132-0-wakeUpInterval 3600 => 3600
2021-01-03 17:23:12.887 INFO ZWAVE: Node 87: value updated: 132-0-controllerNodeId 1 => 1
2021-01-03 17:23:13.079 INFO ZWAVE: Node 87: value updated: 112-0-4-1 0 => 0
2021-01-03 17:23:13.080 INFO ZWAVE: Node 87: value updated: 112-0-4-2 0 => 0
2021-01-03 17:23:13.207 INFO ZWAVE: Node 87: metadata updated: 135-0-80-3
2021-01-03 17:23:13.208 INFO ZWAVE: Node 87: value updated: 135-0-80-3 0 => 0
2021-01-03 17:23:13.208 INFO ZWAVE: Node 87: metadata updated: 135-0-80-4
2021-01-03 17:23:13.209 INFO ZWAVE: Node 87: value updated: 135-0-80-4 0 => 0
2021-01-03 17:23:13.209 INFO ZWAVE: Node 87: metadata updated: 135-0-80-5
2021-01-03 17:23:13.210 INFO ZWAVE: Node 87: value updated: 135-0-80-5 0 => 0
2021-01-03 17:23:23.303 INFO ZWAVE: Node 87 is now asleep
```

**Comment by larstobi** [comment]
```
2021-01-03 17:42:20.395 INFO SOCKET: Event ZWAVE_API emitted to QQIJZcsqhLrWbZ8oAAAL
2021-01-03 17:42:20.399 INFO APP: Zwave api call: writeValue [
  {
    nodeId: 87,
    commandClass: 112,
    endpoint: 0,
    property: 4,
    propertyKey: 2
  },
  3,
  [length]: 2
]
2021-01-03 17:42:20.400 INFO ZWAVE: Writing 3 to 112-0-4-2
2021-01-03 17:42:23.537 INFO ZWAVE: Node 87 is now awake
2021-01-03 17:42:25.895 INFO ZWAVE: Success zwave api call writeValue
2021-01-03 17:42:26.392 INFO ZWAVE: Node 87: value updated: 112-0-4-65280 0 => 0
2021-01-03 17:42:26.392 INFO ZWAVE: Node 87: value updated: 112-0-4-255 0 => 0
2021-01-03 17:42:27.773 INFO ZWAVE: Node 87 is now asleep

```

**Comment by larstobi** [comment]
@AlCalzone Are these the logs you wanted?

**Comment by AlCalzone** [comment]
Sorry, I always need the detailed zwave-js logfiles, not the ones from zwavejs2mqtt.

**Comment by AlCalzone** [comment]
re-opening to test against the newly-added checks

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
