### PR TITLE
fix: don't hide Basic values with treatBasicSetAsEvent

### PR DESCRIPTION
**Pull request by AlCalzone**
Grasping at straws here, but I think this solves the underlying symptom of #1406 
@blhoward2 @robertsLando

### CODE REVIEW

**Comment by blhoward2** [comment]
I'll try it. The values were created under the original compat flag.

**Comment by blhoward2** [comment]
@AlCalzone This works, but it only adds the value when you do a double-tap the first time. It does make the notification_event sensor at that time, so I think this it is fine if that's all we can do. It means that entities may from time-to-time appear. (e.g. if you have a switch you don't normally double-tap, and then someone accidentally double taps it, you'd have a new, unnamed entity discovered in HA.)

**Comment by AlCalzone** [comment]
Hmm that is actually the normal behavior for almost all values, but because they are queried during the interview, you don't notice. I can pre-create the metadata during the interview if that is desired.

**Comment by blhoward2** [comment]
Can you do so only where the compat flag is set? Obviously you wouldn’t want to do it for every switch, but it would help to have the entities discovered initially.

**Comment by AlCalzone** [comment]
Try now :)

**Comment by blhoward2** [comment]
Nope, in fact that broke what was working. I still see the event on mqtt but no devices setup in HA.

**Comment by AlCalzone** [comment]
Can you make me a log of that? And did you re-interview the node?

**Comment by blhoward2** [comment]
Here you go:

`2021-01-17 13:30:38.180 INFO ZWAVE: Node 3: value notification: 32-0-event 255`

```
13:30:38.177 DRIVER « [Node 003] [REQ] [ApplicationCommand]
                      └─[BasicCCSet]
                          target value: 255
13:30:38.179 CNTRLR   [Node 003] treating BasicCC Set as a value event
```

That all appears to work, but it never discovers a sensor for 32. Before your most recent change it would discover it on a double-tap, but now it does not discover it then either. I neglected to nuke my log file first and its huge, so let me know if you need the verbose log and I'll do it again.

```
2021-01-17 13:10:31.145 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 50 => 50

2021-01-17 13:10:31.159 INFO ZWAVE: Node 3 is alive

2021-01-17 13:10:31.543 INFO ZWAVE: Node 3: value added 3-38-0-targetValue => 50

2021-01-17 13:10:31.549 INFO ZWAVE: Node 3: value added 3-38-0-duration => undefined

2021-01-17 13:10:31.796 INFO ZWAVE: Node 3: value added 3-38-0-currentValue => 50

2021-01-17 13:10:31.799 INFO ZWAVE: Node 3: value added 3-38-0-Up => undefined

2021-01-17 13:10:31.800 INFO ZWAVE: Node 3: value added 3-38-0-Down => undefined

2021-01-17 13:10:31.802 INFO ZWAVE: Node 3: value added 3-43-0-sceneId => undefined

2021-01-17 13:10:31.804 INFO ZWAVE: Node 3: value added 3-43-0-dimmingDuration => undefined

2021-01-17 13:10:31.806 INFO ZWAVE: Node 3: value added 3-112-0-3 => 0

2021-01-17 13:10:31.807 INFO ZWAVE: Node 3: value added 3-112-0-4 => 0

2021-01-17 13:10:31.809 INFO ZWAVE: Node 3: value added 3-112-0-7 => 20

2021-01-17 13:10:31.811 INFO ZWAVE: Node 3: value added 3-112-0-8 => 1

2021-01-17 13:10:31.812 INFO ZWAVE: Node 3: value added 3-112-0-9 => 20

2021-01-17 13:10:31.814 INFO ZWAVE: Node 3: value added 3-112-0-10 => 1

2021-01-17 13:10:31.815 INFO ZWAVE: Node 3: value added 3-112-0-11 => 20

2021-01-17 13:10:31.817 INFO ZWAVE: Node 3: value added 3-112-0-12 => 1

2021-01-17 13:10:31.818 INFO ZWAVE: Node 3: value added 3-114-0-manufacturerId => 99

2021-01-17 13:10:31.820 INFO ZWAVE: Node 3: value added 3-114-0-productType => 18756

2021-01-17 13:10:31.821 INFO ZWAVE: Node 3: value added 3-114-0-productId => 12344

2021-01-17 13:10:31.823 INFO ZWAVE: Node 3: value added 3-134-0-libraryType => 3

2021-01-17 13:10:31.824 INFO ZWAVE: Node 3: value added 3-134-0-protocolVersion => 4.34

2021-01-17 13:10:31.826 INFO ZWAVE: Node 3: value added 3-134-0-firmwareVersions => 5.29

2021-01-17 13:10:31.827 INFO ZWAVE: Node 3: value added 3-134-0-hardwareVersion => undefined

2021-01-17 13:10:31.928 INFO ZWAVE: Node 3: metadata updated: 112-0-3

2021-01-17 13:10:31.931 INFO ZWAVE: Node 3: metadata updated: 112-0-4

2021-01-17 13:10:31.934 INFO ZWAVE: Node 3: metadata updated: 112-0-7

2021-01-17 13:10:31.937 INFO ZWAVE: Node 3: metadata updated: 112-0-8

2021-01-17 13:10:31.939 INFO ZWAVE: Node 3: metadata updated: 112-0-9

2021-01-17 13:10:31.942 INFO ZWAVE: Node 3: metadata updated: 112-0-10

2021-01-17 13:10:31.945 INFO ZWAVE: Node 3: metadata updated: 112-0-11

2021-01-17 13:10:31.947 INFO ZWAVE: Node 3: metadata updated: 112-0-12

2021-01-17 13:11:09.765 INFO ZWAVE: Node 3: value updated: 112-0-3 0 => 0

2021-01-17 13:11:29.401 INFO ZWAVE: Node 3: value updated: 112-0-4 0 => 0

2021-01-17 13:11:51.358 INFO ZWAVE: Node 3: value updated: 112-0-7 20 => 20

2021-01-17 13:12:13.214 INFO ZWAVE: Node 3: value updated: 112-0-8 1 => 1

2021-01-17 13:12:44.829 INFO ZWAVE: Node 3: value updated: 112-0-9 20 => 20

2021-01-17 13:12:59.479 INFO ZWAVE: Node 3: value updated: 112-0-10 1 => 1

2021-01-17 13:13:03.320 INFO ZWAVE: Node 3: value updated: 112-0-11 20 => 20

2021-01-17 13:13:09.478 INFO ZWAVE: Node 3: value updated: 112-0-12 1 => 1

2021-01-17 13:13:10.969 INFO ZWAVE: Node 3: value updated: 112-0-12 1 => 1

2021-01-17 13:13:46.434 INFO ZWAVE: Node 3: interview completed, all values are updated

2021-01-17 13:30:38.180 INFO ZWAVE: Node 3: value notification: 32-0-event 255
```

**Comment by blhoward2** [comment]
[node 3 interview.log](https://github.com/zwave-js/node-zwave-js/files/5826786/node.3.interview.log)

**Comment by blhoward2** [comment]
[node 3 interview v2.log](https://github.com/zwave-js/node-zwave-js/files/5827002/node.3.interview.v2.log)

**Comment by AlCalzone** [comment]
Okay I know what happens. The Basic CC is not in the list of supported CCs and doesn't get interviewed. As a result the value Metadata does not get created.
Should be an easy fix.

**Comment by AlCalzone** [comment]
@blhoward2 try again :)

**Comment by robertsLando** [comment]
Please inform me when this is merged (now I will receive notification)

**Comment by blhoward2** [comment]
The switch now creates a Basic class automatically in querying, but HA doesn't set up the sensor like it did before it did this. I'm unsure if it is on your end or @robertsLando .

[node 3 interview v3.log](https://github.com/zwave-js/node-zwave-js/files/5840140/node.3.interview.v3.log)


[node_3.json 2.zip](https://github.com/zwave-js/node-zwave-js/files/5840143/node_3.json.2.zip)

**Comment by AlCalzone** [comment]
It is still not querying the Basic CC 😫

**Comment by robertsLando** [comment]
> It is still not querying the Basic CC tired_face

So it's not on my side right?

**Comment by AlCalzone** [comment]
Probably not
@blhoward2 Try the latest commit please

**Comment by AlCalzone** [comment]
@zwave-js-bot fix lint

**Comment by blhoward2** [comment]
Do we need to actually query it? Don’t we know what it’ll be from the compat flag? Aren’t all Basic Sets the same?

**Comment by AlCalzone** [comment]
The value metadata is created during the interview (only once). The interview is only done if the Basic CC is supported.

Let me know if it works after the last change. If not, I'll roll back to the version where it works after the double tap.

**Comment by blhoward2** [comment]
@AlCalzone This is working perfectly now, thanks!

**Pull request merged**
