### PR TITLE
feat(config): add new configuration for PIR-200 Motion Sensor

### PR DESCRIPTION
**Pull request by rikdc**
This configuration is for Evolve PIR-200. 

It was sold to me as "GoControl", and the packaging had Norteck, and the manual had Evolve, so I wasn't sure what Manufacturer name to include.

https://opensmarthouse.org/zwavedatabase/1245/reference/evolve-pir-200-installation.pdf

### CODE REVIEW

**Comment by rikdc** [comment]
@zwave-js-bot fix lint

**Review by blhoward2 — CHANGES_REQUESTED** [review]
You're missing some key points in our style guide, like capitalization. Please take a look and correct, then request a new review when you're ready. 

https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide

**Comment by rikdc** [comment]
> You're missing some key points in our style guide, like capitalization. Please take a look and correct, then request a new review when you're ready.
> 
> https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide

Thanks for taking a look! Happy to update this, just verifying where the issue is. Is it with the option labels? The `paramInformation` block was taken from a [similar device](https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x027a/zse40.json#L118). I also wasn't sure if the description added meaningfully, but opted to keep it in for consistency with other devices.

**Comment by blhoward2** [comment]
Option labels was what caught my eye, yes. We're cleaning up files and just haven't gotten to the other one yet.

**Review by blhoward2 — APPROVED** [review]
I made some minor changes to get rid of the descriptions.

**Comment by AlCalzone** [comment]
I would probably have mentioned the sensitivity range (highest to lowest) in the description instead of options, but I can live with that.

**Comment by rikdc** [comment]
Glad it's merged, thanks for the feedback - that'll help for any future ones I submit.

**Pull request merged**
