### PR TITLE
fix(config): add Clamp 3 meters to DSB28, fix bitmask

### PR DESCRIPTION
**Pull request by booroondook-eng**
Added Clamp 3 meters and corrected 1 mistake

### CODE REVIEW

**Comment by blhoward2** [comment]
Not all devices have three clamps and defining these for ones that don't can cause issues. Can you confirm your deviceType and deviceId? Firmware version? We're going to have to see if we can condition these somehow.

**Comment by booroondook-eng** [comment]
> Not all devices have three clamps and defining these for ones that don't can cause issues. Can you confirm your deviceType and deviceId? Firmware version? We're going to have to see if we can condition these somehow.

2021-05-09 14_44_13-IMG_20210509_143852_9 jpg - IrfanView (Zoom_ 1224 x 918)
As you can see n the attached photo, my device has name DSB28-ZWEU and it has 3 clamps for 3 phases.
Also you can read its user manual: https://aeotec.freshdesk.com/support/solutions/articles/6000166671-home-energy-meter-g2-user-manual- (please read "Diagram of EU/AU Version(3 Phases,4 Wires)" article), and you can download  Excel table (HEM Calculator) with its parameters: https://aeotec.freshdesk.com/helpdesk/attachments/6103459970

**Comment by blhoward2** [comment]
That's not the info I need. From zjs2mqtt or HA, what's the deviceType, deviceID and firmware version? I need the device's fingerprint.

**Comment by booroondook-eng** [comment]
> That's not the info I need. From zjs2mqtt or HA, what's the deviceType, deviceID and firmware version? I need the device's fingerprint.

I don't fully understand where I can get the information you need. Maybe these screenshots will answer your question?
2021-05-09 15_36_25-Window
2021-05-09 15_39_10-Z-Wave JS - Home Assistant

**Comment by AlCalzone** [comment]
@blhoward2 there were already other settings for clamp 3 in that file. Looks like an oversight to me. Device ID is correct.

**Comment by blhoward2** [comment]
Aeotec confirmed there is no way to distinguish these or the ZW095. Some have two clamps and some three. Do we hide the parameter when it eventually times out on the read?

**Comment by AlCalzone** [comment]
No we don't. Could just be temporary RF problems. Don't think that's much of a problem though.

**Comment by AlCalzone** [comment]
sorry, I'll need to hijack your PR for a test

**Comment by AlCalzone** [comment]
hm, that's not what I expected to happen 😅

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
