### PR TITLE
fix(config): update Zipato NE-NAS-AB02Z

### PR DESCRIPTION
**Pull request by marcusbirkin**
Add missing parameters
Order parameters to group like parameters
Tweak exisiting labels for consistency

### CODE REVIEW

**Comment by AlCalzone** [comment]
Do you have a source for these changes? All manuals I find online for this device, including [this one](https://www.zipato.com/wp-content/uploads/2018/06/ne-nas-ab02z.eu-Zipato-INDOOR-SIREN_UserManual_v1.4_newFCC_ID_preview.pdf) on the [manufacturer page](https://www.zipato.com/product/indoor-siren) only mention params 1-6 and no "Disabled" volume.

**Comment by marcusbirkin** [comment]
> Do you have a source for these changes? All manuals I find online for this device, including [this one](https://www.zipato.com/wp-content/uploads/2018/06/ne-nas-ab02z.eu-Zipato-INDOOR-SIREN_UserManual_v1.4_newFCC_ID_preview.pdf) on the [manufacturer page](https://www.zipato.com/product/indoor-siren) only mention params 1-6 and no "Disabled" volume.

The source is I have 2 of them.
I'm not sure why these parameters are not documented in the manual, as without parameter 7 the unit can never function as a doorbell!.
I also had to make the same changes to OpenZWave a couple of years ago. https://github.com/OpenZWave/open-zwave/pull/2072

**Comment by AlCalzone** [comment]
Fair enough - do you know if these were changed with a specific firmware version?

**Comment by marcusbirkin** [comment]
That I don't know.
What I do know is both my units run v2.17

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
