### PR TITLE
feat: support pre-filling the DSK and scanning DSK-only QRs

### LINKED ISSUE #5205: Smart Start: QR Code inclusion
A controller providing the SmartStart functionality SHOULD provide a QR Code scanning capability. If the controller offers a QR Code scanning capability:

- [x] It MUST support the addition of nodes using QR Code format defined in [10] in its Provisioning List when scanning the QR Code.
- [ ] It SHOULD support scanning of S2 only QR codes representing the DSK String prefixed with “zws2dsk:”.(example: “zws2dsk:34028-23669-20938-46346-33746-07431-56821-14553”) in order to simplify the S2 bootstrapping process.

_Note: We should also support un-prefixed DSK QR codes_

### PR DESCRIPTION
**Pull request by AlCalzone**
@raman325 @robertsLando 

This is an attempt at supporting QR codes that only include the DSK (prefixed or unprefixed). I tried to add this functionality to the API without breaking changes - doing this as part of `parseQRCodeString` would require changes to the return type which in turn would require application-level checks to decide what to do with the info.

The downside is that after scanning, applications need to first check if the QR code string is a valid DSK (`tryParseDSKFromQRCodeString`) and if yes use the S2 inclusion strategy with pre-filled DSK.
If not, attempt to parse the encoded info from the QR code string as they do now.

Thoughts?

fixes: #5205

### CODE REVIEW

**Review by robertsLando — DISMISSED** [review]
LGTM for me 👍🏼

**Comment by raman325** [comment]
so if I understand this correctly, the existing logic would not work for this type of QR code, both before and after the change. After this change, we'd have to add explicit support by adding a logic branch that checks the QR code against this new function and branches off to inclusion strategy with pre-filled DSK if it's this type of QR code?

If I got that right, this looks like a great way to solve this problem without breaking anything.

**Comment by AlCalzone** [comment]
Correct

**Comment by robertsLando** [comment]
@AlCalzone Could that function be 'safe' so I can use it directly on frontend?

**Comment by AlCalzone** [comment]
done

**Comment by robertsLando** [comment]
Perfect! That would make it even easier to integrate :)

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

**Pull request merged**
