### PR TITLE
fix(config): fixed Fantem Motion configuration

### PR DESCRIPTION
**Pull request by cdnninja**
Added device ID and additional parameters to Fantem motion 6 which is an OEM for Aeotec ZW100. Clone of https://github.com/zwave-js/node-zwave-js/blob/27a9e2a9b4fb78d47c9d743216959472f40fde20/packages/config/config/devices/0x0086/zw100_0.0-1.6.json.   I am not sure if firmware align though so using the lowest firmware as a starting point.

#1596

### CODE REVIEW

**Comment by cdnninja** [comment]
@zwave-js-bot fix lint

**Comment by AlCalzone** [comment]
@blhoward2 just reworked the file you used as a starting point:
https://github.com/blhoward2/node-zwave-js/blob/aeotec_group_3/packages/config/config/devices/0x0086/zw100.json
Please align your file to that one, so we have the same parameter definitions in both (at least the ones that match).

**Comment by cdnninja** [comment]
Done.  I don't think this can be merged until #2459 is done. 

> @blhoward2 just reworked the file you used as a starting point:
> https://github.com/blhoward2/node-zwave-js/blob/aeotec_group_3/packages/config/config/devices/0x0086/zw100.json
> Please align your file to that one, so we have the same parameter definitions in both (at least the ones that match).

**Comment by AlCalzone** [comment]
#2459 is merged

**Comment by AlCalzone** [comment]
@cdnninja ping, you can finalize this now.

**Comment by cdnninja** [comment]
@zwave-js-bot fix lint

**Comment by cdnninja** [comment]
@zwave-js-bot fix lint

**Comment by cdnninja** [comment]
@AlCalzone  Ready for your review.

**Comment by AlCalzone** [comment]
I recently made some changes to the required fields and updated your file to match the changes. Looked good otherwise.

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
