### PR TITLE
feat: add ability to get current logging configuration

### PR DESCRIPTION
**Pull request by raman325**
Follow on to https://github.com/zwave-js/node-zwave-js/pull/1754. This will allow us to add support to `zwave-js-server` and we can subsequently expose a way to see and update the logging configuration from the HA frontend.

### CODE REVIEW

**Comment by AlCalzone** [comment]
I don't think it makes perfect sense to return the `winston` transports along with the rest of the options, or do you need them?

**Comment by raman325** [comment]
Nope, we can remove it, I just wasn't sure how to 🙂

**Comment by AlCalzone** [comment]
Okay I will edit the PR tomorrow.

**Comment by AlCalzone** [comment]
On second thought - let's leave it in.

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
