### PR TITLE
fix(config): cleanup and consolidate ARZ Roller Shutters

### LINKED ISSUE #3872: ARZ Solar (productType 0x0003 - productId 0x0112) Configuration - "COPY" ARZ Z-wave (productType 0x0003 - productId 0x0011)
My ARZ Solar does not allow configuration.
However the ARZ Solar is pretty much the same as the ARZ Z-wave but with an added solar power source.
One of the problems I seem to have is that my shutter/cover does not fully open when the command is issued. At 100% open I still see a part of the shutter covering the window. 

**Describe the solution you'd like**
Could the configuration of the ARZ Z-wave be copied in the configuration of the ARZ Solar. By having a calibration option I think I might be able to solve the "100% open"-problem.

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #3872

### CODE REVIEW

**Comment by gitd8400** [comment]
@AlCalzone [NC 97C-GB_ARZ Solar_20.11.20_FAKRO_KB2356.pdf](https://github.com/zwave-js/node-zwave-js/files/7685459/NC.97C-GB_ARZ.Solar_20.11.20_FAKRO_KB2356.pdf)
This is the manual for the ARZ Solar (0x0112). Parameter 12 does not exist as "the motor works from limit switch to limit switch and control unit updates its run time" (dixit Fakro)

**Comment by AlCalzone** [comment]
Hmm that doesn't seem to mention the calibration parameter...
Are you able to test the new file and see if it reacts to it?

https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files describes how, you'll have to save both files there:
https://raw.githubusercontent.com/zwave-js/node-zwave-js/arz/packages/config/config/devices/0x0085/arz_z-wave.json
and
https://raw.githubusercontent.com/zwave-js/node-zwave-js/arz/packages/config/config/devices/0x0085/arz_z-wave_solar.json

**Comment by gitd8400** [comment]
> Hmm that doesn't seem to mention the calibration parameter... Are you able to test the new file and see if it reacts to it?

As that device model uses the limit switches I was told it does not need the calibration parameter (12). I'm trying to upload the custom files, but can't seem to find the necessary folder (ZwaveJS Addon in Home Assistant)

**Comment by AlCalzone** [comment]
You'll have to temporarily switch to the zwavejs2mqtt addon.

**Comment by gitd8400** [comment]
I changed to zwavejs2mqtt and was able to add the files like you said.
The configuration options show up, but Response to Basic Set does nothing.
I dare not try the Calibration option for my device as my device does not need this.

However, strange thing is that zwavejs2mqtt seems to be able to fully open the shutter whereas the zwavejs addon does not.

**Comment by AlCalzone** [comment]
> Response to Basic Set does nothing.

Did you actually send the device a **Basic CC** Set with targetValue 255?

> However, strange thing is that zwavejs2mqtt seems to be able to fully open the shutter whereas the zwavejs addon does not.

This might be something worth reporting in https://github.com/home-assistant/core

**Comment by AlCalzone** [comment]
> I dare not try the Calibration option for my device as my device does not need this.

With the manual you posted, it probably makes more sense to document the config params that are in there.

**Comment by gitd8400** [comment]
> > Response to Basic Set does nothing.
> 
> Did you actually send the device a **Basic CC** Set with targetValue 255?

Tried both:
image
image

**Comment by gitd8400** [comment]
> > However, strange thing is that zwavejs2mqtt seems to be able to fully open the shutter whereas the zwavejs addon does not.
> 
> This might be something worth reporting in https://github.com/home-assistant/core

I was going to but now I switched back from zwavejs2mqtt to zwavejs and re-adding the integration it works perfect again.
I can't recreate the problem so possibly something went wrong while adding the integration before?

**Comment by AlCalzone** [comment]
> > Did you actually send the device a **Basic CC** Set with targetValue 255?
> 
> Tried both:

That just shows you changing the configuration. Did you also send a Basic CC Set command?

**Comment by gitd8400** [comment]
> That just shows you changing the configuration. Did you also send a Basic CC Set command?

Right you are (again). Z-wave remains a conundrum to me. I'll try and issue that command. Is this possible via the Web UI of zwavejs2mqtt? Or should I use MQTT for that.

**Comment by AlCalzone** [comment]
Try mqtt. Since there's usually a "better" CC, the basic CC values are hidden most of the time.

**Pull request merged**
