### PR TITLE
feat(config): add Zooz Zen37 800LR Wall Remote

### LINKED ISSUE #6571: Missing device configuration: Zooz ZEN37
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [X] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

Zooz ZEN37

### Manufacturer ID

0x027a

### Product Type

0x7000

### Product ID

0xf003

### Firmware Version

1.0.0

### Is the device listed on the Z-Wave Alliance website?

No

### Do you have a manual?

https://cdn.shopify.com/s/files/1/0218/7704/files/zooz-800-series-z-wave-long-range-wall-remote-zen37-800lr-manual.pdf

### PR DESCRIPTION
**Pull request by zackbcom**
## Changes
- PR for Zooz 800 Series Z-Wave Long Range Wall Remote ZEN37 800LR (Battery Powered)
  - Note, not currently in Zwave Alliance.
  - [Manual](https://cdn.shopify.com/s/files/1/0218/7704/files/zooz-800-series-z-wave-long-range-wall-remote-zen37-800lr-manual.pdf) 
  - [Product Site](https://www.thesmartesthouse.com/products/zooz-800-series-z-wave-long-range-wall-remote-zen37-800lr-battery-powered)
  - Firmware is at 1.0.0 [[source](https://www.support.getzooz.com/kb/article/1622-zen37-wall-remote-change-log/)]
- Fixes: #6571

## Questions
I'm unsure if I need the following snippit of code. Seems like other [Zooz devices have this](https://github.com/search?q=repo%3Azwave-js%2Fnode-zwave-js%20path%3A%2F%5Epackages%5C%2Fconfig%5C%2Fconfig%5C%2Fdevices%5C%2F0x027a%5C%2F%2F%20skipConfigurationNameQuery&type=code).
```json
	"compat": {
		// The device sends Configuration CC info reports in 4-byte chunks, causing each query to block the network for roughly 1.5 seconds.
		"skipConfigurationNameQuery": true,
		"skipConfigurationInfoQuery": true
	},
```

## Testing artifacts
- Tested on local UI. Everything looks good.
  - image
  - image

### CODE REVIEW

**Comment by zacs** [comment]
@AlCalzone anything I can do to help push this along?

**Comment by zackbcom** [comment]
@zacs I have been sick. If you want to finish the MR, feel free.

**Comment by zackbcom** [comment]
@zacs @AlCalzone 
Ready for review.

**Comment by eric10k93** [comment]
any chance of getting this reviewed/merged soon?

**Comment by l3arcf** [comment]
I too would love to see this reviewed and merged. Up-vote here.

**Comment by drewmcdowell** [comment]
Waiting with bated breath for this to be merged. 🤞

**Review by justinsanker — APPROVED** [review]

**Comment by justinsanker** [comment]
Hey guys, any chance you could complete this before the end of the month?

**Comment by davidcsally** [comment]
@AlCalzone  @zacs would love to see this merged if possible!

**Comment by AlCalzone** [comment]
Did a few cleanup changes, otherwise looks good.
I'm awaiting confirmation from Zooz about the association groups - they might not be necessary.

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
