### PR TITLE
fix(config): add Neo Coolcam PIR Sensor 2

### PR DESCRIPTION
**Pull request by bwosborne2**
Added PIR sensor 2 and removed from old file.

### CODE REVIEW

**Comment by bwosborne2** [comment]
This should resolve Issue # 2738

https://github.com/zwave-js/node-zwave-js/issues/2738

**Comment by bwosborne2** [comment]
@zwave-js-bot fix lint

**Comment by bwosborne2** [comment]
@zwave-js-bot run checks

**Review by blhoward2 — APPROVED** [review]
Changes approved but I don't think this changes anything RE #2738

**Review by AlCalzone — CHANGES_REQUESTED** [review]
I also don't see how this fixes #2738. You didn't change the configuration parameters.

**Comment by bwosborne2** [comment]
> You didn't change the configuration parameters.

image

image


What am I missing? I just removed the reference in the original file and added a second one.

**Comment by blhoward2** [comment]
Exactly, so the only thing you changed was the label that displays. That wouldn't fix anything if it was broken.

**Comment by bwosborne2** [comment]
Let me close & try this again later. Somehow I posted an incorrect file. Sorry.

**Pull request closed without merging**
