### PR TITLE
Use node list instead of bit mask for SendDataMulti

### PR DESCRIPTION
**Pull request by AlCalzone**
@lukescott I could use your help testing the Multicast support. With this change, I get a report from the controller that the messages are actually sent, but my test plug does not react to the BinarySwitchSet command.

### CODE REVIEW

**Comment by lukescott** [comment]
I should be able to test it this weekend. At a company conference at the moment. 

Did u see the links I posted on the other thread about the source code I found from Silicon Labs?

**Comment by AlCalzone** [comment]
Yep, thanks! I confirmed with that source code that the node list is not a bitmask like written in the specs, but really an array with node IDs. Hence this PR.

**Comment by lukescott** [comment]
Strange that the specs were wrong.

Have you tried the Basic CC? I looked over the C# version (that has tests) and they have this:

```C#
private TransmitOptions _txOptions = TransmitOptions.TransmitOptionAcknowledge;

var sendRes = firstCtrl.SendDataMulti(new byte[] { 0x02, 0x03 }, new COMMAND_CLASS_BASIC.BASIC_SET(), _txOptions);
```

When I have a chance I'll test it w/ my HS-WS100+ switches.

**Comment by AlCalzone** [comment]
> Strange that the specs were wrong.

You would be surprised how often small mistakes are in there.

I haven't tested with BasicSet, only BinarySwitchSet. And I had different transmission options than just ACK. Will do another test tonight, didn't have much time yesterday.

**Comment by lukescott** [comment]
Doesn't seem to work. I get this:
```
03:42:24.749 DRIVER » [REQ] [SendDataMulticast]                                          [P: Normal]
                      │ transmitOptions: 0x25
                      │ callbackId:      50
                      └─[BinarySwitchCCSet]
                          payload: 0x00
03:42:24.752 SERIAL » 0x010b001402052e2501002532fa                                        (13 bytes)
03:42:24.761 SERIAL « [ACK]                                                                   (0x06)
03:42:24.763 DRIVER   ACK received from controller for current transaction
03:42:24.765 SERIAL   The receive buffer is empty, waiting for the next chunk...
03:42:24.769 SERIAL « 0x0104011401ef                                                       (6 bytes)
03:42:24.771 SERIAL   Buffer := 0x0104011401ef                                             (6 bytes)
03:42:24.774 SERIAL » [ACK]                                                                   (0x06)
03:42:24.777 DRIVER « [RES] [SendDataMulticast]                                       [confirmation]
                        wasSent: true
03:42:24.781 SERIAL   The receive buffer is empty, waiting for the next chunk...
```

When I try to send a normal message afterward I get:
```
03:43:20.982 DRIVER   workOffSendQueue > skipping because a transaction is pending
```

**Comment by lukescott** [comment]
This is the code I am currently using to test:
```ts
import {Driver} from "zwave-js"
import {BinarySwitchCCSet} from "zwave-js/build/lib/commandclass/BinarySwitchCC"
import repl = require("repl")

const driver = new Driver("/dev/ttyAMA0", {
	// @ts-ignore
	skipInterview: true,
})

driver.on("driver ready", async () => {
	await driver.controller.interview()
	await driver.controller.nodes.get(46).interview()
	await driver.controller.nodes.get(5).interview()
})

process.on("SIGINT", async () => {
    await driver.destroy()
    process.exit(0);
})

driver.start()

const replServer = repl.start({
    useGlobal: true,
});

function send(nodeId: number | [number, number, ...number[]], targetValue: boolean) {
	const cc = new BinarySwitchCCSet(driver, {
		nodeId,
		endpoint: 0,
		targetValue
	});
	driver.sendCommand(cc)
}

replServer.context.driver = driver;
replServer.context.send = send;

replServer.on("close", async () => {
    await driver.destroy()
    process.exit(0);
})
```
And then in repl `send([5, 46], false)` with 5 and 46 being my Kitchen counter and overhead lights.

**Comment by AlCalzone** [comment]
> Doesn't seem to work

Have you tried with BasicCCSet? The behavior you wrote above happened to me too. Seems that no aknowledgement is received although the corresponding transmit option is set.

**Comment by lukescott** [comment]
Yep, same result with BasicCCSet.

**Comment by AlCalzone** [comment]
Do the devices react to the commands?

**Comment by lukescott** [comment]
If I send a single node id it reacts (singlecast). If I try to send more than one (multicast) it does not. I'm currently trying to send to a HS-WS100+.

I tried the HS-FC200+ and I get something different (but also doesn't react to multicast):

```
08:52:38.574 DRIVER » [REQ] [SendDataMulticast]                                          [P: Normal]
                      │ transmitOptions: 0x01
                      │ callbackId:      1
                      └─[BasicCCSet]
                          payload: 0x63
08:52:38.576 SERIAL » 0x010f0014060000000000402001630101e0                                (17 bytes)
08:52:38.584 SERIAL « [ACK]                                                                   (0x06)
08:52:38.586 DRIVER   ACK received from controller for current transaction
08:52:38.588 SERIAL   The receive buffer is empty, waiting for the next chunk...
08:52:38.592 SERIAL « 0x0104011400ee                                                       (6 bytes)
08:52:38.594 SERIAL   Buffer := 0x0104011400ee                                             (6 bytes)
08:52:38.597 SERIAL » [ACK]                                                                   (0x06)
08:52:38.601 DRIVER « [RES] [SendDataMulticast]                                   [fatal_controller]
                        wasSent: false
08:52:38.604 DRIVER     the message for the current transaction could not be sent, scheduling attemp
                      t (2/3) in 500 ms...
08:52:38.607 SERIAL   The receive buffer is empty, waiting for the next chunk...
08:52:39.107 DRIVER » [REQ] [SendDataMulticast]                                        [attempt 2/3]
                      │ transmitOptions: 0x01
                      │ callbackId:      1
                      └─[BasicCCSet]
                          payload: 0x63
08:52:39.109 SERIAL » 0x010f0014060000000000402001630101e0                                (17 bytes)
08:52:39.116 SERIAL « [ACK]                                                                   (0x06)
08:52:39.118 DRIVER   ACK received from controller for current transaction
08:52:39.119 SERIAL   The receive buffer is empty, waiting for the next chunk...
08:52:39.123 SERIAL « 0x0104011400ee                                                       (6 bytes)
08:52:39.125 SERIAL   Buffer := 0x0104011400ee                                             (6 bytes)
08:52:39.146 SERIAL » [ACK]                                                                   (0x06)
08:52:39.149 DRIVER « [RES] [SendDataMulticast]                                   [fatal_controller]
                        wasSent: false
08:52:39.152 DRIVER     the message for the current transaction could not be sent, scheduling attemp
                      t (3/3) in 500 ms...
08:52:39.155 SERIAL   The receive buffer is empty, waiting for the next chunk...
08:52:39.654 DRIVER » [REQ] [SendDataMulticast]                                        [attempt 3/3]
                      │ transmitOptions: 0x01
                      │ callbackId:      1
                      └─[BasicCCSet]
                          payload: 0x63
08:52:39.656 SERIAL » 0x010f0014060000000000402001630101e0                                (17 bytes)
08:52:39.663 SERIAL « [ACK]                                                                   (0x06)
08:52:39.665 DRIVER   ACK received from controller for current transaction
08:52:39.667 SERIAL   The receive buffer is empty, waiting for the next chunk...
08:52:39.672 SERIAL « 0x0104011400ee                                                       (6 bytes)
08:52:39.674 SERIAL   Buffer := 0x0104011400ee                                             (6 bytes)
08:52:39.676 SERIAL » [ACK]                                                                   (0x06)
08:52:39.678 DRIVER « [RES] [SendDataMulticast]                                   [fatal_controller]
                        wasSent: false
08:52:39.681 DRIVER     the message for the current transaction could not be sent after 3 attempts, 
                      dropping the transaction
08:52:39.685 DRIVER   resuming send queue
08:52:39.689 SERIAL   The receive buffer is empty, waiting for the next chunk...
```

I've also tried messing with the transaction option.

**Comment by AlCalzone** [comment]
> 1406000000000040

Looks like you passed an array with 5x Node id 0 and 1x Node id 64 as the target. The controller cannot send that. All node IDs must exist.

**Comment by lukescott** [comment]
Strange. I was trying to target node 47. I used `send([47], 0)` or `send([47], 99)` with the Basic command class.

(Btw, I'm on the Pacific timezone. It's 8:30 AM right now)

**Comment by AlCalzone** [comment]
My devices respond now. I forgot the CC length in the serialized payload...

**Comment by lukescott** [comment]
Awesome! Giving it a try now.

**Comment by lukescott** [comment]
Works with all my devices 🎉 🎉 🎉

**Comment by AlCalzone** [comment]
`v2.14.0` will be released in a couple of minutes

**Pull request merged**
