### PR TITLE
fix(config): change Aeotec Minimote config to writeOnly

### PR DESCRIPTION
**Pull request by ualex73**

### CODE REVIEW

**Comment by ualex73** [comment]
@zwave-js-bot fix lint

**Comment by blhoward2** [comment]
It's quite possible. I'll check tonight. Can you remove the readonly override though? It should already be false in the template. In fact, if the template is only used here the change should be made to the template not in the file.

**Comment by ualex73** [comment]
@blhoward2 i have removed the readOnly lines.

**Review by blhoward2 — DISMISSED** [review]
This template isn't used for any other files, so changing the write only in the template is the better way to do this. The manual is silent on whether this is write only but I do see that OZW has theirs as such. Approved with my changes.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
@blhoward2 maybe we should give the `base_mode_5` a better name that makes it clear that it's intended for remotes?

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
