### PR TITLE
docs: update specs to release package DKD13867

### PR DESCRIPTION
**Pull request by ahochsteger**
These files have changed:

| Doc.Nr | Document | old version (date) | new version (date) | checked |
|----|----|----|---|---|
| SDS11846 | Z-Wave Plus Role Type Specification | 26 (2019-04-09) | 29 (2020-07-06) | ⭕ |
| SDS11847 | Z-Wave Plus Device Type Specification | 30 (2019-10-10) | 32 (2020-07-06) | ⭕ |
| SDS13425 | Z-Wave Plus Assigned Manufacturer IDs | 10 (2019-03-01) | 11 (2020-07-01) | ✔ |
| SDS13548 | List of defined Z-Wave Command Classes | 13 (2019-01-10) | 15 (2020-07-01) | ✔ |
| SDS13713 | Notification Command Class, list of assigned Notifications | 7 (2019-01-01) | 12 (2020-01-06) | ✔ |
| SDS13781 | Z-Wave Application Command Class Specification | 13 (2019-10-10) | 15 (2020-07-06) | ⚠ |
| SDS13782 | Z-Wave Management Command Class Specification | 12 (2019-10-01) | 14 (2020-06-01) | ⚠ |
| SDS13783 | Z-Wave Transport-Encapsulation Command Class Specification | 12 (2019-10-10) | 14 (2020-07-06) | ⚠ |
| SDS13784 | Z-Wave Network-Protocol Command Class Specification | 8 (2019-01-04) | 10 (2020-07-06) | ⭕ |
| INS13954 | Z-Wave 500 Series Appl. Programmers Guide v6.8x.0x | 7 (2018-06-14) | 13 (2020-04-21) | ⭕ |
| SDS14220 | Indicator Command Class, list of assigned Indicator and Property IDs | 3 (2019-05-06) | 4 (2020-01-01) | ✔ |
| SDS14223 | Z-Wave Command Class Control Specification | 9 (2019-10-10) | 11 (2020-07-06) | ⚠ |
| SDS14224 | Z-Wave Plus v2 Device Type Specification | 8 (2019-10-10) | 10 (2020-07-06) | ⭕ |

These files have been added:

| Doc.Nr | Document | version (date) | checked |
|----|----|----|---|
| SDS13738 | Z-Wave Plus Assigned Icon Types | 5 (2019-04-01) | ⭕ |
| SDS13907 | Simple AV Command Class, list of assigned AV Control codes | 1 (2017-04-03) | ⭕ |
| SDS13937 | Node Provisioning QR Code Format (S2, Smart Start) | 6 (2018-04-09) | ⭕ |
| SDS13944 | Node Provisioning Information Type Registry (QR code, Z/IP Gateway, SmartStart) | 9 (2020-07-06) | ⭕ |
| SDS14305 | Meter Table Monitor Command Class, list of assigned types, scales and datasets | 2 (2018-04-05) | ⭕ |
| SDS14622 | Anti-Theft Command Class, list of assigned Lock Entity IDs | 2 (2020-07-01) | ⭕ |

Legend: 
✔ checked, action taken
⭕ nothing to do right now
⚠ Action might be necessary

### CODE REVIEW

**Comment by AlCalzone** [comment]
Thanks. If you have some more time at hand, it would be nice to see for each changed file which revision was already checked into this repo. If not, I'll check it when I merge later.

**Comment by ahochsteger** [comment]
> Thanks. If you have some more time at hand, it would be nice to see for each changed file which revision was already checked into this repo. If not, I'll check it when I merge later.

You mean, where the filename has just renamed vs. where the contents have changed too?
I'll see what I can find out ...

**Comment by AlCalzone** [comment]
Only if the contents were changed. The revision (and the changes) are usually noted on some of the first pages.

**Comment by robertsLando** [comment]
@AlCalzone Have you ever thought about moving specs another repo? Most users that clone this will never use them (and them are heavy), I think that creating a repo would be better and cleaner

`zwave-js/zwave-specs`

**Comment by AlCalzone** [comment]
> Most users that clone this will never use them

I'm lazy and this way I can just run `start specs` and see the directory with the specs in them 😆

**Comment by robertsLando** [comment]
> I'm lazy and this way I can just run start specs and see the directory with the specs in them laughing

Yes but in future that will keep growing, just think about it

(I'm lazy like you in such things so i understand :laughing: )

**Comment by AlCalzone** [comment]
Maybe git submodules are the way to go :)

**Comment by ahochsteger** [comment]
@AlCalzone the changed revisions are now in the description of the PR. I did not copy the details of the change log, as this would not be a simple copy/paste - too much manual work since I'm lazy too ;-).

**Comment by AlCalzone** [comment]
> changed revisions are now in the description of the PR

Perfect! Some of this information needs to go into several places in this repo. The overview helps me to identify what is new.

**Comment by ahochsteger** [comment]
@robertsLando, @AlCalzone, concerning putting them into a separate repo:
If the purpose of node-zwave-js is to provide a spec compliant implementation in the long run I don't see a problem with keeping them in the repo.
There are some data files (*.xlsx) that may be of interest for automating some tasks (e.g. to track spec completeness).

**Comment by AlCalzone** [comment]
@ahochsteger I've hijacked your first comment to remember what I've already checked

**Comment by AlCalzone** [comment]
Points that might require action are tracked in https://github.com/zwave-js/node-zwave-js/issues/1142

**Comment by AlCalzone** [comment]
Thanks! I've got some work to do now :D

**Pull request merged**
