### PR TITLE
feat(config): change manufacturer and improve labels for nzw31s and nzw30s

### PR DESCRIPTION
**Pull request by towerhand**
Changing manufacturer from "NIE Technology Co., Ltd." to "Inovelli".

Edit: Fixing some discrepancies between the labels and descriptions for the NZW30, NZW30S, NZW31 and NZW31S files too.

### CODE REVIEW

**Comment by towerhand** [comment]
Not sure what to do with the param 3 ("LED Indicator") or where to find the proper info. The NZW30 have 3 options and NZW30S only 2 options, The NZW31 and NZW31S don't have it at all but I remember being able to change it with OZW.

**Review by AlCalzone — APPROVED** [review]
If you find out about that parameter 3, we can do it in a later PR

**Comment by AlCalzone** [comment]
Before I merge - is this ready? :D

**Comment by towerhand** [comment]
Yes I'm done. Thank you.

**Comment by AlCalzone** [comment]
No, thank you!

**Pull request merged**
