### PR TITLE
feat(config): add Namron 200W led dimmer

### PR DESCRIPTION
**Pull request by geirsf**
Added Namron LED Dimmer Z-Wave 200W based on 
- [1402756-Brukerveiledning-5 (1).pdf](https://github.com/zwave-js/node-zwave-js/files/6134678/1402756-Brukerveiledning-5.1.pdf),
- https://products.z-wavealliance.org/products/3797

### CODE REVIEW

**Comment by blhoward2** [comment]
@geirsf Earlier today we merged detailed documentation on device files, including a style guide and detailed guidance on templating. Could you please take a look at those, make any changes necessary to conform, and then let us know when you're ready for us to take a look line-by-line?

https://zwave-js.github.io/node-zwave-js/#/

**Comment by geirsf** [comment]
@blhoward2 sure.

**Comment by geirsf** [comment]
@blhoward2  have tried to update if after your styleguide

**Comment by AlCalzone** [comment]
@blhoward2 can you give this a second look?

**Review by blhoward2 — APPROVED** [review]
In this interest of getting this moving I just made the changes myself, but in the future please follow the style guide more closely. A number of the items I fixed explicitly contradict what is in the style guide.

**Review by AlCalzone — APPROVED** [review]

**Pull request merged**
