### PR TITLE
fix(config): add RU version of ZW100 (FW 1.10)

### PR DESCRIPTION
**Pull request by Inoy-D**
Add productId for RU version

### CODE REVIEW

**Comment by AlCalzone** [comment]
/cc @blhoward2

Shouldn't be too much of a conflict?

**Comment by Inoy-D** [comment]
No

**Comment by AlCalzone** [comment]
That question wasn't for you ;)
blhoward2 is editing all the Aeotec files, so it might affect him.

**Comment by Inoy-D** [comment]
ok

**Comment by blhoward2** [comment]
I'm already adding this so it's fine.

**Comment by AlCalzone** [comment]
@zwave-js-bot rename commit

**Pull request merged**
