### PR TITLE
fix(config): update Fibaro FGK-101 device config with units and options

### PR DESCRIPTION
**Pull request by alexz707**
Added units and options according lates FIBARO DOOR/WINDOW SENSOR FGK-10x Manual for FW 3.2
Regards Alex

### CODE REVIEW

**Comment by alexz707** [comment]
@zwave-js-bot fix lint

**Comment by alexz707** [comment]
@zwave-js-bot help

**Comment by alexz707** [comment]
@zwave-js-bot rename-commit

**Comment by alexz707** [comment]
@AlCalzone i think the PR is fine, but I don't know how to change the semantic PR title (I thought I already did!?)

**Comment by AlCalzone** [comment]
You had a space at the beginning :)

**Review by AlCalzone — CHANGES_REQUESTED** [review]
I know most of the file was already like this before, but since you're touching it already, let's clean up the parameters a bit. Please have a look at our [style guide](https://zwave-js.github.io/node-zwave-js/#/config-files/style-guide) for this.

Some things that come to mind:
- Avoid repeating the label in descriptions. Use descriptions only where necessary and try to fit the info into the label (but short)
- Parameter labels should be in "Title Case", Option labels are okay.
- The following parameters look like they should be split into [partial parameters](https://zwave-js.github.io/node-zwave-js/#/config-files/partial-parameters):
   - 3 (values 1, 2, 4)
   - 70
   - 71
   - 72
- No "..." in labels or descriptions

**Comment by AlCalzone** [comment]
@alexz707 are you planning to finish this?

**Comment by alexz707** [comment]
> @alexz707 are you planning to finish this?

Yes as soon as I have some time left I will TRY ;)
I'm not sure if I understood the partial params correctly so you will have to look over it for sure...

**Pull request closed without merging**
