### PR TITLE
feat(config): import Z-Wave Alliance Files batch 2

### PR DESCRIPTION
**Pull request by blhoward2**
Batch 2 for volunteer review

### CODE REVIEW

**Comment by jmmit** [comment]
Taking on the first 5 files initially.

**Comment by blhoward2** [comment]
@jmmit Are you still working on this one? Or should someone take it over after where you've stopped? No rush but I want to ensure they're all being worked on.

**Comment by jmmit** [comment]
I'm still good to continue just work had got in the way last few days if you aren't in rush I'll pickup again in a day or two (might have some time tonight).

**Comment by blhoward2** [comment]
No problem, thanks. Just checking in.

**Comment by jmmit** [comment]
Top 10 files now done.

**Pull request closed without merging**
