### PR TITLE
chore(config): disallow leading zeroes in firmware versions

### PR DESCRIPTION
**Pull request by AlCalzone**
/cc @robertsLando @blhoward2

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
LGTM. BTW do you have some units test for config files linting?

**Comment by AlCalzone** [comment]
Uh you mean tests for the tests? No 😅 I test those changes by hand.

**Comment by robertsLando** [comment]
> Uh you mean tests for the tests? No sweat_smile I test those changes by hand.

I mean something like creating a `ConfigValidator.ts` where you place all the validation functions (each one could return `true` if valid or an error string if not) so you can write units test for them. Just a thought btw :)

**Comment by AlCalzone** [comment]
Accepting PRs 😁

**Pull request merged**
